### ISSUE TITLE
Configure Columns hanging

### ISSUE THREAD

**Issue by slhyatt77** [alexed1/LightningFlowComponents#1028]
I'm getting hung up on the Configure Columns button. It just sits there and never moves to show anything to configure.
![image](https://user-images.githubusercontent.com/39288702/150592814-ce159d55-d506-41bc-a89b-5ff81a31a328.png)

**Comment by ericrsmith35** [comment]
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/#Restrictions

If you see this error when trying to Configure Columns, try going to Setup > Security > Session Settings and unchecking “Enable clickjack protection for customer Visualforce pages with headers disabled“. Also, in your Setup > User settings, make sure both Debug Mode and Development Mode are Unchecked.

**Comment by slhyatt77** [comment]
That was it! Many thanks!
