### ISSUE TITLE
Datable - Lookup Column - Displaying Link instead of text

### ISSUE THREAD

**Issue by AndyHaas** [alexed1/LightningFlowComponents#1032]
### Steps to reproduce

Object Type: OpportunityLineItem
Field Attempting to Display: Name, Product2Id, OpportunityId

Comments:
We have this same datatable working on another object that is displayed just before this data table. So this is an object-specific issue while using the data table.

### Expected behaviour
Tell us what should happen

What should be happening is that the field should be showing the name of the Opportunity Line Item.

### Actual behaviour
Tell us what happens instead

What is happening is that the link to the opportunity line item is being displayed and when we uncheck the navigation box within the Datatable configuration the field is left blank.

### Screenshots
![image](https://user-images.githubusercontent.com/22582720/151594359-c4486948-634b-48d7-b2d5-4b6b9fdf001c.png)

### Debug Logs
NA

**Comment by Duha-H** [comment]
Chiming in as I've encountered this recently. This typically happens for me when the input collection does not have a value populated in the Name field. For instance, if the OpportunityLineItem collection in this case is being fetched using a Get Records element in flow, and fields are stored using one of the "Choose fields..." options in **How to Store Data**, I needed to make sure that the Name field is specified as a field to store as well.

Not sure if this is the same issue encountered here, but that's what fixed it for me.

**Comment by ericrsmith35** [comment]
Thanks for the tip @Duha-H

**Comment by cadillacben** [comment]
I'll echo eric's comment on security.  I've had a similar issue where a lookup shows as an ID vs. a name and I had to give edit access to the source object to resolve it.  Or if a clickable link isn't desired, just do a text formula field.
