### ISSUE TITLE
LightningLookupController Test class

### ISSUE THREAD

**Issue by bw-ath** [alexed1/LightningFlowComponents#1033]
### Documentation issues

I am trying to create an unmanaged package which includes the quick lookup component, and SF is giving an error that there is no test class for LightnintLookupController. Is there one available? Forgive me I'm not a developer per se.

If your problem stems from wrong, outdated, or unclear documentation, please:

1. Submit a link to the documentation here:
2. Explain why it is wrong or unclear:
3. Suggest any changes:

### Support requests

We do not offer support for these components, and help requests will be closed.

**Comment by ericrsmith35** [comment]
Yes, there is a test class.  All of the source code can be found here.  https://github.com/alexed1/LightningFlowComponents/tree/master/flow_screen_components/quickLookup
