### ISSUE TITLE
My version of the navigate button

### ISSUE THREAD

**Issue by danhowellnz** [alexed1/LightningFlowComponents#104]
Hi,

Thanks for all of your hard work on the flow lightning component. I have come up with a more comprehensive solution:
https://github.com/danhowellnz/NavigateButton

It might be useful for the masses. 

Cheers,
Daniel

**Comment by alexed1** [comment]
This is great, Dan. Can you record a screencast that shows how to use the different features? If you do that, we'll create a blog post at https://medium.com/@alexedelstein and an install page at https://sites.google.com/view/flowunofficial/flow-screen-components  

Give it a different name to distinguish it from the button at https://sites.google.com/view/flowunofficial/flow-screen-components/navigation-button  .... perhaps something like AdvancedNavigationButton

**Comment by alexed1** [comment]
@danhowellnz checking in on this.

**Comment by danhowellnz** [comment]
My apologies for being show. We had one video made last week. I'm hoping we will have a blog explaining the features this week.

**Comment by danhowellnz** [comment]
Finally, Here you go: https://gravitylab.nz/lightning-navigation-button/

**Comment by alexed1** [comment]
Closing as successful.
