### ISSUE TITLE
*Datatable* - Pre-selected records not available in output 

### ISSUE THREAD

**Issue by PhilippReinholdMaag** [alexed1/LightningFlowComponents#1044]
Datatable Version #: 3.3.2

#Steps to reproduce the behavior:
1. Fill a relevant Collection into "Which records are already selected?" in the datatable data source.
2. Add a screen which displays the selected record information
2. Run Flow
3. Verify that in the predefined records are automatically selected (Do not actively select another record within the same datatable)
4. Click next
4. See that the Variable  .....outputSelectedRow.Id is empty

## Expected behaviour
Even if the user does not change the record within the datatable, i would assume that the preselected record would be available in the output variable and therefore ....outputSelectedRow.Id would not be empty.

### Actual behaviour
The output variable is empty

**Comment by ericrsmith35** [comment]
This should be resolved in v3.4.5
