### ISSUE TITLE
Datatable v3.4.5 Apex Action error: Unable to read SObject

### ISSUE THREAD

**Issue by boooney** [alexed1/LightningFlowComponents#1056]
1. Start flow loop
2. Capture field values on a screen
3. Assign those field values to a new single record variable using an Assignment element
4. Add single record variable to a record collection with an Assignment element
5. End loop
6. On confirmation screen, add datatable with record collection variable from above to show records details before creating records

### Expected behaviour
Datatable will show record data

### Actual behaviour
While debugging, Flow shows error message "Apex Action error: Unable to read SObject"
After clicking Ok, The datatable shows "This table currently has no data to display"

**Comment by ericrsmith35** [comment]
When creating new records to display in the datatable that have not yet been written to the Object, you need to include a unique "dummy" recordId for each record.  It should be 15 characters starting with the same 3 characters as the regular Ids for that SObject.  For example, for Opportunity records, use 006000000000001, 006000000000002, 006000000000003, ...

**Comment by boooney** [comment]
Super helpful. Thanks.
