### ISSUE TITLE
Datatable - Configure Columns - Error Message after editing Label to include "%"

### ISSUE THREAD

**Issue by henrydmaj** [alexed1/LightningFlowComponents#1069]
### Steps to reproduce

1. Click Configure Columns
2. Add Number field to table
3. Click Change Label on this Number Field
4. Add the % symbol to the Label
5. Click Save
6. Click Done
7. Error Appears

### Expected behaviour
Change should be accepted with no Error Message and the updated label should appear in the datatable when the flow is run

### Actual behaviour
The change is not accepted, an erro message appears and the updated label does not appear in the datatable when the flow is run

### Error Message
Something went wrong

Save your flow and refresh the page. If the problem persists, contact Salesforce Customer Support. Error ID: 698060072.

If you're working on a screen component, check your component configuration for invalid values.

URIError: malformed URI sequence throws at https://xxxxxx--dev.lightning.force.com/auraFW/javascript/GLwpaE1i74371O4RpOURgA/aura_prod.js line 100 > Function line 8 > eval:4:45331

### Component Version
3.4.5

**Comment by ericrsmith35** [comment]
This has been identified and the fix will be included in the next release.

**Comment by henrydmaj** [comment]
Brilliant, thanks Eric
