### ISSUE TITLE
How do I install Rich Text Input lightnignflow component

### ISSUE THREAD

**Issue by anjlidaryani** [alexed1/LightningFlowComponents#108]
Hi,

I am trying to install 'Rich Text Input' component to Salesforce. When I click it, it just downloads the zip file rather than taking me to Salesforce. What do I need to do after downloading the zip file?

Thanks

**Comment by alexed1** [comment]
I've updated the installation link at this page to provide an installer: https://sites.google.com/view/flowunofficial/flow-screen-components/rich-text-input
