### ISSUE TITLE
*Datatable* - Table Height - Value is ignored

### ISSUE THREAD

**Issue by smunkelt** [alexed1/LightningFlowComponents#1082]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### Steps to reproduce

1. Create a GetRecords steps to retrieve ServiceAppointment record
2. Dont retrieve all fields but only AppointmentNumber
3. Add a screen component with a datatable, Select Object = Service Appointment; Display with records = previous query step.
4. Add field from GetRecord step to be displayed via Configure Columns
5. Set Table Height to 400px
6. Leave all other settings as is

### Expected behaviour
the datatable will be displayed in a container with a height of 400px. If more records need to be displayed scrolling functionality is available.

### Actual behaviour
Any value in field Table Height is ignored. The datatable shows all records in one long list without scrolling. 

### Screenshots
![image](https://user-images.githubusercontent.com/5795588/158268089-07ea2c57-9477-4e49-9bb1-49635aa07c88.png)

### Debug Logs
If applicable, please insert debug logs here
<details>
<summary>Debug Log Information</summary>

```
Paste the output of the logs here.
```
</details>

**Comment by ericrsmith35** [comment]
This has been addressed and will be fixed in the next release (v3.5.0)
