### ISSUE TITLE
*{!OppTerrAssignDefaultLogicFilter}* - _({!Select Id, AccountId, Territory2Id from Opportunity where})_ - {!No such column 'Territory2Id' on entity 'Opportunity'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names}

### ISSUE THREAD

**Issue by carotmg** [alexed1/LightningFlowComponents#1085]
### Installation process failed

* When you tried to install the Version 2.7.7, the next error appears: 
### Steps to reproduce

- Install version 2.7.7 in a Sandbox. 

Problem:

1.  Apex compile failure
Apex class OppTerrAssignDefaultLogicFilter: line 30, column 15:
Select Id, AccountId, Territory2Id from Opportunity where
                      ^
ERROR at Row:1:Column:23
No such column 'Territory2Id' on entity 'Opportunity'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.

2.  Apex compile failure
Apex class OppTerrAssignDefaultLogicFilter: line 61, column 45: Invalid type: Schema.ObjectTerritory2Association

3.  Apex compile failure
Apex class OppTerrAssignDefaultLogicFilter: line 61, column 13: Invalid type: ObjectTerritory2Association

4.  Apex compile failure
Apex class OppTerrAssignDefaultLogicFilter: line 62, column 69: Variable does not exist: ota

5.  Apex compile failure
Apex class OppTerrAssignDefaultLogicFilter: line 64, column 33: Variable does not exist: ota.Territory2.Territory2Type

6.  Apex compile failure
Apex class OppTerrAssignDefaultLogicFilter: line 66, column 45: Variable does not exist: ota

7.  Apex compile failure
Apex class OppTerrAssignDefaultLogicFilter: line 66, column 62: Variable does not exist: ota.Territory2.Territory2Type

8.  Apex compile failure
Apex class OppTerrAssignDefaultLogicFilter: line 67, column 22: Variable does not exist: ota.Territory2.Territory2Type

9.  Apex compile failure
Apex class OppTerrAssignDefaultLogicFilter: line 72, column 45: Variable does not exist: ota

10.  Apex compile failure
Apex class OppTerrAssignDefaultLogicFilter: line 83, column 9: Invalid type: Territory2Model

11.  Apex compile failure
Apex class OppTerrAssignDefaultLogicFilter: line 85, column 12: Variable does not exist: models

12.  Apex compile failure
Apex class OppTerrAssignDefaultLogicFilter: line 86, column 29: Variable does not exist: models

### Expected behaviour
It should be installed successfully.

### Actual behaviour
It doesn't 

```
</details>

**Comment by ericrsmith35** [comment]
This looks like it may be related to a Test Class unique to your org that is not part of the component you are trying to install.  When installing, select Advanced Options and pick "Compile only the Apex in the package".

![image](https://user-images.githubusercontent.com/24724447/159780993-551fd8cd-36dc-413d-999a-92fa8129ba45.png)

**Comment by carotmg** [comment]
It worked! Thank you very much for the quick response.
