### ISSUE TITLE
Using "Contains" in "Where" clause

### ISSUE THREAD

**Issue by wallyworley** [alexed1/LightningFlowComponents#109]
Not an issue but a question. I can get the WHERE clause to work but only on things like Title='Vice President' etc. I'm trying to get this to work if the Title CONTAINS a certain word. Any help is greatly appreciated.

**Comment by ericrsmith35** [comment]
Instead of using CONTAINS, use LIKE.

Title LIKE '%Vice President%'

**Comment by wallyworley** [comment]
Worked great!! Thanks so much.
