### ISSUE TITLE
SOQL Relationships Not Supported

### ISSUE THREAD

**Issue by veaux** [alexed1/LightningFlowComponents#113]
For lookupFSC the use of FieldName__r.FieldName2__c does not seem to be supported for Custom Metadata Types. Issue seems to be that an ORDER BY is automatically created in the SOQL statement and ORDER BY relationship fields is not supported in Custom Metadata Types. No way to remove that it seems.

Same issue if using nested SOQL. The auto addition of the LIMIT is causing the SOQL to fail for Custom Metadata Types.

**Comment by ericrsmith35** [comment]
Which component are you having this issue with?

**Comment by ericrsmith35** [comment]
Have you tried creating a version of the component with line 67 (soql += ' ORDER BY ' + displayedFieldName + ' Limit 100';) of the Apex Class (LightningLookupController) commented out?

**Comment by veaux** [comment]
We were using the managed package now so no hadn't tried commenting anything out. Uninstalling this and trying as an unmanaged package might resolve. Will try that tomorrow.

**Comment by veaux** [comment]
Not looking as straightforward as I thought. We tried installing what was in the lookupFSC folder as an Unlocked Package but I think we are missing something bc not working even just leaving code as is.

**Comment by ericrsmith35** [comment]
I assume that included the Apex Class, Static Resource & Lightning Event components?

**Comment by veaux** [comment]
Not initially but yes, updating the Lightning Controller to remove the LIMIT clause and commenting out a few lines in the Apex Class seemed to do the trick! Sorry Im not strong enough in programming to contribute to the application though. Thanks for help!

**Comment by veaux** [comment]
Maybe closed prematurely. Getting script thrown exception error in what looks like line 78 of LightningLookupController.cls. SOQL works fine and can see correct output in logs. Appears to be the String.valueOf doesn't like that this is a relationship field?

`16:39:22:021 VARIABLE_ASSIGNMENT [86]|ex|"common.apex.runtime.impl.ExecutionException: Invalid field hdone__ResponseMapping__r.hdone__Response_Option__c for hdone__ResponseCategory__mdt"|0x6229fe1`

**Comment by ericrsmith35** [comment]
The relationship field could be an issue here.  How about creating a custom formula field with the relationship there and then using that in your lookup?

**Comment by veaux** [comment]
Its custom metadata type, cant use formulas.

**Comment by ericrsmith35** [comment]
Where are you using "hdone__ResponseMapping__r.hdone__Response_Option__c"?

**Comment by veaux** [comment]
I2_Display Which Field?

**Comment by ericrsmith35** [comment]
The component is designed to only work with a single Object at a time.  If you are using the custom metadata just to get the name of a field in the object you are doing the lookup in, you should first get that value with a formula or Record Lookup before calling the component.

**Comment by veaux** [comment]
Ok I'll close then thanks for looking at it. With custom metadata types formulas are not supported and since it's a 2 objects away can't easily get with a lookup...well and if could then I'd have to use something else anyway since values would be stored in Sobject Collection at that point.
