### ISSUE TITLE
Collection Actions - GetRecordsFromIds "An Apex error occurred: System.QueryException: unexpected token: 'null'"

### ISSUE THREAD

**Issue by boooney** [alexed1/LightningFlowComponents#1134]
1. Follow guide https://unofficialsf.com/hydrate-ids-into-records-with-get-records-from-ids/ to configure the GetRecordsFromIds Apex Action in a scheduled flow.
3. run GetRecordsFromIds Apex Action using the following inputIds = {!Unique_Approvers_Invoices.fieldValueCollection} ([0053p000006s0Y4AAI,0051R00000HYNy7QAH,0053p0000079dUCAAY,00536000002pygbAAA,0051R00000HYLq6QAH,005360000075Q69AAE,0053p000006s0S2AAI,0051R00000HYLprQAH,0053p000006s15YAAQ,005360000016NDFAA2,0051R00000HYLpcQAH])
4.5. See error "An Apex error occurred: System.QueryException: unexpected token: 'null'"

### Expected behaviour
I have a fieldValueCollection of user Ids that I want to "hydrate" into User Records using the GetRecordsFromIds Apex Action

### Actual behaviour
I get the error message

### Screenshots
![image](https://user-images.githubusercontent.com/11412333/173209861-266cf913-5cdd-4b25-8328-b068f140152c.png)

**Comment by alexed1** [comment]
You need to provide the fieldNames input as well. The action should probably be upgraded to just fetch all fields, now that that is possible https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_fields.htm. If that solves your issue, go ahead and close this.

**Comment by boooney** [comment]
Thanks much.  I'm happy to help update the doc at Unofficialsf if you'd like me to.
