### ISSUE TITLE
Quick Lookup - Install Links are bad for v1.0.3

### ISSUE THREAD

**Issue by bottomlinebrokers** [alexed1/LightningFlowComponents#1136]
Install links on the unofficialsf page (https://unofficialsf.com/lookup/#install) for v1.0.3 lead you to install Datatable 4.0.5, NOT Quick Lookup, for both PROD and Sandbox links.  I had to install v1.0.2.  Please find

**Comment by ericrsmith35** [comment]
THis has been updated to show the correct links.

**Comment by bottomlinebrokers** [comment]
Eric - Thank you for such rapid responses.  It helps us folks in the middle of complex flowing! 🙂

Mark
________________________________
