### ISSUE TITLE
Render label attribute with Rich Text HTML tags in RichTextInputFS or Text Area Plus

### ISSUE THREAD

**Issue by samanthashain** [alexed1/LightningFlowComponents#1138]
**Is your feature request related to a problem? Please describe.**

Display Text components followed by RichTextInputFS or TextArePlus components leave a visual spacing issue.  I would prefer to use the Label attribute on either component, howevever the label attribute does not render HTML tags.  We have a requirement that includes Rich Text labeling.  Use Case is "questions" on a Grant Application form.

**Describe the solution you'd like**

Be able to use HTML tags (composed in Text Template resource) in Label attribute in Lightning Component.
Open to storing question text in Text Template variables or directly in the Label field for each component.

**Describe alternatives you've considered**

Use Display Text component and deal with spacing issues.

**Additional context**

See Loom video recording: https://www.loom.com/share/b13304403d724e2c8069a5ab578c80e8

**Comment by jdayment** [comment]
This is supported in the next release of Text Area Plus!
