### ISSUE TITLE
FlexCard - Community user - Field not shown unless record shared

### ISSUE THREAD

**Issue by cadillacben** [alexed1/LightningFlowComponents#1140]
### Steps to reproduce

1. Have a community page with a flow on it
2. set the flow to run in system mode without sharing
3. Somehow share one account to the community user (account team or manual share)
4. Choose another account that is not shared
5. perform a get accounts to get the above accounts
6. add flex cards to a screen based on the get records
7. add shipping street and another field, number of fields doesn't matter
8. Note only the shared record's fields show, but both show the Name in the header

### Expected behaviour
Both records should display the requested field data

### Actual behaviour
Only the shared record shows the requested field data
Note that this works as expected in debug mode, so you have to actually login as the user

### Screenshots
In the below screenshot the account on the left is shared and the account on the right is not shared.  They just happen to have the same name, but they're different.

![image](https://user-images.githubusercontent.com/17458691/173904059-14cb2e4e-eea7-4a00-a8c1-87598e6d2b65.png)

**Comment by jdayment** [comment]
The card header and fields displayed in the card process data differently. The header is referencing field data from the get records portion of the flow itself where the data on the fields in the fields displayed is using lightning-record-view-form to populate the field values so it is actually getting those values oob vs the flow getting the fields and values. So for example I can get All Accounts and select the fields I get to only 'Name' and if I select to display multiple fields it will still display all of the fields and values I selected in the CPE. From the component library "lightning-record-view-form requires a record ID to display the fields on the record. It doesn't require additional Apex controllers or Lightning Data Service to display record data. This component also takes care of field-level security and sharing for you, so users see only the data they have access to." So in short it is working kind of as designed the fields and field value are being processed outside of the flow in the card so we can't override sharing but the name we are getting from within the flow. Short term solution would be to have a session based permission until I can solution and build a way to only show the cards when there is complete data.

**Comment by cadillacben** [comment]
Thanks @jdayment 
Ok, I wondered how the data came in after not seeing apex for it and knowing it took in a collection.  I did consider a session based permission, but can you share that way too?

**Comment by cadillacben** [comment]
> Here you go https://help.salesforce.com/s/articleView?id=sf.perm_sets_session_activate_flow.htm&type=5 I think there are some popular blog posts floating around as well I think Jen Lee had a really good one. (as a note I don't know if I have implemented a session based permission for a community user so there might be more to it for that user type)

Thanks for the link.  I did see that, but unless I'm missing something those only grant permissions vs. sharing.  I guess I could do view all, lol.

**Comment by jdayment** [comment]
Yeah that is what you would have to do there isn't an elegant temporary
share option 🤪

**Comment by cadillacben** [comment]
Ah, ok I was hoping to learn about some new sharing method.  Cool, I appreciate the help here and with all the other components you work on.  You make us wannabe developers look good.
