### ISSUE TITLE
*DataTable* - Table output - GACK error

### ISSUE THREAD

**Issue by cadillacben** [alexed1/LightningFlowComponents#1142]
I've reported this to SF, but wanted to add it here for awareness and to validate it's not just the two orgs I tried.  I've tried in two sandboxes with different versions along with a completely different org, same results.  Versions 4.0.5 and 4.0.3.  It started 6/17/22.

### Steps to reproduce

1. get account records, other objects work fine
2. display a datatable with account records
3. select a record
4. advance to the next screen

### Expected behaviour
Next screen displays and table outputs it's data joy

### Actual behaviour
Unfortunately, there was a problem. Please try again. If the problem continues, get in touch with your administrator with the error ID shown here and any other related details. Error ID: 1378965438-5429 (-414970662)

### Screenshots
![image](https://user-images.githubusercontent.com/17458691/174323184-e0d69d82-374f-4415-aed1-da2f7ebaf8d0.png)
![image](https://user-images.githubusercontent.com/17458691/174323230-9d0526cd-e4b3-4e6d-a5fa-0698a76e522d.png)

### Debug Logs
debug logs don't show any information related to an error

**Comment by ericrsmith35** [comment]
Try individually selecting the fields in the Account object and do not include any GeoLocation fields.
