### ISSUE TITLE
FlowScreenComponentsBasePack 3.0.7 - Upgrade error

### ISSUE THREAD

**Issue by TonyK88** [alexed1/LightningFlowComponents#1159]
1. Have FlowScreenComponentsBasePack 2.7.7 installed 
2. Upgrade to FlowScreenComponentsBasePack 3.0.7

### Expected behaviour
Should upgrade sucessfully

### Actual behaviour
Received the below error email that "Package FlowScreenComponentsBasePack Install Failed". I searched FlowTableViewDefinition__c. and there are no records.

Your request to install package "FlowScreenComponentsBasePack ver 0.1" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.

If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.

Organization: Onyx CenterSource (00D530000004eqL)
User: Tony Kidd (005530000011iMX)
Package: FlowScreenComponentsBasePack (04t5G000003rUyA) Error Number: 565720467-81437 (-2134128278)
Problem:

1. (FlowTableViewDefinition__c.Alignments__c) Cannot change type due to existing data
FlowTableViewDefinition__c.Alignments__c: Cannot change type due to existing data

2. (FlowTableViewDefinition__c.Cell_Attributes__c) Cannot change type due to existing data
FlowTableViewDefinition__c.Cell_Attributes__c: Cannot change type due to existing data

3. (FlowTableViewDefinition__c.Edits__c) Cannot change type due to existing data
FlowTableViewDefinition__c.Edits__c: Cannot change type due to existing data

4. (FlowTableViewDefinition__c.Field_API_Names__c) Cannot change type due to existing data
FlowTableViewDefinition__c.Field_API_Names__c: Cannot change type due to existing data

5. (FlowTableViewDefinition__c.Filters__c) Cannot change type due to existing data
FlowTableViewDefinition__c.Filters__c: Cannot change type due to existing data

6. (FlowTableViewDefinition__c.Icons__c) Cannot change type due to existing data
FlowTableViewDefinition__c.Icons__c: Cannot change type due to existing data

7. (FlowTableViewDefinition__c.Labels__c) Cannot change type due to existing data
FlowTableViewDefinition__c.Labels__c: Cannot change type due to existing data

8. (FlowTableViewDefinition__c.Other_Attributes__c) Cannot change type due to existing data
FlowTableViewDefinition__c.Other_Attributes__c: Cannot change type due to existing data

9. (FlowTableViewDefinition__c.Type_Attributes__c) Cannot change type due to existing data
FlowTableViewDefinition__c.Type_Attributes__c: Cannot change type due to existing data

10. (FlowTableViewDefinition__c.Widths__c) Cannot change type due to existing data
FlowTableViewDefinition__c.Widths__c: Cannot change type due to existing data

11. (FlowTableViewDefinition__c.Wraps__c) Cannot change type due to existing data
FlowTableViewDefinition__c.Wraps__c: Cannot change type due to existing data

**Comment by ericrsmith35** [comment]
https://docs.google.com/document/d/1rqOREveltPp9sVPkEopt7N1ZPGvLC2ZTDzPzpVYms68/

**Comment by TonyK88** [comment]
Hey Eric - that fixed it! Thanks very much for responding and so quickly.

Tony

**Comment by ericrsmith35** [comment]
That's great news.
