### ISSUE TITLE
Enable to install FlowScreenComponentsBasePack du to existaing Data

### ISSUE THREAD

**Issue by WdrFafa** [alexed1/LightningFlowComponents#1162]
I'm trying installing the V3.0.7 FlowScreenComponentsBasePack in order to install the last Datatable version and i can't due to existing data... but i can't erase either this datas

![image](https://user-images.githubusercontent.com/103574978/177729060-538fa4fa-6a7f-4c87-80cb-270da02a3a28.png)

**Comment by ericrsmith35** [comment]
https://docs.google.com/document/d/1rqOREveltPp9sVPkEopt7N1ZPGvLC2ZTDzPzpVYms68/
