### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by whitefusion17** [alexed1/LightningFlowComponents#1170]
Hello the nee version is failing when you install as it states you need version 3.0 before installing

**Comment by ericrsmith35** [comment]
Which component?

**Comment by whitefusion17** [comment]
FlowActionsBasePack I will try and post a screengrab of the issue now

**Comment by whitefusion17** [comment]
![image](https://user-images.githubusercontent.com/71931027/180425368-2d32bdbb-3d81-444a-812d-4113a47ffbf5.png)

**Comment by whitefusion17** [comment]
This is the link https://test.salesforce.com/packaging/installPackage.apexp?p0=04t5G000003rV1TQAU

Thats is on this page I can see it was updated yesterday https://unofficialsf.com/flow-action-and-screen-component-basepacks/

**Comment by whitefusion17** [comment]
Any joy ?

**Comment by whitefusion17** [comment]
Ok sorted this issue now
