### ISSUE TITLE
Upgrade FlowScreenComponentsBasePack Production

### ISSUE THREAD

**Issue by AndyHaas** [alexed1/LightningFlowComponents#1174]
### Documentation issues

If your problem stems from wrong, outdated, or unclear documentation, please:

1. Submit a link to the documentation here:
https://docs.google.com/document/d/1rqOREveltPp9sVPkEopt7N1ZPGvLC2ZTDzPzpVYms68/edit
2. Explain why it is wrong or unclear:
Within production, I am trying to update the Field API Names to what the document has above but getting errors because the field is referenced in APEX Class. In Sandbox, I was able to delete the class and install the updates.

There were custom validation error(s) encountered while saving the affected record(s). The first validation error encountered was "Cannot change field type of a custom field referenced in Apex class or trigger: <a href="/01p8Y000004hgYX">QuickRecordViewController</a>".

### Support requests

We do not offer support for these components, and help requests will be closed.

**Comment by AndyHaas** [comment]
@ericrsmith35 any suggestions? I have other flows that use these components so an uninstall isn't plausible.

**Comment by ericrsmith35** [comment]
I am not familar with QuickRecordViewController.  What package is it a part of?

**Comment by AndyHaas** [comment]
It is a part of the FlowScreenComponentsBasePack package. I am upgrading from 2 to 3

**Comment by AndyHaas** [comment]
<img width="979" alt="Screen Shot 2022-07-26 at 11 24 10" src="https://user-images.githubusercontent.com/22582720/181059648-190563cb-1434-40cc-a835-d3f86294dc74.png">
<img width="1007" alt="Screen Shot 2022-07-26 at 11 23 51" src="https://user-images.githubusercontent.com/22582720/181059652-3a584e9e-3f56-4882-b40c-d4721090075b.png">

**Comment by JCUK89** [comment]
Hi @AndyHaas & @ericrsmith35 

I was able to get around this issue by installing version 3.0.6 first. 

Once I Installed it, I was able to change the Field_API_Names__c data type to Long Text Area, 2000 character limit. 

Then, I was able to install version 3.0.10 no problem.

**Comment by AndyHaas** [comment]
@JCUK89,
This worked! This would be a good note to put into the documentation. Not sure what difference is causing this particular issue, but good catch.

**Comment by ericrsmith35** [comment]
I have added a note to the documentation.
