### ISSUE TITLE
Customisable Banner - please include font weight

### ISSUE THREAD

**Issue by JodieM** [alexed1/LightningFlowComponents#1211]
**Describe the solution you'd like**
I'd really like font weight to be an option on the banner

**Additional context**
I am trying to get the flow to look as close as possible to standard related record components, and without font weight I can't make the header bold enough to look like standard

**Comment by alexed1** [comment]
Hi, Jodie...can you clarify which component you're referring to? [Is it this one?](https://unofficialsf.com/from-sharad-style-your-flow-with-headers-banners-rules-formatting-and-more/)

**Comment by JodieM** [comment]
Yes that's the one, thanks @alexed1

**Comment by alexed1** [comment]
Fixed by Andy Haas in version 1.0.1 https://unofficialsf.com/from-sharad-style-your-flow-with-headers-banners-rules-formatting-and-more/
