### ISSUE TITLE
*File Upload Improved* - _(Required)_ - Requiredness fails

### ISSUE THREAD

**Issue by JodieM** [alexed1/LightningFlowComponents#1213]
### Steps to reproduce

Set up File Upload as per image attached. 
Set Required = True (mine is set by a Formula which equates to true, but I had it set as true previously). 
Run Flow
DO NOT upload Files

### Expected behaviour
A Message Appears to say you need to upload files

### Actual behaviour
Flow fails with error message of "Flow encountered an error when processing and converting between data types."

### Screenshots
[Settings](https://drive.google.com/file/d/1QhXSOzlrBoN76DMU__EVgQeQAEPfgZiP/view?usp=sharing)
[Error](https://drive.google.com/file/d/1P1-PKLk_RrxomOS4Y3Pjr4kh7OPl-Suq/view?usp=sharing)

### Debug Logs
Nothing appears in the debug logs that is of any help

**Comment by JodieM** [comment]
Also there is no required indicator showing

**Comment by AndyHaas** [comment]
@JodieM 
I can't see your images, but I went ahead and loaded the component within my test org to validate the requiredness is working and I am getting my custom message and the default message that is set if you don't set a message.

Check the following settings with yours.
The two squares in Orange are required. The message is optional
<img width="316" alt="Screen Shot 2022-09-15 at 18 38 49" src="https://user-images.githubusercontent.com/22582720/190526937-81e4323f-4fcd-45af-bded-2ac10e7e099a.png">

**Comment by JodieM** [comment]
I've just shared the images (bizarre, they were public) but both of those
settings arr correct. Maybe it has something to do with multiple upload
components on the one page?

**Comment by AndyHaas** [comment]
Can you check the debug output to see what that variable is set to when you run it? You can do this within Flow Builder and you should expect to see a True/False response.

**Comment by JodieM** [comment]
OMG. You are NOT going to believe the cause! And you definitely won't believe how long it took me to find the cause! It was due to #1223. Yep. Bizarre. My guess is that there is some javascript run to validate that the files are uploaded and that javascript running actually caused the Lightning Input FSC fields to refresh and they freaked out and all I could see is that I had not uploaded the files. Dammit. Trap for putting two unofficialSF components in one flow at once. Wow. What an expensive lesson.
