### ISSUE TITLE
*Datatable v.4.0.11 (also v.4.0.9)* - _(Saving Edits)_ - Consecutive Edits to Non-Date Fields Throw Error on Save

### ISSUE THREAD

**Issue by williusTech** [alexed1/LightningFlowComponents#1215]
### Steps to reproduce

From a datatable LWC surfaced through a flow:

1. Edit any combination of rows/columns, then click [Save] _(these will be referred to as “Round 1 Edits” later)_
2. Edit any combination of rows/columns, and click [Save] _(these will be referred to as “Round 2+ Edits” later)_

### Expected behaviour
- Round 2+ Edits are saved and combined with Round 1 Edits
- Any further edits _(Round 3, Round 4, ...)_ are also saveable

### Actual behaviour
- Component error screen is displayed as shown below, for every subsequent [Save] attempt.
- BUT can save Round 2+ edits if the following criteria are met after exiting the error message:
  - Clicking [Cancel] with the same edits
  - Editing more rows to include additional changes to at least two unique date fields, then clicking [Save]

### Screenshots
![image](https://user-images.githubusercontent.com/106705779/190230025-4dd7bc8d-8aa6-4523-b181-df0bb1858d25.png)

<details>
<summary>Screenshot Contents Summary</summary>
From Screenshot:

- **Message**: "[t[e].slice is not a function]"
- **Component** Descriptor: markup://c:datatable
- **File** **Name**: https://xxxxxxxxxx.sandbox.lightning.force.com/lightning/action/quick/modules/c/datatable.js
- **Function**: eval
- **Line**: 1
- **Column**: 37807
- **Stack Trace**: "eval()@https://xxxxxxxxxx.sandbox.lightning.force.com/lightning/action/quick/modules/c/datatable.js:1:37087
eval()@https://xxxxxxxxxx.sandbox.lightning.force.com/lightning/action/quick/modules/c/datatable.js:1:37023
$e.handleSave()@https://xxxxxxxxxx.sandbox.lightning.force.com/lightning/action/quick/modules/c/datatable.js:1:36317"
</details>

**Comment by ericrsmith35** [comment]
This will be fixed in v4.0.12

**Comment by kurtfairfield** [comment]
Thanks Eric :)

**Comment by ericrsmith35** [comment]
This has been resolved in version 4.0.12.  https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/#Installation
