### ISSUE TITLE
*Lightning Input FSC* - _(Value)_ - Value can NOT be a variable or formula, only hard coded

### ISSUE THREAD

**Issue by JodieM** [alexed1/LightningFlowComponents#1223]
### Steps to reproduce

1. Add Lightning Input FSC. 
2. Use Standard Settings as per documentation 

type: "number"
label: "Enter a decimal value"
step: "0.001"

3. Enter Value as 1234.01
4. Run
5. Click Previous
6. No Error. 

Now make only one change. 
3. Enter Value as a Number Variable with the same default value {!vNumber}
4. Run
5. Click Previous
6. Error: Flow encountered an error when processing and converting between data types. Please check the flow and ensure all data types are matched correctly

### Expected behaviour
Coming back to the screen should show the value in the variable again, not an error. 

### Actual behaviour
Error: Flow encountered an error when processing and converting between data types. Please check the flow and ensure all data types are matched correctly

### Screenshots
Here's a video https://www.loom.com/share/6c7772afbc214071b7e3d19f956b6bc8

### Debug Logs
If applicable, please insert debug logs here
<details>
<summary>Debug Log Information</summary>

```
55.0 APEX_CODE,FINEST;APEX_PROFILING,FINEST;CALLOUT,FINEST;DB,FINEST;NBA,INFO;SYSTEM,FINE;VALIDATION,INFO;VISUALFORCE,FINER;WAVE,FINEST;WORKFLOW,FINER
19:53:58.0 (177136)|USER_INFO|[EXTERNAL]|0056F000006aVRm|redacted|(GMT+10:00) Australian Eastern Standard Time (Australia/Sydney)|GMT+10:00
19:53:58.0 (45603121)|FLOW_VALUE_ASSIGNMENT|91204136eb267acb16bc71ebf0e618354e8496a-7e1e|error.errorId|358475656-319734 (-196161961)
19:53:58.0 (45664258)|FLOW_VALUE_ASSIGNMENT|91204136eb267acb16bc71ebf0e618354e8496a-7e1e|error.type|FLOW_INTERVIEW_HANDLED_ERROR
19:53:58.0 (45677191)|FLOW_VALUE_ASSIGNMENT|91204136eb267acb16bc71ebf0e618354e8496a-7e1e|error.message|Flow encountered an error when processing and converting between data types. Please check the flow and ensure all data types are matched correctly.
19:53:58.0 (423326848)|FLOW_ELEMENT_ERROR|Flow encountered an error when processing and converting between data types. Please check the flow and ensure all data types are matched correctly.|FlowScreen|scrInput
19:53:58.426 (426808675)|CUMULATIVE_PROFILING_BEGIN
19:53:58.426 (426808675)|CUMULATIVE_PROFILING|No profiling information for SOQL operations
19:53:58.426 (426808675)|CUMULATIVE_PROFILING|No profiling information for SOSL operations
19:53:58.426 (426808675)|CUMULATIVE_PROFILING|No profiling information for DML operations
19:53:58.426 (426808675)|CUMULATIVE_PROFILING|No profiling information for method invocations
19:53:58.426 (426808675)|CUMULATIVE_PROFILING_END
```
</details>

**Comment by AndyHaas** [comment]
@JodieM 
I will take a look at it this week.

**Comment by AndyHaas** [comment]
@JodieM 
Sorry for this taking so long work just got ahold of me. But I have created a PR to resolve this issue. This is also a two-fold issue in which the variable you must use must be of type String, as that is what the component is looking for. 

If you want to fix this in your org, you can open the component and remove the default=' ' on the value attribute. 

It was hard to figure out the issue, but it was an easy solution.

**Comment by alexed1** [comment]
new version 1.0 package at https://unofficialsf.com/lightninginput/
