### ISSUE TITLE
*SendViaMarketingCloud* - _(SendEmailViaMC)_ -  Allow a messageKey to be specified as input in the action

### ISSUE THREAD

**Issue by lemerv** [alexed1/LightningFlowComponents#1237]
The messageKey attribute is very useful for transactional sends. Details are here: https://developer.salesforce.com/docs/marketing/marketing-cloud/guide/sendMessageSingleRecipient.html

**Is your feature request related to a problem? Please describe.**
Yes, documented here: https://github.com/alexed1/LightningFlowComponents/issues/1236

**Describe the solution you'd like**
What would be a great improvement to the SendEmailViaMC action is to have another input field for specifying a messageKey. This be what gets appended to the end of the callout url. For example:

Input value for messageKey = 1234

Final callout url to the transactional api = https://mcxxxxxxxxxxxxxxxxxxxxxxx.rest.marketingcloudapis.com/messaging/v1/email/messages/1234

**Describe alternatives you've considered**
This action does already create a messageKey (looks to be a timestamp), but this is not available as an output from the action, so is not really useful.

**Additional context**

**Comment by alexed1** [comment]
ok, new version 1.1 fixes the behavior of both messageKey and contactKey, and messageKey is now an optional input. Let me know if you get a chance to try it.  https://unofficialsf.com/using-flow-with-salesforce-cdp-marketing-cloud-messaging/

**Comment by lemerv** [comment]
Thanks Alex, this is working well.

Only other thing that I neglected to mention is to include the messageKey as an attribute in the json payload so that it gets saved to a corresponding field in the data extension in marketing cloud. This is very useful to be able run queries in MC and join various tables on messageKey.

_Note that if we include messageKey in the attributes and there is no field in the DE called messageKey, the message will still send without issue. So I don't think there is a problem with doing this._

Working example below with "myMessageKey" on the end of the callout url and also an attribute in the payload:

```
https://mcxxxxxxxxxxxxxxxxxxxxxxx.rest.marketingcloudapis.com/messaging/v1/email/messages/{{myMessageKey}}

{
  "definitionKey": "test_txn_v1",
  "recipient":
  {
  "to": "ben@gravitylab.nz",
  "contactKey": "0033C00000aJlA0QAK",
  "attributes": {
    "MessageKey": "{{myMessageKey}}",
    "FirstName": "Ben"
    }
  }
}
```
