### ISSUE TITLE
URGENT -- How do we create extra child fields e.g more checkboxes than 4 

### ISSUE THREAD

**Issue by anjlidaryani** [alexed1/LightningFlowComponents#124]
Hi,

By default for each parent question, I can only display 4 child checkboxes. I have a use case where I have to display around 15 child checkboxes. I tried editing the dynamicQuestionFSC component and adding checkboxes after 4 like below but when I went back to flow, I still see only 4 checkboxes.

         <aura:attribute name="childCheckbox5_conditionalRelationship" type="String" default="false"/>
         <aura:attribute name="childCheckbox5_nowVisible" type="Boolean" default="false"/>
        <aura:attribute name="childCheckbox5_storage" type="Boolean" default="false"/>
        <aura:attribute name="childCheckbox5_label" type="String" default="Needs a label assigned via a 
         flow input"/>
        <aura:attribute name="childCheckbox5_controlType" type="String" default="checkbox" />
       <aura:attribute name="childCheckbox5_defaultValue" type="Boolean" default="checkbox" />
        
      <aura:attribute name="childCheckbox6_conditionalRelationship" type="String" default="false"/>
      <aura:attribute name="childCheckbox6_nowVisible" type="Boolean" default="false"/>
      <aura:attribute name="childCheckbox6_storage" type="Boolean" default="false"/>
      <aura:attribute name="childCheckbox6_label" type="String" default="Needs a label assigned via a 
        flow input"/>
      <aura:attribute name="childCheckbox6_controlType" type="String" default="checkbox" />
      <aura:attribute name="childCheckbox6_defaultValue" type="Boolean" default="checkbox" />

Please advise. Thanks

**Comment by anjlidaryani** [comment]
Really looking for an answer. I am reluctant to write a separate lightning component just for 2 parent questions :(

**Comment by alexed1** [comment]
Did you also add the new checkboxes in the design file? You need to add them in both places. This allows you to control which attributes actually are visible in Flow.

**Comment by anjlidaryani** [comment]
Yes I added in multiple different classes and it seems to work fine now. Thanks.
