### ISSUE TITLE
QuickLookup - Conditional visiblility not updating to reflect chosen values

### ISSUE THREAD

**Issue by HafstadErik** [alexed1/LightningFlowComponents#1243]
When Using the QuickLookup component other components on the same screen with conditional visibility depending on the output of the QuickLookup component (O1_Output Value) does not show correctly. 

Add the QuickLookup component to a screen
Add display text standard component to screen with conditional visibility (Quicklookup O1_Output Value = some value) 
verify that Conditional visibility does not show the display text as expected

**Comment by ericrsmith35** [comment]
Make sure you are setting the O1_Output Value in the Output section, not the Input section.

**Comment by AndyHaas** [comment]
I have tested this, and if you are using a Parent/Child, the visibility will not show as the screen doesn't refresh to calculate the variable you assigned to the parent. But if you are not using it as a Parent/Child, then you can use the {lookupAccount.OutputValue} != null and the component will display based on the value.

**Comment by HafstadErik** [comment]
Thanks for the feedback :)


ons. 19. okt. 2022 kl. 14:39 skrev Andy H ***@***.***>:

**Comment by AndyHaas** [comment]
@HafstadErik 
If the feedback is optimal and resolves this issue, please close this issue. 

Thanks 
Andy
