### ISSUE TITLE
sendBetterEmail - Single Email - CC Collection no longer works

### ISSUE THREAD

**Issue by jdpond** [alexed1/LightningFlowComponents#1253]
sendBetterEmail will not send multiple email addresses to CC either as string or as collection of strings in current release

Probably all collection variables are failing, but definitely CC

From User on #OhanaSlack

What are we doing wrong? I've tried everything I can think of.
We're trying to send an email using Send Better Email. We've got a text field on Case that allows users to enter email addresses separated by ; . We want to use the values in this field as the CC recipients of the email triggered.
We've tried:

1. Setting it as a typed string
2. Assigning the field value to a collection variable
3. Using the Convert Strings to Collections variable - every time we specify the delimiter (;), it removes the ; and replaces with ,
4. Using SUBSTITUTE to swap the ; for , and then try to use the same above action with the  same ; delimiter
5. Other things I'm probably forgetting

I know we're not running the most recent version of collection actions, so I'm not sure if it's a bug or there's something we've just overlooked. (Convert Strings is current) 

### Steps to reproduce

1. Create a String Collection of Valid Email Addresses
2. Assign that collection to CC in CPE
3. Execute

### Expected behaviour
Works fine in previous releases

### Actual behaviour
Haven't checked to see if related to all email address variables

### Debug Logs
If applicable, please insert debug logs here
<details>
<summary>Debug Log Information</summary>

From Error:

SENDBETTEREMAIL (APEX): 1. Simplest Better Email
Inputs:
cb_UseSalesforceSignature = CB_FALSE
HTMLbody = {!x1_HTML_Body} (<p>This is some <span style="color: rgb(41, 25, 215);">body text </span>created using the rich text editor in the <b>Text Template</b> resource in <u style="font-size: 22px;">Flow</u>.</p>)
replyEmailAddress = {!testReturnAddress} ([DoNotReply@example.com.invalid](mailto:DoNotReply@example.com.invalid))
SendCCthisOneEmailAddress = null
SendCCthisStringCollectionOfEmailAddresses = {!ccCollection} ([test1@example.com,test2@example.com])
senderDisplayName = {!testSenderName} (DoNotReply)
SendTOthisOneEmailAddress = {!send_Email_To} ([grunt-banana-checker@example.com](mailtogrunt-banana-checker@example.com))
subject = {!sendSubject} (sendBetterEmail Test: Flow Example 1)
UseSalesforceSignature = false
________________________________________
Error Occurred: An Apex error occurred: SendBetterEmail.InvocableActionException: No Messages were sent. First Error: nullError Code:INVALID_EMAIL_ADDRESS - Email address is invalid:
</details>

**Comment by alexed1** [comment]
Fixed in version 3.1
