### ISSUE TITLE
Improved File Upload - ContentVersionId - Not working! HIGH PRIO! 

### ISSUE THREAD

**Issue by Mille347** [alexed1/LightningFlowComponents#1256]
**Please fix ASAP!** 

When using the File Upload Improved component, no documents are added to the collection of the component anymore, same as well for adding manual values. 

Reproduce:
Debug a flow or use a flow with this component, Content document links will not be created.

![image](https://user-images.githubusercontent.com/117359192/199712157-f6dbf1ac-8f46-4312-9646-85f91cc6a260.png)

![image](https://user-images.githubusercontent.com/117359192/199712066-ac34e400-0356-40b7-bf52-289cd93e37cb.png)

**Comment by mateuszpiechgaf** [comment]
I confirm the same issue here: 
![image](https://user-images.githubusercontent.com/108469488/199718539-fa4f932b-38eb-4a65-9bd6-c81201ac8a67.png)
When I go back to the initial screen and go next again, then the collections are not empty anymore.

**Comment by hollya-torrent** [comment]
I'm seeing the same issue. Outputs are all null until I navigate away from the page and then navigate back.
<img width="319" alt="Screen Shot 2022-11-04 at 12 37 28 PM" src="https://user-images.githubusercontent.com/92382823/200040671-82aef39e-d847-4a16-bd36-09ecd936647a.png">

**Comment by rygramer** [comment]
I'm not entirely sure what caused this problem. Perhaps it has something to do with Lightning Web Security? Regardless, it appears that passing a cloned copy of the array back to Flow (rather than using the original) does the trick.
