### ISSUE TITLE
I6 Filter on which field

### ISSUE THREAD

**Issue by cjwvu** [alexed1/LightningFlowComponents#126]
This field always defaults to AccountId. Is this how it ought to be, as AccountId is not relevant in my case?

**Comment by alexed1** [comment]
Eric, your thoughts?

**Comment by ericrsmith35** [comment]
Object Name defaults to Opportunity, Display Field Name to Name, Value Field Value to Id and Filter Field Name to AccountId.

The defaults are just there as a convenience.  Most users will and should be specifying their own values when they place the component on the page.  Specifying your own values will replace whatever the defaults are.

**Comment by cjwvu** [comment]
What I noticed was, even after removing the value ‘AccountId’ from the field, after saving and opening the screen back, I was seeing the value there again. If that’s just being used there a placeholder text, that shouldn’t be an issue.

 My flow isn’t related with Accounts, so this wasn’t really impacting the flow, however just felt like reporting if it was really a bug.
