### ISSUE TITLE
Flex Cards Header Display Field

### ISSUE THREAD

**Issue by RebbePod** [alexed1/LightningFlowComponents#1269]
**Is your feature request related to a problem? Please describe.**
It's frustrating when using auto named object for that to be the field in the header

**Describe the solution you'd like**
Would be cool to be able to select which field should be displayed in the header

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by jdayment** [comment]
Thanks for the feedback I am exploring this option as well as some other field selections

**Comment by jdayment** [comment]
This was implemented in FlowScreenComponentsBasePack Version 3.3.4
