### ISSUE TITLE
Flex Cards - Add Height Adjustment 

### ISSUE THREAD

**Issue by RebbePod** [alexed1/LightningFlowComponents#1271]
**Is your feature request related to a problem? Please describe.**
Sometimes I want just the header text without any body, sometimes I would like more fields to be displayed but don't need the card any wider, or perhaps I would like just one extra field and don't need it as tall.

**Describe the solution you'd like**
A separate height adjustment setting vs width setting. (Would be cool to have fit to text as an option)

**Comment by RebbePod** [comment]
@jdayment not sure if you missed this, I noticed you assigned yourself the others.
Sorry for the ping and I hope I'm not asking for to much, just things that I saw would be useful to me and hopefully others!

**Comment by jdayment** [comment]
I did still working on getting something's assigned 😉
