### ISSUE TITLE
Flow Button Bar - Default Value Is Not Being Set

### ISSUE THREAD

**Issue by Garywoo** [alexed1/LightningFlowComponents#1280]
### Steps to reproduce

1. Add the Flow Button Bar component to a screen
2. Add two example buttons
3. Set the Action Mode to 'Selection'
4. Set the Default value to one of the two example buttons
5. Set Required to 'Yes'
6. Set Multi-Select to 'No'

### Expected behaviour
When the buttons are displayed in the flow, one of the buttons will be selected by default.

### Actual behaviour
When the buttons are displayed in the flow, none of the buttons are selected by default.

### Screenshots
![image](https://user-images.githubusercontent.com/10392194/204018404-28398956-6975-4003-aed6-f1507791a745.png)

![image](https://user-images.githubusercontent.com/10392194/204018543-b794e943-405d-471d-bd49-fa01b7323f12.png)

### Additional Info
This issue has been reported several times in the comments of the Unofficial SF post for this action from Sept '21: https://unofficialsf.com/flow-button-bar-new-and-improved/#comment-5529207521
@fromsteinsfdc added this feature in Aug '21, so I'm not sure if the feature worked initially, and then broke shortly afterwards following the Winter '22 release?

**Comment by mhousaini** [comment]
I'm also having this issue
