### ISSUE TITLE
Flex Card Error: Error during LWC component connect phase

### ISSUE THREAD

**Issue by emosteve** [alexed1/LightningFlowComponents#1282]
Error during LWC component connect phase: [Unknown public property "name" of element <C-FSC_PICK-ICON>. This is likely a typo on the corresponding attribute "name".]

I did make a new simple screen flow in the same sandbox and the error didn't occur. 

Instance is USA20S.  I initially had the error using v3.7  of the Flowactionsbasepack. upgrading to 3.8 didn't help.
![FlexError](https://user-images.githubusercontent.com/91743290/204387166-24dd7c3d-b5d5-4d13-bfac-0a0f6dee34a1.png)

**Comment by emosteve** [comment]
Update. Closed everything and tried again. It is working now.

**Comment by jdayment** [comment]
Thanks @emosteve let us know if it happens again it's a strange error since there have been no changes to the component throwing the error recently fyi @adwhite75 and @alexed1 this is what I was referring to earlier
