### ISSUE TITLE
Flex Cards Remove The Field Title

### ISSUE THREAD

**Issue by RebbePod** [alexed1/LightningFlowComponents#1284]
**Is your feature request related to a problem? Please describe.**
Sometimes I don't need or want it to show the name of the field. For example when listing opportunities I don't need it to say 'stage', having 'closed' is enough. This also takes up extra space.

**Describe the solution you'd like**
Give the ability to remove field titles (would be even cooler if it can be changed for each field)

**Comment by jdayment** [comment]
This will be included in the next release to choose between "Show field labels" or "Hide Field Labels"

**Comment by RebbePod** [comment]
Thank you very much, any point in making a follow up to have the show name of fields be field specific or not worth the effort?
