### ISSUE TITLE
Flex Cards Custom CSS For Fields

### ISSUE THREAD

**Issue by RebbePod** [alexed1/LightningFlowComponents#1285]
**Is your feature request related to a problem? Please describe.**
The ability to customize the header is great, it just makes the rest of the card look dull in comparison :)

**Describe the solution you'd like**
Add the ability for custom CSS for the body as well

**Comment by jdayment** [comment]
This should be in the next release

**Comment by RebbePod** [comment]
@jdayment Any update on when the next release is?

**Comment by jdayment** [comment]
We have some exciting things in the pipeline but no timeline right now

**Comment by jdayment** [comment]
OOTB field styling from SLDS will be supported in the next release
