### ISSUE TITLE
detect and launch

### ISSUE THREAD

**Issue by exactt** [alexed1/LightningFlowComponents#1289]
the detectAndLaunch component imho has a wrong help text in the detectAndLaunch.design file for "fieldChange": "Id" should not be included. It is set directly in the controller. If you enter Id,MyCustumField__c the flow is not starting because than the field list is not a correct String array.

`doInit: function(component, event, helper) {
        // By Default set the Id field as this is required
        var tempFieldList = ['Id'];`

**Comment by AndyHaas** [comment]
You are exactly correct. I've had a PR to push up to get this fixed. I will get this done this week.

**Comment by AndyHaas** [comment]
@exactt,
Changes are pending. If there is anything else that would make this component better, please let us know.

**Comment by AndyHaas** [comment]
@exactt,
Changes are approved and will be pushed out with the next update. Thanks for bringing this to our attention.
