### ISSUE TITLE
*quickLookup* - "Cannot read properties of undefined (reading 'toLowerCase')" red modal error message

### ISSUE THREAD

**Issue by boooney** [alexed1/LightningFlowComponents#1303]
1. On a screen flow which is on a record page tab
2. Select value on quickLookup flow component
3. See red error modal box with message  "Cannot read properties of undefined (reading 'toLowerCase')"
4. Can close box and continue with the rest of the flow.

![image](https://user-images.githubusercontent.com/11412333/207946418-f89ab195-6521-4996-8f4c-a8c89e2d4343.png)

**Comment by jameskbw** [comment]
Is there any work around for this currently?

**Comment by DonleeMalacad** [comment]
Hi guys,

Is there any work around for this issue? I am experiencing the same issue currently.

**Comment by alexed1** [comment]
Thanks for the fix, ajfmo-cfg!

**Comment by boooney** [comment]
Thank you!  I updated the v1.2 and confirmed that this bug is fixed.

**Comment by boooney** [comment]
fixed
