### ISSUE TITLE
Add a clear licence for this project

### ISSUE THREAD

**Issue by simon-nowak** [alexed1/LightningFlowComponents#1306]
**Is your feature request related to a problem? Please describe.**
This project is really usefull and give lot of help for admins. However I'm not sure about what is the philosophie around using the components. There is no licence attached to this project.
- Can I use a component inside an open source project?
- Can I use a component inside a component I sell ?...

This website is a usefull ressource to understand licence: https://choosealicense.com/no-permission/

**Describe the solution you'd like**
A licence should be choose (maybe MIT?). If not any admin that copy/paste component from here put his company at risk.

**Describe alternatives you've considered**
For certains feature we evaluate the proposed solution and usually produce our own. We cannot take a risk here.

I allowed I can do a PR to add this

**Comment by alexed1** [comment]
There's a license here: https://github.com/alexed1/LightningFlowComponents/blob/master/LICENSE

Do you think we need something different or additional?

**Comment by simon-nowak** [comment]
Sorry didn't seen it. Closing this.
