### ISSUE TITLE
Text Area Plus! - Textbox - Caching in latest release (1.6)

### ISSUE THREAD

**Issue by egwylf** [alexed1/LightningFlowComponents#1307]
### Steps to reproduce

- Our sandbox has a flow which uses TextAreaPlus! multiple times on different screens.  
- The sandbox has version 1.5.1 of the TextAreaPlus installed.
- I deployed the flow to production and upon testing discovered the caching issue was occurring.
- Noticed production had an earlier version of TextAreaPlus installed (can't remember which version, but it was earlier than 1.5.1)
- Successfully upgraded TextAreaPlus in production to version 1.6
- Re-ran flow in production and caching issue still occurred.
- Attempted to downgrade TextAreaPlus in production to version 1.5.1. 
- Even though Salesforce said TextAreaPlus was successfully downgraded, it still said version 1.6.
- Decided to uninstalled version 1.6 and install version 1.5.1 as that's the version that was working in our sandbox.
- TextAreaPlus now working in flow as expected.

**Comment by alexed1** [comment]
@jdayment thoughts on this one?

**Comment by jdayment** [comment]
There is a bug in the logic for the slack markdown handler I have a fix for it should have it later this week.
