### ISSUE TITLE
*FlowScreenComponentsBasePack* - _(fsc_quickChoiceCPE)_ - Flow Screen Config Error

### ISSUE THREAD

**Issue by jortegamo** [alexed1/LightningFlowComponents#1317]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### Steps to reproduce

1. Go to any screen flow
2. insert fsc_quickChoice component
3. Configuration component throws an error

### Expected behaviour
you should be able to choose Picklist type value without any error

### Actual behaviour
When you choose Picklist type value an error thrown: 'available-field-types' property does not exist into c-fsc_pick-object-and-field-3 component.

### Possible resolution
fsc_quickChoiceCPE component. In line 49: 

`<c-fsc_pick-object-and-field-3 field-label={inputValues.fieldName.label}
                        object-label={inputValues.objectName.label} object-type={inputValues.objectName.value}
                        field={inputValues.fieldName.value} onfieldselected={handlePickObjectAndFieldValueChange}
                        available-field-types={settings.availableFieldTypesPicklist}></c-fsc_pick-object-and-field-3>`

use the atribute DataTypeFilter instead of available-field-types. 

### Debug Logs
If applicable, please insert debug logs here
<details>
<summary>Debug Log Information</summary>

```
Paste the output of the logs here.
```
</details>

**Comment by AndyHaas** [comment]
@jortegamo I have made the necessary changes within the components and made a PR#1318

**Comment by AndyHaas** [comment]
@jortegamo please use the latest FlowScreenComponentsBasePack which has the fix for this.

**Comment by alexed1** [comment]
sounds like this one is fixed, so closing.
