### ISSUE TITLE
Lookup Choice Removed after Field Validation error in Flow

### ISSUE THREAD

**Issue by rickzaragoza** [alexed1/LightningFlowComponents#138]
Hi thanks for the lookup component it's amazing! I use it in VisualFlow, the problem is when users forget to fill out a required field and click the submit button, the page refreshes, displays the field validation error message e.g. _Please enter some valid input. Input is not optional._ **and** removes the user's lookup choices. They use the flow for every customer interaction and it has four lookups on the page so this is problematic. I've done all I can to make the flow as error proof (default values etc.)  as possible but they still manage to forget something and this limitation is a big deal breaker for them. Any help or suggestions would be greatly appreciated. Thank you Rick

**Comment by ericrsmith35** [comment]
It's not an ideal solution, but how about if you do the validation checks programatically in the flow after you do the lookups and before you update the records?  Provide your own error message and go to a new screen with just the invalid lookup on it or go to the same screen as before but set default values for the valid fields to what the user entered the first time.

**Comment by rickzaragoza** [comment]
Thanks Eric! I tried something like that before but was going about it the wrong way so your suggestion helped. So yeah, unchecking the required field check boxes, adding a default value which is the output value variable and checking the errors programmatically works. The only thing lol, is then the lookup displays the Id instead of the I2_Display Which Field? which in this case is a custom field. 
A minor annoyance. Is there anyway we can output more than one value from the lookup like the Id and Name or some other custom string field? I really appreciate you getting back to me it really helped. Cheers.


Rick Zaragoza
917-202-2869

**Comment by ericrsmith35** [comment]
You can set your default value to the display field value of the selected record.  It doesn't have to be the ID.  For another record selection option, take a look at how I do it with a datatable.

[https://ericsplayground.wordpress.com/2019/03/11/enhance-your-flows-with-data-tables-part-1/](https://ericsplayground.wordpress.com/2019/03/11/enhance-your-flows-with-data-tables-part-1/)

**Comment by rickzaragoza** [comment]
Thanks! I was hoping to do both with the lookup component e.g. assign the name and Id to two variables and a datatable wouldn’t really work in this scenario they are searching and adding up to 4 topics in separate lookup components by name. However, I’m grateful for the workarounds you offered and will definitely be using the datatable component for other things.





Cheers!


Rick Zaragoza

917-202-2869
