### ISSUE TITLE
Shouldn't this be an equality check instead of an assignment?

### ISSUE THREAD

**Issue by cpfrommer** [alexed1/LightningFlowComponents#1393]
https://github.com/alexed1/LightningFlowComponents/blob/5c8cc576fa41ac249eca6489f4240740de4ed3bf/flow_screen_components/textAreaPlus/force-app/main/default/lwc/textAreaPlus/textAreaPlus.js#L461

**Comment by alexed1** [comment]
@jdayment thoughts?

**Comment by jdayment** [comment]
Good catch I have a pending PR for some enhancements let me test this tomorrow to make sure it doesn't uncover any other bugs and I'll adjust accordingly

**Comment by jdayment** [comment]
Changes included in the the latest PR
