### ISSUE TITLE
FlowUploadImproved - Summer '23 Issue Uploading for Guest User

### ISSUE THREAD

**Issue by sfscgjohnson** [alexed1/LightningFlowComponents#1403]
1. Go to flow with fileuploadimproved component on Summer '23 instance
2. Click on Upload
3. Select File and click upload
4. See error: 168 KB
filesname.jpg upload progress is 0%
Can't upload filename.jpg.

### Expected behaviour
File should be uploaded

### Actual behaviour
Get Error Message seen above this is after Summer '23 was added to the org.

**Comment by sfscgjohnson** [comment]
I see that it is trying to go here:
https://mysiteaddress.com/chatter/handlers/file/body

Request Method: POST
Status Code: 400 
Remote Address: 
Referrer Policy: origin-when-cross-origin

**Comment by sfscgjohnson** [comment]
Debug Log:
8.0 APEX_CODE,FINEST;APEX_PROFILING,INFO;CALLOUT,INFO;DB,INFO;NBA,INFO;SYSTEM,DEBUG;VALIDATION,INFO;VISUALFORCE,INFO;WAVE,INFO;WORKFLOW,INFO
18:16:25.0 (209682)|USER_INFO|[EXTERNAL]|0053h000006e56U|home_support_us@irobot2.force.com.uat|(GMT+00:00) Greenwich Mean Time (GMT)|GMTZ
18:16:25.0 (260537)|EXECUTION_STARTED
18:16:25.0 (264518)|CODE_UNIT_STARTED|[EXTERNAL]|apex://FileUploadImprovedHelper/ACTION$deleteContentDoc
18:16:25.0 (1220193)|CODE_UNIT_STARTED|[EXTERNAL]|01pDi000001G7qI|FileUploadImprovedHelper.deleteContentDoc(String)
18:16:25.0 (1430587)|HEAP_ALLOCATE|[79]|Bytes:3
18:16:25.0 (1510312)|HEAP_ALLOCATE|[84]|Bytes:152
18:16:25.0 (1526582)|HEAP_ALLOCATE|[399]|Bytes:408
18:16:25.0 (1539578)|HEAP_ALLOCATE|[412]|Bytes:408
18:16:25.0 (1550641)|HEAP_ALLOCATE|[520]|Bytes:48
18:16:25.0 (1574032)|HEAP_ALLOCATE|[139]|Bytes:6
18:16:25.0 (1621308)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:14
18:16:25.0 (1625427)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:32
18:16:25.0 (1634849)|METHOD_ENTRY|[1]|01pDi000001G7qI|FileUploadImprovedHelper.FileUploadImprovedHelper()
18:16:25.0 (1639247)|STATEMENT_EXECUTE|[1]
18:16:25.0 (1643300)|STATEMENT_EXECUTE|[1]
18:16:25.0 (1672082)|HEAP_ALLOCATE|[52]|Bytes:5
18:16:25.0 (1692678)|HEAP_ALLOCATE|[58]|Bytes:5
18:16:25.0 (1699451)|HEAP_ALLOCATE|[66]|Bytes:7
18:16:25.0 (1712906)|SYSTEM_MODE_ENTER|true
18:16:25.0 (1725300)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:5
18:16:25.0 (1728886)|STATEMENT_EXECUTE|[131]
18:16:25.0 (1730988)|STATEMENT_EXECUTE|[198]
18:16:25.0 (1736351)|SYSTEM_MODE_EXIT|true
18:16:25.0 (1748263)|METHOD_EXIT|[1]|FileUploadImprovedHelper
18:16:25.0 (1753823)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:18
18:16:25.0 (1760411)|VARIABLE_SCOPE_BEGIN|[107]|versId|String|false|false
18:16:25.0 (1803796)|VARIABLE_ASSIGNMENT|[107]|versId|"068Di000001yX4fIAE"
18:16:25.0 (1818811)|SYSTEM_MODE_ENTER|true
18:16:25.0 (1823503)|HEAP_ALLOCATE|[108]|Bytes:5
18:16:25.0 (1827353)|STATEMENT_EXECUTE|[107]
18:16:25.0 (1829197)|STATEMENT_EXECUTE|[108]
18:16:25.0 (1831777)|HEAP_ALLOCATE|[108]|Bytes:72
18:16:25.0 (1850376)|HEAP_ALLOCATE|[108]|Bytes:4
18:16:25.0 (1861166)|HEAP_ALLOCATE|[108]|Bytes:7
18:16:25.0 (2733668)|SOQL_EXECUTE_BEGIN|[108]|Aggregations:0|SELECT ContentDocumentId FROM ContentVersion WHERE Id = :tmpVar1 LIMIT 1
18:16:25.0 (7860492)|SOQL_EXECUTE_END|[108]|Rows:0
18:16:25.0 (7893543)|HEAP_ALLOCATE|[108]|Bytes:4
18:16:25.0 (7919703)|HEAP_ALLOCATE|[108]|Bytes:0
18:16:25.0 (8027637)|HEAP_ALLOCATE|[108]|Bytes:4
18:16:25.0 (8046076)|HEAP_ALLOCATE|[108]|Bytes:40
18:16:25.0 (8148992)|HEAP_ALLOCATE|[108]|Bytes:46
18:16:25.0 (8170181)|SYSTEM_MODE_EXIT|true
18:16:25.0 (8660109)|FATAL_ERROR|System.QueryException: List has no rows for assignment to SObject

Class.FileUploadImprovedHelper.deleteContentDoc: line 108, column 1
18:16:25.0 (8674913)|FATAL_ERROR|System.QueryException: List has no rows for assignment to SObject

Class.FileUploadImprovedHelper.deleteContentDoc: line 108, column 1
18:16:25.8 (8686239)|CUMULATIVE_LIMIT_USAGE
18:16:25.8 (8686239)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 1 out of 100
  Number of query rows: 0 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 0 out of 150
  Number of Publish Immediate DML: 0 out of 150
  Number of DML rows: 0 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

18:16:25.8 (8686239)|CUMULATIVE_LIMIT_USAGE_END

18:16:25.0 (8730622)|CODE_UNIT_FINISHED|FileUploadImprovedHelper.deleteContentDoc(String)
18:16:25.0 (8930928)|CODE_UNIT_FINISHED|apex://FileUploadImprovedHelper/ACTION$deleteContentDoc
18:16:25.0 (8938914)|EXECUTION_FINISHED

**Comment by jdayment** [comment]
I tried duplicating this and am not able to are you still getting this error @sfscgjohnson?

**Comment by sfscgjohnson** [comment]
I am no longer getting it because Security determined that uploading files for guest users without tying them to a contact record was a security violation (this isn't a community).  So we removed the ability from Guests to upload.

**Comment by inbasys** [comment]
I am using the FileUpload component in Lightning ScreenFlow for Portal users to upload the document. The issue that I am seeing is the file preview is not working. This is a big issue for me as the user is looking for this feature. Can I get some patch code for this?

**Comment by jdayment** [comment]
InterviewGuid is only used as a form of data-id to help with some of the cacheing that occurs the error seems to be related with guest user permissions and possibly the site security settings. Sorry I am not much help on this one as I am not able to duplicate it on a few sites both on Summer 23 and Winter 24

**Comment by rutgergernandt** [comment]
@jdayment thanks for looking into it. From Googling the message error it seems to related with the session id, some suggest proxy settings or invalid cross domain (salesforce.com vs force.com). 

Just checking: did you tried the component in an Aura site? Or in LWC only? I checked the code and I see you use the sessionKey. It seems related to an invalid session key, but I cannot really think of a reason the code would be problematic, other than when Aura and LWC are getting mixed up somewhere?

**Comment by jdayment** [comment]
I am still not able to duplicate any issues outside of perm related.
