### ISSUE TITLE
Text Area Plus - Feature Enhancement

### ISSUE THREAD

**Issue by S-R1** [alexed1/LightningFlowComponents#1415]
Hi - 

I am testing the Text Area Plus package specifically for the character counter functionality. I was wondering if it would be possible to include the "Provide Help" feature, as is currently available in standard Flow functionality. 

We currently use the Help Text feature to guide Users through the needed information for each field, or to redirect users (via a hyperlink embedded in the help text) who may require more immediate assistance.

**Comment by S-R1** [comment]
Thanks Josh! What is the release cadence for Text Area Plus?

**Comment by jdayment** [comment]
I don't have a defined cadence it's kind of when I get free time to get to it. I have one pending release right now so it won't be this next one coming up but will be in the one after that. I have a couple other things I am working on in my pipeline right now so I can't commit to a specific timeframe.

**Comment by S-R1** [comment]
Hi Josh - another item we noticed, and not certain if this is specific to Debug mode or not - when typing in the text area and moving through the flow to another screen, then back - the text is not saved. We need to re-enter the text. I've confirmed that the checkbox is selected (by default) in the Advanced section. Am I missing something?

**Comment by jdayment** [comment]
I've added help text in an upcoming PR for rich text and plain text variations
