### ISSUE TITLE
Stages in files

### ISSUE THREAD

**Issue by ricbeccari** [alexed1/LightningFlowComponents#1417]
Hello, I made a quick search and anyone asked for this, is there a way to know in wich stage is a file being upload?
If there isn't, can it be developed? Or if there is a way with the Improved File Upload, can you tell me how?

I'll wait for response, thanks!

**Comment by jdayment** [comment]
I am not sure I understand your question what do you mean by which stage?

**Comment by ricbeccari** [comment]
I already figure it out how to do it from standard file upload, but, what I mean is if a got a Case, 4 stages in it, and I need to know in wich stage a file was uploaded. Standard way it must be done by flow, you may do a better way with your Improved File Uploaded

**Comment by ricbeccari** [comment]
Thanks for your answer anyway! I appreciate it
