### ISSUE TITLE
Datatable - Record Collection Input - This table currently has no data to display

### ISSUE THREAD

**Issue by jacobatfieldin** [alexed1/LightningFlowComponents#1423]
### Steps to reproduce

1. Create a screen flow and get a collection of records and use that collection to display columns in the datatable component
2. Debug the flow
3. Datable is always showing This table currently has no data to display

### Expected behavior
Display the records in the collection variable

### Actual behavior
Message saying This table currently has no data to display

### Screenshots
Image below shows the error and below that the standard data table component from Salesforce using the same record collection:
![image](https://github.com/alexed1/LightningFlowComponents/assets/98544043/18e10f9c-dbc4-4805-9c9f-5c06f9a8203f)

### Debug Logs
I believe (sorry not a developer) the debug logs show that there is insufficient access to the record type. But I don't have a Record Type for the Case object. I did test this on an object I do have record types and it does work so it seems like the error is when the object has no record type it fails?

![image](https://github.com/alexed1/LightningFlowComponents/assets/98544043/ca77e457-832a-427c-ad72-18558d7d4c11)

**Comment by ericrsmith35** [comment]
Please see if you have the same issue with v4.1.4

**Comment by jacobatfieldin** [comment]
Sorry for the delay, yes v4.1.4 does fix the issue. Closing this out.

Thank you! 🥇
