### ISSUE TITLE
Child Records are not filtered based on the parent lookup field. 

### ISSUE THREAD

**Issue by vinodkumarchokkula** [alexed1/LightningFlowComponents#143]
LookupFSC: Tried the same configuration  described in the Description, the contact lookup shows all the contacts, irrespective of parent in the drop down

Browser Console shows the following log:  hlpGetRecords: I1_Contact I2_Name isI_false isP_false isC_true I6_AccountId I7_undefined M_undefined W_undefined D_undefined

**Comment by ericrsmith35** [comment]
@vinodkumarchokkula In the parent component, enter a value for Component ID.  Then in the child component, enter the same value in Parent ID.  This is a new feature that allows you to have multiple Parent/Child relationships on the same screen.  Each parent gets a unique name and each of its child components references that name.
