### ISSUE TITLE
*SHOW TOAST-FLOW ACTION* - _({!ElementName})_ - After install, show toast flow action is not available for selection

### ISSUE THREAD

**Issue by baobao917** [alexed1/LightningFlowComponents#1430]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### Steps to reproduce

1. Install Show Toast - Flow Action package
2. Go to an auto-launch or record triggered flow.
3. Add element = Action
4. Search for "Toast"
5. No available actions named Toast

### Expected behaviour
ShowToast action should be available to select

### Actual behaviour
TShowToast action is not available to select

### Screenshots
![image](https://github.com/alexed1/LightningFlowComponents/assets/104730171/da1ab6fc-0f96-45f9-afa5-2653453e7387)
![image](https://github.com/alexed1/LightningFlowComponents/assets/104730171/f1e09056-4ab9-463d-b396-5c521bb3d7e8)

### Debug Logs
If applicable, please insert debug logs here
N/A

```
Paste the output of the logs here.
```
</details>

**Comment by ericrsmith35** [comment]
The toast action is only available for screen flows.

**Comment by alexed1** [comment]
Autolaunched flows run wholly on the server, without any browser involvement, so no way to show a toast.
