### ISSUE TITLE
*Collection Processors for Flow* - _(Extract Strings From Collection [USF Collection Processor])_ - Action name not found: null

### ISSUE THREAD

**Issue by RikusFischer** [alexed1/LightningFlowComponents#1437]
### Steps to reproduce

1. Create a screen flow that uses the Extract Strings From Collection [USF Collection Processor]
2. Pass record collection into component and set field to extract
3. Set allowEmptyCollection to TRUE and dedupeValues to TRUE
4. Run the Flow
5. On the first run this error occurs: "Action name not found: null"
6. Running the Flow the second time it works as expected

### Screenshots
![image](https://github.com/alexed1/LightningFlowComponents/assets/130669494/69a47045-e68f-4ba9-b327-8fd763ca9914)
![image](https://github.com/alexed1/LightningFlowComponents/assets/130669494/adcd52d1-afb3-4c72-b481-0af1cc1cedcb)

**Comment by ericrsmith35** [comment]
I've tried to recreate this and I am not seeing any errors.

**Comment by MlleBaeten** [comment]
We are also seeing this error with two actions within the CollectionActionsL package:
- Get First
- Extract Strings From Collection
We see the error intermittently, but then when we run the flow again to recreate the issue, the flow runs as expected.  Can't find any cause for this issue.
Running latest version of CollectionActionsL: 3.1.1.

**Comment by RikusFischer** [comment]
I was able to fix it by recompiling the Apex Classes. I realised this only happened in our Staging and UAT environments and not in the dev environment.

**Comment by jeremywatso** [comment]
We are also experiencing the exact same issue, intermittently, in our of our production orgs with both: 
- Find Records in Collection
- Extract Strings From Collection

Also running latest version of collectionActions 3.2.0

**Comment by ericrsmith35** [comment]
@alexed1 Do you know why this could be happening?

**Comment by BaileyAnn** [comment]
my org started see this error today for Dedupe_Record_Collection (FlowActionCall).
```

You’ve received this email because an error occurred while your "SA-SCR-SF-Sales Agreement SPA .csv BOM Import" flow was running.
Error element Dedupe_Record_Collection (FlowActionCall).
Action name not found: null 
```
![image](https://github.com/alexed1/LightningFlowComponents/assets/13024173/c0db0fe0-473f-4e05-bfcf-e2288fa7c80b)

![image](https://github.com/alexed1/LightningFlowComponents/assets/13024173/b384ce75-dde4-48bc-8a43-235b7652b60c)

**Comment by samphif** [comment]
I'm also experiencing this as well. ive decided to hold on upgrades from 3.1.1 as it seemed to get way worse. thought we were completely clear but the issue rearose after a month

**Comment by ericrsmith35** [comment]
I have case open with Salesforce for this issue.

**Comment by ericrsmith35** [comment]
Salesforce has found and patched this bug in Spring '24 orgs.

**Comment by samphif** [comment]
Awesome great news.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dougepsotic** [comment]
> Salesforce has found and patched this bug in Spring '24 orgs.

@ericrsmith35 I am still seeing the "Action name not found: null" error on ConvertCSVToStringCollection. So not sure this patched solved the issue.

**Comment by karenzelevinsky** [comment]
@ericrsmith35 I am also still seeing this error. The only fix I can find is to recompile apex classes after I get alerted that there was a problem. I think I will also need to stop using the package and do it manually. Very sad.
