### ISSUE TITLE
Datatable Error with Opportunity Product

### ISSUE THREAD

**Issue by mpiquero1111** [alexed1/LightningFlowComponents#1450]
Using datatable in a flow to allow inline editing of newly created Opportunity Products, component gives error "Could not find the field: Quantity on the object Product2". 

The table is showing standard object Opportunity Product (API name OpportunityLineItem) which contains a lookup to Product2, and where Quantity is a field. Some how your component is thinking that i am giving it records of Product2, which I am not.

[apex-07L7X00000K9HegUAF.log](https://github.com/alexed1/LightningFlowComponents/files/12498821/apex-07L7X00000K9HegUAF.log)

![table](https://github.com/alexed1/LightningFlowComponents/assets/28360938/c1395fc2-5a55-4104-beb7-7ad2cc861b20)

**Comment by ericrsmith35** [comment]
How are you populating the records in the vNewOpptyLineItems resource?  If you are creating new records in the flow prior to committing them to the database, then you will need to give each record a "dummy" id before you can make any edits in the Datatable.

Each dummy id should be unique and it must start with the same 3 characters as a regular OpportunityLineitem record (00k).

For example 00k000000000001, 00k000000000002, 00k000000000003, ...

Be sure to delete those id field values before you do a Create Records in your flow.

**Comment by mpiquero1111** [comment]
I think you found my problem. I have used the product ID as the ID for the line item. I am going to use your suggestion and test now. Thank you for the quick reply!

**Comment by mpiquero1111** [comment]
Yup that was it. I caused my own error in trying to be lazy and not create a formula to populate the ID. I appreciate pointing me in the right direction.
