### ISSUE TITLE
QuickChoiceFSC - Screen Entry - Input Mode Visual Card Not Recognized

### ISSUE THREAD

**Issue by NickSauer7** [alexed1/LightningFlowComponents#1489]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### Steps to reproduce

1. Launch Flow with QuickChoice Component and Visual Card Input Mode.  Ensure all String Collections are Valid
2. Error is given:  Something went wrong with the "XXXXXXX" screen component on the "YYYYYYY" flow. Contact your Salesforce admin about this error. QuickChoiceFSC: Need a valid Input Mode value. Didn't get one

### Expected behaviour
Cards Should be Displayed

### Actual behaviour
Cards Not Displayed.  It does not seem that inputMode or quickLabels properties are established in connectedCallback

### Screenshots
![image](https://github.com/alexed1/LightningFlowComponents/assets/47322464/03ad40e4-f766-4e7a-86eb-fbd20feccd49)
![image](https://github.com/alexed1/LightningFlowComponents/assets/47322464/97e5bd24-be36-48ee-96e5-e7d56c947e01)
![image](https://github.com/alexed1/LightningFlowComponents/assets/47322464/1c9398ec-c26d-477d-a387-8e06bb9c12b9)

**Comment by ericrsmith35** [comment]
This will be fixed in v2.42 along with:

- Clear the selected value if the options change on a reactive screen
- Allow "Add a 'None' Choice" option for all valid picklist methods
- Added clarification to an error message that could appear if the component has conditional visibility on a screen that can be revisited.

**Comment by ericrsmith35** [comment]
@NickSauer7 Thanks for the detailed notes on how to reproduce the error and a possible solution.

Keep an eye out for version 3.2.6 or later of the FlowScreenComponentsBasePack

**Comment by NickSauer7** [comment]
Excellent, thanks for the update!

**Comment by NickSauer7** [comment]
Works a charm in v2.42.  Thansk @ericrsmith35 !
