### ISSUE TITLE
New approach to 'default' value: no need to reselect

### ISSUE THREAD

**Issue by Striky2** [alexed1/LightningFlowComponents#149]
Hello, 

Thank you for this outstanding component. 

I was wondering if there was any possibility to have a different kind of "default" value. I mean one that would actually pre-set the actual object value (and not only the field value) to the object ID corresponding to the default value provided?

The usecase would be "editing in loop several objects that contain a lookup FSC to be set" (so the goal is for the UX to be super-quick if nothing has changed on the object and move to the next one), if the user doesn't modify anything, the default object value behind the component is preserved (currently null is passed if nothing is chosen and the field value is set to the default), but the user can also change this default value to something else.

Thank you.

**Comment by alexed1** [comment]
@ericrsmith35  fyi

**Comment by ericrsmith35** [comment]
The type of default value you are looking for is in the component currently.  Provide INPUT values for the following two parameters:

Default Value: (whatever placeholder text you want displayed in the input box)
O1_Output Value: The value to be passed out through the O1_Output Value OUTPUT parameter if no value is selected in the input box

Example:  Looking up an Account, defaulting to the Account Name of "ACME Company".  Assume the RecordId for ACME Company is stored in the flow variable vDefaultId.

**[Input Section]**
API Name: AcctLookup
Component ID: 
**Default Value: ACME Company**
I1_Object Name: Account
I2_Display Which Field? Name
I3_Field Label: Account
I4_Output Which Field as Value? Id
I5_ Parent or Child Lookup? 
I6_Filter on which field? 
I7_Filter Value: 
**O1_Output Value: {!vDefaultId}**

**[Output Section]** 
O1_Output Value: {!vSelectedAccountId} (a text variable)

**Comment by Striky2** [comment]
Thank you so much for this detailed answer. 
Exactly what I was looking for!
