### ISSUE TITLE
Error on load of the Lookup screen

### ISSUE THREAD

**Issue by allisonletts** [alexed1/LightningFlowComponents#15]
I use the lookup FSC as part of a flow that's called from a custom action, so it loads as an overlay. In the background, when I get to the lookup FSC screen, I see this error message pop up as a red toast:
Exception occured:
 invalid ID field: null
 Class.LightningLookupController.getFieldValue: line 113, column 1

**Comment by ericrsmith35** [comment]
@allisonletts What are the input parameters and values you set when you call the component from your flow?

**Comment by allisonletts** [comment]
![image](https://user-images.githubusercontent.com/17914696/39647303-f5150b08-4fa3-11e8-8b48-0bdeff4c42c5.png)
Field Label: to
Display which field: Name
Object Name: npsp__General_Accounting_Unit__c
Output Which Field: Id
Use Pills: {!$GlobalConstant.True}

**_Outputs Tab_**
Output Value: (my variable)

**Comment by ericrsmith35** [comment]
Support for Pills was removed from the component.  Try installing the current version.

**Comment by allisonletts** [comment]
Installed the latest version and we're good.
