### ISSUE TITLE
QuickChoice - v2.42 - Dependent Picklist - Dependent Picklist Error when Default Controlling Value Provided Spring '24

### ISSUE THREAD

**Issue by mhosveolia** [alexed1/LightningFlowComponents#1509]
Since spring 24 the ability to use quick choice for dependant picklists on existing records has stopped working.  It seems that any value put into the controlling picklist value field will cause the controlled picklist to not appear in the flow.  I was on QuickChoice Version #: 2.41 when I noticed the issue and upgraded to QuickChoice Version #: 2.42 to see if it fixed but did not.

### Steps to reproduce

1. Add 2 QuickChoice Components to a Flow with one being a controlling field of the other.  Enter a valid value in the Value field of the controlling field.  In the controlled field enter a Controlling Value for picklist.  I am using a formula field now that uses the controlling field value.
3. Debug Flow.  i am using an existing record as the flow is updating some fields)
4. The controlled field does not appear on the flow.  Tested changing values.
5. If the Value of the Controlling field is left blank the the controlled field appears and values change correctly as the controlling field is changed.

### Expected behaviour
Prior to Spring 24.  I was able to use valid existing values from the record in both the controlled and controlling field.  The controlled field would work as expected when the controlling field was changed.  I did this using variables populated from the record the flow was run on.  

### Actual behaviour
When a value is populated in the controlling field then the controlled field never appears.  When viewed on record screen a component error appears with a message of  [Cannot read properties of undefined (reading 'controllerValues')]
Component Descriptor: markup://c:fsc_quickChoiceFSC
File: /modules/c/fsc_quickChoiceFSC.js
Function: U.setPicklistSelections
Stack Trace: U.setPicklistSelections() ...modules/c/fsc_quickChoiceFSC.js:1:9694
set controllingPicklistValue()   ...modules/c/fsc_quickChoiceFSC.js:1:7146

**Comment by alexed1** [comment]
Do you have the ability to open a case with Salesforce on this? If so, post the Case number here.

**Comment by mhosveolia** [comment]
Here is the Case #46124312

**Comment by ericrsmith35** [comment]
I have a workaround posted.  Please see the latest version of the FlowScreenComponentsBasePack. 3.3.2 https://unofficialsf.com/flow-action-and-screen-component-basepacks/

**Comment by mhosveolia** [comment]
Thank You Eric!  I can confirm it is working again.
