### ISSUE TITLE
Datatable - inline editing

### ISSUE THREAD

**Issue by Jaedenkaal** [alexed1/LightningFlowComponents#151]
Is it possible to make inline editing work for a datatable in a flow? I can't seem to get the onsave action to trigger or actually do anything. Is this just not possible in a flow at this time?

**Comment by ericrsmith35** [comment]
@Jaedenkaal Did you look at the example here?
https://developer.salesforce.com/docs/component-library/bundle/lightning:datatable/example#lightningcomponentdemo:exampleDatatableInlineEdit

You will need an actual Apex class to write your data.

**Comment by ploughran** [comment]
The issue I ran into with this, was that in my Datatable component I used an attribute that was of a specific object type(Runner__c[]). To populate this, I used an SObject Collection Variable of object Runner. In the example above @ericrsmith35, the Inline Edit Datatable uses a generic object and not a salesforce object. Do you have any coaching on how we could build this into a datatable and then write back to the SObject Collection in a flow as opposed to directly to an object with an apex class?

**Comment by Jaedenkaal** [comment]
> @Jaedenkaal Did you look at the example here?
> https://developer.salesforce.com/docs/component-library/bundle/lightning:datatable/example#lightningcomponentdemo:exampleDatatableInlineEdit
> 
> You will need an actual Apex class to write your data.

Hi Eric,

Yes, I've been all through there.
I'm trying to use the data table to create new objects rather than modify existing ones. What I'd like to do is use the inline edit to modify only the array of objects (and their values) passed to the data table by the flow (via a collection variable). Sending the draft data to the objects themselves and re-querying to get a new set isn't going to work for me in this case.

I've actually gotten pretty close, in part using the page you referenced; at this point the save button action works, but just replaces the table data with only the draft ids and values. To work properly it should update the table data with the draft values (keeping everything that hasn't changed). What's the best way to do this?

**Comment by alexed1** [comment]
@ploughran You can use javascript to convert the Object data coming out of the datatable to a javascript array of your particular SObject. Then you can pass that across the Flow/LC border to a Flow SObject Collection.

**Comment by alexed1** [comment]
@Jaedenkaal , what you're trying to do should be workable. The first thing you have to do is use javascript to merge the changes that come to you onSave in the draft object into your list of records. You can do this either by modifying the Object that gets passed to the datatable, or the array of SObjects that is what actually travels between the Flow and the component. 

Keep in mind the data flow:

Collection of SObjects in Flow --> (across boundary into datatableFSC) --->javascript Array of Sobjects  --> javascript Object --> (across boundary into datatable base component) ----> do some inline edits and click save ---> (across boundary into datatable FSC) ---> merge the draft changes into the javascript Object ---> convert the javascript Object to javascript Array of SObjects ---> (return across boundary into Flow collection)

Whatever you guys pull off here, please write a blog post for UnofficialSF!

**Comment by ChewinChaz** [comment]
@Jaedenkaal Did you ever solve this?  I am trying to do something similar but am fairly new to salesforce development.

**Comment by ericrsmith35** [comment]
I haven't had a chance to work through this one yet.

**Comment by ChewinChaz** [comment]
No worries.  I didn't see a blog post from @Jaedenkaal so I was just curious if he had figured out how to inline edit/create.  Love your component btw thank you so much for sharing!  Do you know if it will be possible to set the objects dynamically in a future release?  Some of my users don't have access to all of the objects.

**Comment by ericrsmith35** [comment]
There will be the option to dynamically set the SObject in the next release
or two

In the meantime I plan on creating a single object version that admins will
be able to edit to set the object. Stay tuned.
