### ISSUE TITLE
Allow href to be returned and displayed from APEX-Defined Data Type in the data table

### ISSUE THREAD

**Issue by stephenpstanley** [alexed1/LightningFlowComponents#1514]
I'm using an APEX-Defined Data Type which includes record IDs and displaying them in a data table but I can't create a nice-looking clickable link displaying a Name field as would be possible if the data table was based on an sObject. I can return a URL and specify that the field/column is a URL, but then it displays as /001xxxxxxxxxxxxxxx instead if the Account Name as an example of the lookup is to an Account record

**Describe the solution you'd like**
To be able to display a Name rather than the URL and when the user clicks on it for the UI to navbigate to the record represented by the URL

**Describe alternatives you've considered**
I've returned a text string in an href format (<a href="/001xxxxxxxxxxxxxxx">Account Name</a>). 
- When formatted as text in the component builder, this displays as <a href="/001xxxxxxxxxxxxxxx">Account Name</a> in the table and is not clickable
- When formatted as a URL in the component builder, it displays as https://<a href="/001xxxxxxxxxxxxxxx">Account Name</a> and is not valid
- When formatted as a URL in the component builder and you return a relative URL, the link works, but it's just ugly

I've looked at the source code and the way that the name and lookup field resolving works is to use a getDescribe() (around line 420 in your ers_DatatableController.cls) to work out the related object, but APEX-defined data types don't support the concept of related objects so I can't use that approach

I've tried various Special Type Attributes and Special Other Attributes, to make the href be interpreted as html so it displays as it would be by a browser receiving an href but either there is no existing directive or I've not lucked on the right one yet.  The documentation of this aspect of the component seems very sparse

**Additional context**
href configured as text in the component
![image](https://github.com/alexed1/LightningFlowComponents/assets/25858472/88d6c6b3-6533-4e4b-99a3-cde1198025be)

href configured as a url in the component
![image](https://github.com/alexed1/LightningFlowComponents/assets/25858472/587af1c0-1779-4bd2-9c5a-cf2cef65e25d)

(horribly) ugly relative url returned and configured as a URL in the component
![image](https://github.com/alexed1/LightningFlowComponents/assets/25858472/3d84c5ba-afa2-4ce8-bc29-336c42e74ee8)

**Comment by ericrsmith35** [comment]
You can create clickable links in Apex Defined Datatables.  Please see the following example:

Data
[{"Site":"Google","url":"https://www.google.com"},{"Site":"Salesforce","url":"https://www.salesforce.com"}]

Column Fields
url

Column Labels
1:Site

Column Types
1:url

Special Type Attributes
1:{label:{fieldName:Site}, target:"_blank"}

Key Field
url

![image](https://github.com/alexed1/LightningFlowComponents/assets/24724447/a277d00b-231a-4528-9249-d58bbbf5c568)

**Comment by stephenpstanley** [comment]
Thank you - that’s a combination I didn’t think of. I’ll give it a try
