### ISSUE TITLE
*DataTable* - _DataSource_ - New Education Cloud objects not visible

### ISSUE THREAD

**Issue by gctattainpartners** [alexed1/LightningFlowComponents#1526]
*Requires org with the new Education Cloud*

Add component to a screen flow.
In the Data Source look for an object from Education Cloud (Academic Term, Individual Application, Learner, Learning, Contact  Contact Relationship, Account Account Relationship, etc) 
See that they are missing
Check the "Display ALL objects for selection box"
Verify that the objects still aren't available for selection.

Expected behaviour
Objects included in the new Education Cloud as standard would be available. (I have a full license and access to the objects in question)

Actual behaviour
Expected objects aren't available for selection

Screenshot
{This is with ALL objects checked}
Notice that the first object is "Accepted Event Relation" which is alphabetically after "Academic Term". Also "Account Account Relationship" is missing.
![Datatable Data Source Missing Ed Cloud Objects](https://github.com/alexed1/LightningFlowComponents/assets/97310291/bbc0ea06-cc9e-47d2-a9e4-41861580316a)

**Comment by ericrsmith35** [comment]
The v3.17 of the FlowActionsBasePack should now support object selection in CPEs up through API 59.0.
