### ISSUE TITLE
*Datatable 4.2* - Dependent Picklist Fields

### ISSUE THREAD

**Issue by pcarass** [alexed1/LightningFlowComponents#1536]
Hi @ericrsmith35 
Can you confirm if Dependent Picklist fields are still not currently supported in the latest version (4.2) of Datatable?
Thanks,
Paul

**Comment by ericrsmith35** [comment]
No support yet.

**Comment by pcarass** [comment]
Thanks @ericrsmith35 
Just checking for clarification, in case I missed a step in my configuration.
Thanks as always for all your hard work with this and everything else you're doing.
Regards,
Paul
