### ISSUE TITLE
Long text area show enters in datatable

### ISSUE THREAD

**Issue by Juul1** [alexed1/LightningFlowComponents#1537]
**Is your feature request related to a problem? Please describe.**

The issue is that my enters are not shown in the datatable when using a long text area.

**Describe the solution you'd like**

I want to see enters in the long text area, now everything is shown after each other.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by Juul1** [comment]
Adding <br> is working. But the <br> tag is also visible on the standard record ;)

**Comment by ericrsmith35** [comment]
For Long Text Area, try BR() instead of <br>.  Have you tried Rich Text instead of Long Text Area?

**Comment by Juul1** [comment]
Ok thanks!!
