### ISSUE TITLE
*Datatable* - _(Apex-Defined)_ - Apex Defined cells can't be edited? 

### ISSUE THREAD

**Issue by fprovot** [alexed1/LightningFlowComponents#1558]
### Steps to reproduce

- Add Datatable component displaying Apex-Defined records.
- Allow edition on fields.
- Run the flow 
- Update one cell 
- Save : the cell should keep its value but don't. Also trying the property of the datable outputEditedRowsString is null.

### Expected behaviour
The cell update must be kept in the table and usable afterward.

### Actual behaviour
Tell us what happens instead

### Debug Logs
Flow debug details : 
After the update, I try to display the datatable (named Selected_Items) changes on another datatable (just for debug): 

  *Lightning Component:* screen_final_datatable_values
  Screen component: c:datatable
  Inputs:
  cb_isUserDefinedObject = (CB_TRUE)
  columnFields = (id,name,price,z0type)
  isUserDefinedObject = (true)
  tableDataString = Selected_Items.outputEditedRowsString (null)
  Outputs:
  null

</details>

**Comment by ericrsmith35** [comment]
Please see if this issue is still there with v4.3.0 of the datatable

**Comment by fprovot** [comment]
Hello
Now updates on the table are kept in the display after clicking on 'Save'
Thanks
