### ISSUE TITLE
Datatable - Pagination - Retain selections after page change

### ISSUE THREAD

**Issue by fprovot** [alexed1/LightningFlowComponents#1559]
**Is your feature request related to a problem? Please describe.**
Using a datatable with pagination, selected rows are not retained when we change the page.

**Describe the solution you'd like**
Be able to select rows on any page of the pagination without loosing selection of the previous page.

**Describe alternatives you've considered**
I don't see how to manage that.

**Comment by ericrsmith35** [comment]
This issue has been addressed in the latest (v4.3.0) release.
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/

**Comment by fprovot** [comment]
This works fantastically in 4.3! thanks.
