### ISSUE TITLE
Where does css lives for this lightning bundle

### ISSUE THREAD

**Issue by anjlidaryani** [alexed1/LightningFlowComponents#156]
Hi,

I need to change the styling for few elements. Please let me know where the css lies, so that I could make changes.

Thanks

**Comment by alexed1** [comment]
You can add a Style file to a lightning bundle. Most of the components here don't have one, but you can provide it yourself. https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/components_css.htm

You can also apply styles more directly by using the style property of most html tags. If you do it that way you can pass information into the component dynamically. For example, you could have a color picker on screen 1 of your flow and you could pass the selected color into your component, and then use the color to style a tag. 

If you get a chance to experiment with it, let us know how it went!
