### ISSUE TITLE
I6 Filter on which field

### ISSUE THREAD

**Issue by cchrisv** [alexed1/LightningFlowComponents#158]
Right now I am trying to Display = Name, Output = Id and Filter SearchKey__c on a custom object. However, I6 Filter on which field appears to not be working for me. It continued to filter on Name.

**Comment by ericrsmith35** [comment]
Are you also specifying an I7_Filter Value?

**Comment by cchrisv** [comment]
No, that looks like it needs to be a pre-defined value. I was hoping the user could type in the lookup box which would search for the record.

**Comment by ericrsmith35** [comment]
If you don't want to restrict the potential values in the lookup box, leave both I6 & I7 blank.  Typing text into the lookup box will then filter by the Display field (Name).

**Comment by cchrisv** [comment]
Got ya, I'm trying to filter by user input against a different field from the one being displayed. I understand why it doesnt work now.
