### ISSUE TITLE
Datatable - Winter 25 Patch 7.1 Breaks Flex Widths

### ISSUE THREAD

**Issue by mirniazkkr** [alexed1/LightningFlowComponents#1589]
1. In a sandbox org with Winter 25 Patch 7.1 (released on Sept 23), navigate to the Configure Columns component
2. Despite any hardcoded column widths, you'll find that the columns headers do not move

Expected Behavoir:
Column width definitions should be respected

Actual Behavoir:
Column width set to 0

![image](https://github.com/user-attachments/assets/10954424-a8ba-4ec5-a0f0-0d94b476149a)

https://help.salesforce.com/s/articleView?id=release-notes.salesforce_release_notes.htm&language=en_US&release=252&type=5
```
lightning-datatable

This behavior has changed.

During inline editing, validation errors appear on the cell itself rather than on the whole datatable.

This attribute has changed.

wrap-table-header—This attribute is now a string instead of a boolean. In addition to clipping or wrapping all table headers, you can now wrap or clip table headers based on the wrap and clip settings for each individual column. Accepted values are all, none, and by-column. The default setting is by-column.
```

Believe the changes that are required are on datatable.js, lines 1546 and 1549 - from boolean to string.

**Comment by ericrsmith35** [comment]
https://unofficialsf.com/datatable-winter-25-update/
