### ISSUE TITLE
Enhancement Request - Lookup Multiple Selections

### ISSUE THREAD

**Issue by Seanman236** [alexed1/LightningFlowComponents#160]
The Lookup FSC is awesome.  One of my users got back to me asking if there's a way to set it up so they can select more than one option.  I've explained we are using something generously made available by folks much more advanced than myself but that I would reach out.

The use case they described is that frequently a small set of records (1-5) all need to be worked with in the same context.  Right now they kick off the flow, look up each record, and go through several screens each time.   Being able to select several options at once and then store them in a collection to then pass downstream in the flow would be very useful.

The easy solution here is to just put multiple look ups on the initial screen and then have the flow add them to a collection which is perfectly fine.  That said, I saw the combobox component does have some sort of multi-select ability (no clue if it is extendable here) so was curious if this was on the roadmap.

Thanks again for providing such powerful tools!

**Comment by ericrsmith35** [comment]
You should take a look at the datatable component for multi-select options.

https://ericsplayground.wordpress.com/2019/03/11/enhance-your-flows-with-data-tables-part-1/


Eric Smith
