### ISSUE TITLE
Datatable - Master Detail Hyperlinks

### ISSUE THREAD

**Issue by JeremyG69** [alexed1/LightningFlowComponents#1609]
For Lookup fields we get the name and link displayed automatically - I would love this to be the same for Master Detail fields as well.

A workaaround is to create a forumal field with a Hyperlink and include that in the datatable

**Comment by ericrsmith35** [comment]
In order for a lookup or master/detail field to display as a link, it must be “reparentable”

**Comment by JeremyG69** [comment]
Ah - OK many thanks
