### ISSUE TITLE
Lookup list incomplete

### ISSUE THREAD

**Issue by mehansen82** [alexed1/LightningFlowComponents#162]
The Lookup list only displays the first (approximate) 100 record results for the user to scroll through. If you need to select any field beyond that, it is REQUIRED that you start typing in the box which activates predictive search. My concern is that for my particular use case (194 records), only options from A-G are displaying and it's not intuitive to my users to start typing in order to find any H-Z records, which will prompt support calls concerned that we've lost approximately 50% of our data in that object when we really haven't. For mouse users this is definitely going to be problematic. Please feel free to contact me directly if you need additional clarification. 

The first image shows the end of the list of records for the Object referenced in the Lookup Component
![End of Object List](https://user-images.githubusercontent.com/48998023/57874917-42913f80-77d7-11e9-968b-0de967d9f17c.png)
The second image shows the end of the Lookup results displayed within the Flow.
![End of Lookup Picklist](https://user-images.githubusercontent.com/48998023/57874921-46bd5d00-77d7-11e9-89f0-e3c1dc4c0e5c.png)

**Comment by ericrsmith35** [comment]
100 records is an arbitrary limit.  You can change or remove the limit from the LightningLookupController Apex Class.
![Capture](https://user-images.githubusercontent.com/24724447/57880851-d241e880-77ed-11e9-94a6-4d3a73d7bbf8.PNG)

**Comment by mehansen82** [comment]
Thanks Eric!

Michelle Hansen
Sales Support Consultant
8801 Prairie View Lane SW, Ste. 100
Cedar Rapids, IA. 52404
(319) 841-8416

On May 16, 2019, at 2:18 PM, Eric Smith <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION: This email originated from outside of NISC or its subsidiaries. Do not click links or open attachments unless you recognize the sender and know the content is safe.


100 records is an arbitrary limit. You can change or remove the limit from the LightningLookupController Apex Class.
[Capture]<https://user-images.githubusercontent.com/24724447/57880851-d241e880-77ed-11e9-94a6-4d3a73d7bbf8.PNG>

**Comment by mehansen82** [comment]
Eric,

I updated that field successfully in sandbox, but when I try to deploy it to production (change set that includes the LightningLookup Class and Test Class) I’m failing with only 68% code coverage. I have absolutely zero idea what I’m doing when it comes to Apex and development and code coverage. Would you have some time to help me out in the near future?

Thanks,

[http://intranet/sig/NISC_50th_logo.jpg]<http://www.nisc.coop/>
Michelle Hansen
Sales Support Consultant
National Information Solutions Cooperative®
8801 Prairie View Lane SW
Ste.100
Cedar Rapids, IA 52404
• e-mail: michelle.hansen@nisc.coop<mailto:michelle.hansen@nisc.coop>
• phone: 866.999.6472 ext 8416
• direct: 319-841-8416
CONFIDENTIALITY NOTICE: This email message, including any attachments, is for the sole use of the
intended recipient(s) and may contain confidential and privileged information. Any unauthorized review,
copying, use, disclosure, or distribution is prohibited. If you are not the intended recipient, please
contact the sender by reply e-mail and destroy all copies of the original message. Thank you.

**Comment by ericrsmith35** [comment]
Are you able to deploy any other Apex classes to Production with a Change
Set?

**Comment by mehansen82** [comment]
I’ve never tried. I have zero experience with development of Apex and certainly have never deployed any outside of a package.

[http://intranet/sig/NISC_50th_logo.jpg]<http://www.nisc.coop/>
Michelle Hansen
Sales Support Consultant
National Information Solutions Cooperative®
8801 Prairie View Lane SW
Ste.100
Cedar Rapids, IA 52404
• e-mail: michelle.hansen@nisc.coop<mailto:michelle.hansen@nisc.coop>
• phone: 866.999.6472 ext 8416
• direct: 319-841-8416
CONFIDENTIALITY NOTICE: This email message, including any attachments, is for the sole use of the
intended recipient(s) and may contain confidential and privileged information. Any unauthorized review,
copying, use, disclosure, or distribution is prohibited. If you are not the intended recipient, please
contact the sender by reply e-mail and destroy all copies of the original message. Thank you.
