### ISSUE TITLE
Lookup FSC Filter Question

### ISSUE THREAD

**Issue by wallyworley** [alexed1/LightningFlowComponents#164]
This is not an issue but a problem that I can't seem to get correct. In lookup i'm trying to return records based on a picklist value in the field directly before the lookup. For example, if the picklist value is Cash (field name {!referraltype}), then I want the lookup to filter values from a custom object where the application__c field equals "Cash" ({!referraltype}). I have tried various combinations of Filter Value and Where Clauses as well as reading the issues in this post without success.

Any help would be greatly appreciated on my part.

Thanks

**Comment by ericrsmith35** [comment]
The value of the picklist field is not available to the Lookup component if
they are on the same flow screen.  If you put your picklist values in a
custom object, you can lookup your value in a Parent Lookup and then have a
Child Lookup on the same screen use that value for its filter.
