### ISSUE TITLE
Dynamic Question support for DATE fields

### ISSUE THREAD

**Issue by shanesayer** [alexed1/LightningFlowComponents#166]
@ericrsmith35 Wondering if there is a way to configure the component to have a date field as a dynamic field?  IF not I'd like to suggest adding that as an option.

Also, is there a way to REQUIRE the child fields?

**Comment by alexed1** [comment]
Hi Shane. We're only a few months away from rolling out official conditional field visibility, so I doubt anyone is going to invest more in Dynamic Question, which we'll probably honorably retire when the official functionality comes out
