### ISSUE TITLE
customFooterFSC: Incorrect action name FINAL - should be FINISH

### ISSUE THREAD

**Issue by p-konakanchi** [alexed1/LightningFlowComponents#172]
In customFooterFSCController.js the action variable should be set to FINISH to end the flow. Currently it is set to FINAL, which is not a valid flow navigation action.

https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/components_config_for_flow_screens_navigate_actions.htm

**Comment by alexed1** [comment]
good spot. fixed.
