### ISSUE TITLE
Selection isn't actually made unless user clicks result, but still satisfies requiredness

### ISSUE THREAD

**Issue by chrispphillips** [alexed1/LightningFlowComponents#175]
When searching for a record that only returns one result, unless the user actually clicks the result value in the list, the component won't use that value.

However, even if the field is marked as required, the user can continue, thinking that they've properly completed the field when they have not.

Would like to see the component either automatically use the value inputted if only one result is returned, or prevent the user from continuing until they actually select a result.

Thanks!

<img width="1263" alt="lookupFSC Issue - 1" src="https://user-images.githubusercontent.com/21038356/61539704-129a2e80-aa0a-11e9-9fe3-fe5bb0b24a9d.png">

<img width="1658" alt="lookupFSC issue - 2" src="https://user-images.githubusercontent.com/21038356/61539717-175ee280-aa0a-11e9-84f1-08cc5a6161a6.png">

**Comment by ericrsmith35** [comment]
Make sure you have updated your code to what is currently on this site.  My last update was earlier this month.  To properly handle a default value you will need to set the following **INPUT** attributes:

- **Default Value:** What you want to appear displayed as the default value in the input box (This must be the same format and type as the field specified in I2_Display Which Field?)
- **O1_Output Value:** The default value to be returned if no selection is made (This must be the same format and type as the field specified in I4_Output Which Field as Value?)

**Comment by chrispphillips** [comment]
@ericrsmith35 Thanks for the quick reply.

I had 2.2 installed so I upgraded to 2.3 but am still having the same problem.

I don't think the issue I'm having though is related to the default value function.

Here is the scenario I'm running into.

The user arrives on the screen with the lookup component with the lookup field input box is blank, as desired. They then type in the value to search on. They see that the system only returns one result and since that value is already in the search box, assume they don't need to click the result (similar to how Salesforce standard Lookups work.)

They then click next thinking they've selected a value when they have not and the screen lets them continue because they've technically filled in the input even though they haven't selected a result. So they are able to continue without actually having specified a value.

Is this the intended design? I was hoping that either the system could utilize the input value if only one result is returned like how standard SF lookups work, or at least prevent them from continuing, forcing them to actually click the result in the dropdown, if the field has been configured to be required.

**Comment by ericrsmith35** [comment]
I think your best bet here is to add a quick Decision element in your flow
after the screen to check for a returned value.

**Comment by chrispphillips** [comment]
Yep that's what I did, just wanted to see if I was doing anything wrong. Regardless, thanks for the plugin. It's been a huge help.

**Comment by solo-1234** [comment]
Hi! Wondering if this still works...

I set it up prefilling Default Value with the record's name, and O1_Output Value with the record's id, but when I load a page with the flow embedded, I get an error toast message that says `Cannot set property 'value' of null`.

I can X the toast message an then the flow works, but it's not going to work for my users... is there something to do to fix that? Otherwise I'll have to skip the default value but that would be a shame.

Thank you!
