### ISSUE TITLE
Custom Object not working in Datatable

### ISSUE THREAD

**Issue by tobiasbossin** [alexed1/LightningFlowComponents#179]
Hi everybody,

I want to use the datatable component because it looks like a charm. WIth standard objects like contacts and accounts it works perfect. But when I want to use  custom objects, it doesn'T show any record.
I adjusted the datatableFSC.cmp and datatableFSC.design and the labels for the custom object then shows up in the component. 
Also other components are showing me the data, like Picklist or Record Choice Sets.
Seems only not to work with custom objects. 

Any ideas or hints or does someone else has the same issue?
Thanks in advance for any help

BG

Tobias

**Comment by ericrsmith35** [comment]
Post a copy of the changes you made to the components and I'll take a look.  It is working fine for many others.

**Comment by ericrsmith35** [comment]
Also, make sure that lines 86-95 are NOT commented out in datatableFSCController.js

**Comment by tobiasbossin** [comment]
Hi Eric, 

thank you very much for your fast response.
This was the one I missde:

> Also, make sure that lines 81-90 and 126-131 are NOT commented out in datatableFSCController.js

Now it works perfect ;)
