### ISSUE TITLE
NavigateToSObject improvement request

### ISSUE THREAD

**Issue by dleland** [alexed1/LightningFlowComponents#180]
Hello - NavigateToSObject works great and I use it a lot.  There is one thing I wish it had - the ability to be either in "view" or "edit" mode when navigating to the object.  Currently, it's always in "view".

Thanks!

**Comment by michaeldawson5** [comment]
Hello - we are using the sales console and when the flow is finished it opens a new tab but not in the subtab that you are working in, it would be great if it opened in the subtab.
