### ISSUE TITLE
Unable to use Where Clause on Lookup

### ISSUE THREAD

**Issue by rissyxlou** [alexed1/LightningFlowComponents#183]
I'm trying to use the lookup component to pull a list of users. 

Here's my Where Clause:
"Title='Regional Account Manager' or Title='Business Development Manager'"

And here are the values I have in my component:
![image](https://user-images.githubusercontent.com/47796706/65264393-17e02c00-dad4-11e9-8735-3db5108084be.png)

**Comment by ericrsmith35** [comment]
Have you tried it with just a single option for the Where clause?  ie without the OR?

**Comment by rissyxlou** [comment]
I just did that. I got this error: 
![image](https://user-images.githubusercontent.com/47796706/65266282-5aa40300-dad8-11e9-8ca9-aa5990f453fa.png)

**Comment by rissyxlou** [comment]
That worked. Thanks!
