### ISSUE TITLE
datatableFSC

### ISSUE THREAD

**Issue by gconarton** [alexed1/LightningFlowComponents#186]
I'm trying to use datatableFSC with the Lead Object as my source.  I have a collection of Leads ({!vCollLeadApplicants}) that fit my parameters.  I have the datableFSC loading them into a list beautifully.  I have a "collection" ({!vSelectedApplication}) variable  to store the selected record (Single or Multi-Row Selection is set to 1).

My problem is the datatableFSC is not passing that selected value into the variable for use elsewhere.  I have tried looping through the selected applicants collection to assign those to a single record variable but that is not working either.

I started out with the changing the code so the LEAD object replaced the Assets object.  Then I thought that may be wrong so I changed that back to ASSETS and changed the first custom object to LEAD (and made changes in all other places).  That is not working either.

**Comment by adwhite75** [comment]
I am seeing the same issue - it looks like this is an issue with Winter 20. I think the developer might need to fix the component to work with the way flow handles Collections now.

**Comment by alexed1** [comment]
Hmm. I'm not aware of any change we made that should cause a lightning component to stop working. @ericrsmith35 let me know what you can diagnose.

**Comment by ericrsmith35** [comment]
I have not been able to reproduce the behavior change you mention in any of my Winter 20 orgs.

gconarton - Are you putting the collection variable for the selected records in the "Store Output Values to Select Variables" attribute section?

**Comment by jeffolmstead** [comment]
I am getting the same issue on Winter 20 - trying to document and if I can resolve will let you know:

Once I complete a form (which loads up fine) and look at the output in debug mode, this is what I see (commented out last name):
![image](https://user-images.githubusercontent.com/1848585/67801793-4ef51600-fa60-11e9-84d6-8ff8fa0fc8ec.png)
It looks like an array of arrays... just wondering if that is a factor. I assumed it would look more like the variable assignment I see here:
![image](https://user-images.githubusercontent.com/1848585/67803220-f5421b00-fa62-11e9-9e93-0fb81f2ac32a.png)
My first time delving as a developer into this though so my knowledge as limited. I will be debugging more later and let you know what I find.

**Comment by ericrsmith35** [comment]
With the new release of Winter ’20, you will need to make sure you select the **“Manually assign variables (advanced)”** checkbox and set your output parameters to variable resources you have created in your flow.

**Comment by jeffolmstead** [comment]
Thank you, that took care of things.

**Comment by seanrmsy** [comment]
@ericrsmith35  Is it enough to set the {Output selected [Object]} to a collection? And if I've got all the values in the section prior to the "Manually assign variables" option, do I need to recreate them in the fields in the section?

**Comment by seanrmsy** [comment]
I'm getting nothing but errors when trying to set these variables Mamnually.

<img width="640" alt="Screen Shot 2019-11-04 at 3 54 58 PM" src="https://user-images.githubusercontent.com/9948230/68161449-86aa0500-ff1b-11e9-9266-af211e20fac6.png">

**Comment by ericrsmith35** [comment]
In the Output section (Manually assign variables (advanced)) you should only be entering a SObject variable for the "Output Selected <objectname>" attribute for the Object you are displaying the datatable for.  All of the other attributes get defined in the input section at the beginning of the component configuration.

If you do provide a value for a "Output Selected <objectname>" attribute in the Input section, the component uses it do display the records in that SObject collection variable as "pre-selected" when displaying the table.

I hope this helps you make progress in using this component.

**Comment by philipmarinovnext** [comment]
Hello,

FoA, thanks for all the labor you've put into this component, it's great.
I found a small issue with the inline editing + preselected lines functions. Basically, any rows that were preselected will not save any of the changes done to them via inline editing. Deselecting and then selecting the row again fixes the issue, regardless if you reselect the row before or after editing it.

**Comment by alexed1** [comment]
go ahead and create an issue in the repo. thanks!

Alex Edelstein
Sr. Dir. Product Management - Automation and Decisioning
Salesforce

<http://smart.salesforce.com/sig/aedelstein//us_mb/default/link.html>

**Comment by ericrsmith35** [comment]
@philipmarinovnext The component keeps the "selected" records and the "edited" records in different attributes.  Only use the SObject collection variable defined in the Output section for "Output Selected <object>" to process the record IDs for the selected records.  Assign a variable in the Output section to the same attribute you passed into the component "Collection - <object>" to access the edited records.

**Comment by adwhite75** [comment]
Hey Eric - does the new inline editing feature not support Lookup fields? Tried adding one to the table and doesnt look like it brings up the Lookup dialogue.

**Comment by ericrsmith35** [comment]
No, Lookup and Picklist fields are not supported.

**Comment by adwhite75** [comment]
Thanks - I figured as much. Appreciate all your hard work!

**Comment by gconarton** [comment]
Hi Eric,

I've been able to have this awesome solution working in my use case.  I'm curious if there is a row limit on this?  I have approx 330 lines that I need to pull in and before I go digging too deep as to why I'm not getting records now, I thought I would check.

Thanks!

Gwen

**Comment by ericrsmith35** [comment]
Gwen,

The datatable component does not have a limit.  It acts on the entire
sObject collection that is passed to it.  Adding pagination would be a good
enhancement.

Eric

**Comment by gconarton** [comment]
Yes it would!  Thank you for your prompt response.

**Comment by ericrsmith35** [comment]
Pagination would still be a nice enhancement
