### ISSUE TITLE
Winter 20 Breaking datatableFSC

### ISSUE THREAD

**Issue by adwhite75** [alexed1/LightningFlowComponents#187]
It looks like Winer 20 has broken the way selections are passed to the sobject collection variables. I've tested the same flow between a Spring 19 and Winter 20 box and both behave differently. The Winter 20 box does not properly populate the collection for the selected records.

**Comment by ericrsmith35** [comment]
I am not able to reproduce this behavior.  Can you share how you are defining all of your attributes and how you are processing the collection that is returned?

**Comment by adwhite75** [comment]
Hi Eric -

Sure. I tested the same flow in a Spring and Winter box and got different behavior. I am defining a 'sobj_collection_Accounts_Searched' variable to pass into the datatable. That works just fine. I am also defining an 'sobj_collection_accounts_Selected' variable into the Output - Accounts part of the component (input/output checked on the variable). When I then check the value of the output sobject collection on a subsequent screen, it's null. 

I tried the same flow on a Spring box in a full copy sandbox and it is working as expected.

**Comment by adwhite75** [comment]
`FAST LOOKUP: get_test_cases
Find all Case records where:
Subject Contains test
Store those records in {!sobj_coll_CasesSearched}.
Save these field values in the variable: Id, Subject
Result
Successfully found records.
SCREEN: test_datatablefsc
Lightning Component: CaseTable
Screen component: c:datatableFSC
Inputs:
column01_fieldName = (Subject)
column01_label = (Subject)
mydata_standard3 = sobj_coll_CasesSearched ([{Id=500q000000CBXTNAA5, Subject=Create Contact/Company for Development - Contact: - Company: test}, {Id=500q000000DmUgKAAV, Subject=Create Contact/Company for Development - Contact: - Company: Test Comp}, {Id=500q000000CSTNFAA5, Subject=Create Contact/Company for Development - Contact:Adam White - Company: Test Company 1234}, {Id=500q000000DmWEDAA3, Subject=Create Contact/Company for Development - Contact:test case 2 - Company:}, {Id=500q000000DmXujAAF, Subject=Create Contact/Company for Development - Contact:test contact - Company: Test comp}, {Id=500q000000DmWsSAAV, Subject=Create Contact/Company for Development - Contact:Test contact test - Company:}, {Id=500q000000DmW7RAAV, Subject=Create Contact/Company for Development - Contact:Test test - Company:}, {Id=500q000000DmX57AAF, Subject=Create Contact/Company for Development - Contact:test test - Company:}, {Id=500q000000CqvKUAAZ, Subject=Create Contact/Company for Development - Contact:Test Test - Company: TEst}, {Id=500q000000DmY7nAAF, Subject=Create Contact/Company for Development - Contact:test test - Company: test comp}, {Id=500q000000JYkkVAAT, Subject=Milestone Test}, {Id=500q000000JYkntAAD, Subject=Milestone Test}, {Id=500q000000JpK6ZAAV, Subject=New Deal Data Quality Verification for TEST4}, {Id=500q000000JpK5uAAF, Subject=New Onboarding Case for TEST4 - Change of Ownership}, {Id=500q000000JpK6YAAV, Subject=New Onboarding Case for TEST4 - Change of Ownership}, {Id=500q000000JokWkAAJ, Subject=Onboarding Case for Portfolio Test 5 - Change of Ownership}, {Id=500q000000JpK5GAAV, Subject=Onboarding Case for Portfolio Test 5 - Change of Ownership}, {Id=500q000000JpK5QAAV, Subject=Onboarding Case for Portfolio Test 5 - Change of Ownership}])
selectedRows_standard3 = sobj_coll_SelectedCases (null)
Outputs:
column01_fieldName = Subject
column01_label = Subject
column01_type = text
column02_type = text
column03_type = text
column04_type = text
column05_type = text
column06_type = text
column07_type = text
column08_type = text
column09_type = text
column10_type = text
hideShow = show
mydata_standard1 = []
mydata_standard2 = []
mydata_standard3 = [[Case (Subject:Create Contact/Company for Development - Contact: - Company: test, Id:500q000000CBXTNAA5)], [Case (Subject:Create Contact/Company for Development - Contact: - Company: Test Comp, Id:500q000000DmUgKAAV)], [Case (Subject:Create Contact/Company for Development - Contact:Adam White - Company: Test Company 1234, Id:500q000000CSTNFAA5)], [Case (Subject:Create Contact/Company for Development - Contact:test case 2 - Company:, Id:500q000000DmWEDAA3)], [Case (Subject:Create Contact/Company for Development - Contact:test contact - Company: Test comp, Id:500q000000DmXujAAF)], [Case (Subject:Create Contact/Company for Development - Contact:Test contact test - Company:, Id:500q000000DmWsSAAV)], [Case (Subject:Create Contact/Company for Development - Contact:Test test - Company:, Id:500q000000DmW7RAAV)], [Case (Subject:Create Contact/Company for Development - Contact:test test - Company:, Id:500q000000DmX57AAF)], [Case (Subject:Create Contact/Company for Development - Contact:Test Test - Company: TEst, Id:500q000000CqvKUAAZ)], [Case (Subject:Create Contact/Company for Development - Contact:test test - Company: test comp, Id:500q000000DmY7nAAF)], [Case (Subject:Milestone Test, Id:500q000000JYkkVAAT)], [Case (Subject:Milestone Test, Id:500q000000JYkntAAD)], [Case (Subject:New Deal Data Quality Verification for TEST4, Id:500q000000JpK6ZAAV)], [Case (Subject:New Onboarding Case for TEST4 - Change of Ownership, Id:500q000000JpK5uAAF)], [Case (Subject:New Onboarding Case for TEST4 - Change of Ownership, Id:500q000000JpK6YAAV)], [Case (Subject:Onboarding Case for Portfolio Test 5 - Change of Ownership, Id:500q000000JokWkAAJ)], [Case (Subject:Onboarding Case for Portfolio Test 5 - Change of Ownership, Id:500q000000JpK5GAAV)], [Case (Subject:Onboarding Case for Portfolio Test 5 - Change of Ownership, Id:500q000000JpK5QAAV)]]
mydata_standard4 = []
mydata_standard5 = []
mydata_standard6 = []
selectedRows_standard1 = []
selectedRows_standard2 = []
selectedRows_standard3 = []
selectedRows_standard4 = []
selectedRows_standard5 = []
selectedRows_standard6 = []

Selected Navigation Button: NEXT
ASSIGNMENT: count_number_selected
{!count_of_sobj} Assign Count {!sobj_coll_SelectedCases}
Result
{!count_of_sobj} = "0"`

**Comment by adwhite75** [comment]
Also, @alexed1  you should know that the new Sobject variable creation quality of life feature totally breaks the component, you can't even save a flow with the datatable using  that as an input.

**Comment by adwhite75** [comment]
I noticed that the 'Output' section is gone in the Winter box vs the Spring box: 

![image](https://user-images.githubusercontent.com/43993412/65771197-ab81b000-e105-11e9-9f81-02ba9c32d6f4.png)

**Comment by ericrsmith35** [comment]
Are you checking the manually assign variable box so you can put your
'sobj_collection_accounts_Selected' in the Output section?

[image: image.png]

**Comment by alexed1** [comment]
@adwhite75 I'm interested in your finding that the automatic output handling has an incompatibility with Datatable. Can you give me a little more detail? Can you repro the problem on  winter 20 scratch org?

**Comment by adwhite75** [comment]
@alexed1  I get the following error when I save my flow when I populate a datatable with the Winter 20 pre-defined collections from a lookup:

An unexpected error occurred. Please include this ErrorId if you contact support: 379474085-20321 (1397861458)

**Comment by ericrsmith35** [comment]
Try manually assigning the collection variables.

**Comment by adwhite75** [comment]
That did it @ericrsmith35 ! I thought you only had to manually assign the outputs, but looks like it worked for the input as well! Might want to make a callout to that on the page if it isnt already and I missed it.

**Comment by ericrsmith35** [comment]
Waiting to see if Alex & team can find a root cause for the issue first.

Eric

**Comment by adwhite75** [comment]
So it saves properly but unfortunately it doesnt populate the table with the data.

**Comment by ericrsmith35** [comment]
Feel free to share how you have configured the attributes and I'll take a
look.

**Comment by ericrsmith35** [comment]
Spring '20 will resolve this issue!
