### ISSUE TITLE
Unable to substitute another formula field for I2-Display Which Field?

### ISSUE THREAD

**Issue by RachelB416** [alexed1/LightningFlowComponents#188]
Using the lookup on Contact object. I want to use a different display field other than Name as there are multiple Contacts with same Name. In flow debug, Name is still the value displayed. 
![image](https://user-images.githubusercontent.com/55809338/65631189-aa813f00-df9c-11e9-9093-78eca2c5705b.png)

What I See: (Contact's Name)
![image](https://user-images.githubusercontent.com/55809338/65631227-bec53c00-df9c-11e9-8fa6-d31654c244ff.png)

Should be: (Contact's Name, Location, Title)
![image](https://user-images.githubusercontent.com/55809338/65631260-cb499480-df9c-11e9-953e-8c4cd3b09d83.png)

**Comment by ericrsmith35** [comment]
I2_Display Wich Field is looking for the API name of a field from the I1_Object Name object(Contact).

**Comment by RachelB416** [comment]
I see. I did select it from the flow sobject instead of just entering the api name.
