### ISSUE TITLE
Winter 20 broke Rich Text Input?

### ISSUE THREAD

**Issue by etech0** [alexed1/LightningFlowComponents#189]
Since Winter 20 (which we got Oct 5), my RichTextInputFSC stopped working. Whatever is in the 'value' box does not display as the default text. Rather, the default text is just "hello".

Screenshots: https://i.imgur.com/RRwiL3d.png
https://i.imgur.com/uzXMDoD.png

This happens whether the "Manually Assign Checkboxes" is checked or not.

Please advise... thank you!

**Comment by bummfelix** [comment]
We have the same problem since our org runs on Winter '20. Did someone managed to find a fix for this?

**Comment by alexed1** [comment]
That bug appears to be inside the base component we're using. Rather than try to figure it out, I've created a new V2 based on LWC instead of the old aura. Try it and let me know if it works for you:
https://login.salesforce.com/packaging/installPackage.apexp?p0=04tB0000000OE9hIAG

**Comment by mtagler-relativity** [comment]
@alexed1 I got the following message when trying to put this in my prod org. I need to replace the old package to replace some critical broken functionality.
![image](https://user-images.githubusercontent.com/42183570/66783390-6bf4eb00-ee9d-11e9-95eb-8570206acbe1.png)

**Comment by etech0** [comment]
@mtagler-relativity did you try installing it into sandbox and then deploying to production? I'm out of the office but will try that when I get back.

**Comment by mtagler-relativity** [comment]
I installed it in production with your last modification, but the component isn't working. If I pull text in via the flow, it displays and writes back to the output variable. Anything manually input into the rich text fields is not sticking. When I go into debug, it says the value is null.

Mary

________________________________

**Comment by etech0** [comment]
hmmm I guess let's see what @alexed1 responds then

**Comment by alexed1** [comment]
I put a new version at https://unofficialsf.com/rich-text-input/ that you should try. I had not been applying the final "promote" command that is now required in sfdx package creation.

**Comment by etech0** [comment]
I just installed the new version and it works great! Note to everyone: after installing the new version, you will need to manually replace each of your Rich Text Components with the new LWC version of the component.

Thank you @alexed1 for fixing this!
