### ISSUE TITLE
Namespace Change to LookupFSC?

### ISSUE THREAD

**Issue by danmwendo** [alexed1/LightningFlowComponents#191]
We've implemented lookupComponentFSC in our sandbox, but we're struggling to find the installation package for it now for our production environment.

It appears the namespace has changed, and that you're no longer listed as publisher, and this is causing deployment issues.

Was the namespace changed?

**Comment by ericrsmith35** [comment]
There are both an Unmanaged (no namespace) and Managed (with namespace) install package available now.
