### ISSUE TITLE
Data Table not refreshing with new Get records

### ISSUE THREAD

**Issue by brainage2** [alexed1/LightningFlowComponents#200]
I am trying to use the data table to display search results of products based on user selecting certain attributes of the product, which filters the Price book entry object.

The steps to reproduce is:

First screen has a list of fields , user selects the values, click next,
Second screen displays the data returned by Get Records
Click previous again , go back to the first screen, change the criteria and click next, the second screen with the data table still displays the same results from the first query.

Also when I use data type Percent the value 4.50% displays as 450% in the data table.

I appreciate you providing these tools.

**Comment by ericrsmith35** [comment]
Backing up in Flows can be a complicated issue, the behavior you see is currently the expected result.  Alex Edelstein just wrote an explanation [here](https://unofficialsf.com/optimizing-lightning-component-inputs-and-outputs-in-flow-screens/).

The Percent data type formats a number with the percent sign.  If your value is .045, it will display as 4.50%.  If your value is 4.5, it will display as 450%.

**Comment by brainage2** [comment]
Thank you.
