### ISSUE TITLE
Flow not executing for non-admin users

### ISSUE THREAD

**Issue by seanrmsy** [alexed1/LightningFlowComponents#201]
I am using datatableFSC for a client. It is working great when running as System Administrator but no other profile is able to run the Flow interview. They are able to load/start the interview but once executed it errors out. The Flow is effectively 2 steps: (1) pick a record Id for an object (2) display all the related records where the record id is equal to 1 and (3) display these in the datatableFSC.

Like I said, it works great for System Admin. Any other profile doesn't work. I don't know if this is related to datatableFSC Flow Component but I' thought I'd check in. Once I install it, are there any other permissions I need to set for other users to be able to use this? Any reason it wouldn't load for them?

The error people are getting is:
moduleapi.interaction.FlowExtensionServiceException: Error defining componentflexipage.common.impl.api.component.designtimeinfo.DesignTimeComponentInfoAuraLazyImpl@7856b1e9 (when running from List View)

And...
This page has an error. You might just need to refresh it. Error in $A.getCallback() [[object Object]] Callback failed: serviceComponent://ui.interaction.runtime.components.controllers.FlowRuntimeController/ACTION$runInterview Failing descriptor: {markup://flowruntime:flowRuntime} (when running from record detail page)

**Comment by seanrmsy** [comment]
Removed datatableFSC and just outputted values and it worked for all users. Not sure what's going on but would love a fix and/or an alternative.

**Comment by ericrsmith35** [comment]
It turns out that even though you are only accessing one of the listed Standard and Custom objects, the user needs to have permissions to access all of them listed in the component to avoid the error.

One work-around you can try is to change the name of any of the objects that the users do not have access to, to ones that they are able to access.

At some point, I will post a single object version of the component with instructions on how to set it up for the one you want to reference.

**Comment by seanrmsy** [comment]
Can I eliminate / comment out any of the standard objects so that, for example, there are just 3 (Accounts, Contacts and Opportunities)?

**Comment by ericrsmith35** [comment]
Yes, you can comment out the objects you do not need.  You have to do so in datatableFSC.cmp, datatableFSC.design and datatableFSCController.js.  In the controller, you only need to comment out the uneeded lines in the // Object Selection section.  You can leave the code in the // Return Selected Table Rows section.

**Comment by syedmoizacc** [comment]
Hi Alex,

We have tried couple of workarounds mentioned above.

- Recreating flow elements where DatatbleFSC is referenced

- Comment out the objects that are not in use from the package

We are still getting the same error as attached here while we navigate to the Screen in the flow
![datatablefsc](https://user-images.githubusercontent.com/61133537/76712648-e1c3f200-676e-11ea-9c69-230eb9134da6.png)

**Comment by ericrsmith35** [comment]
@syedmoizacc First thing to check is that you have made the source code edits in all three of the mentioned files.

**Comment by alexed1** [comment]
One incongruous thing that's jumping out, Eric, is that the error mentions
flexipages, but the component is being used in a community page, which
doesn't involve flexipages.

Also came across this similar bug report:
https://developer.salesforce.com/forums/?id=9062I000000XnIXQA0

 Is there anything in the datatable code that involves flexipages?


Alex Edelstein
Sr. Dir. Product Management - Automation and Decisioning
Salesforce

<https://smart.salesforce.com/sig/aedelstein//us_mb/default/link.html>

**Comment by ericrsmith35** [comment]
The component only implements lightning:availableForFlowScreens.
