### ISSUE TITLE
lookupFSC not outputting correct values

### ISSUE THREAD

**Issue by danmwendo** [alexed1/LightningFlowComponents#204]
Hi,

I am trying to output a short text field (Description__c) as the value to be used from my lookupFSC component. Unfortunately it is not returning the list of records if i select that as my "I4_Output Which Field as Value?"

What is also interesting is if I set "I4_Output Which Field as Value?" to Id, I get the records to display in the drop-down, but if i then try and get records with that Id it seems that lookupFSC has passed the value of "Id" as opposed to an actual record Id.

Any ideas?

**Comment by ericrsmith35** [comment]
What are you using for **I2_Display Which Field?**  That is what determines what gets displayed in the drop-down.

**I4_Output Which Field as Value?** determines which field value gets assigned to the variable you specify in the **Store Output Values to Select Variables** section for **O1_Output Value**

Note: You need to select the **Manually assign variables (advanced)** checkbox.

**Comment by danmwendo** [comment]
Hi Eric,

Thanks for the response.

I have Description__c in the **I2_Display Which Field?**
I wanted to output the same field through **I4_Output Which Field as Value?**
But if I tried that, the values wouldn't display once i ran the flow.

I have been using **Manually assigned variables** all along.

I ended up removing the component, saving the flow, reloading the page, and adding the component again.
I still can't get the values to display if I use Description__c for **I4_Output Which Field as Value?**
But I did manage to get the Id working properly which it wasn't doing previously.

**Comment by ericrsmith35** [comment]
There are a couple of gotchas here.  You can't *I2_Display* a Long Text
Area field, but you can use one as an *I4_Output *field.

You can't use the same field for *I2_Display *and  *I4_Output*.  I'm not
sure why and I'm not able to put the time into tracking it down right now.
As a workaround, you could always output the Id and then use a Get Records
in your flow to pick up any other field values you want from the selected
record.

Eric
