### ISSUE TITLE
Variable as Output in datatableFSC

### ISSUE THREAD

**Issue by energidi** [alexed1/LightningFlowComponents#207]
Hi,
As far as I understand, we can only add Collections as an output.
Since a single selection is allowed, I sometimes need to assign the selected record id to a variable, not to a collection.

Thanks,
Gidi

**Comment by ericrsmith35** [comment]
In that case just insert a loop on the collection variable and act upon the
one and only record in the collection.

**Comment by energidi** [comment]
Eric Hi,
Thank you for your answer.
As you suggested, I am using a loop on the collection.
It will be nice to avoid it and immediately assign a variable instead.

Thanks,
Gidi
