### ISSUE TITLE
Error installing: availability for my instance of salesforce.com

### ISSUE THREAD

**Issue by dbruce94117** [alexed1/LightningFlowComponents#22]
Hi. I could not install in either a production lightning environment nor a developer classic environment. Any idea why I'm getting this error?

Mismatching Versions | The AppExchange Application or component you have selected is not yet available on your instance of salesforce.com. Please check back in a few days to retry the installation. Press the back button of your browser now and bookmark the AppExchange Directory page so that you can find it later.
-- | --

**Comment by dbruce94117** [comment]
Please note, that the link to the AppExchange Directory page is posted on: https://sites.google.com/view/flowunofficial/flow-screen-components/lookup?authuser=0. 

Today the link is different with one for Spring '18 and one for Summer '18. I will be investigating these and reporting my findings. I also did not have "Enable Lightning Runtime for Flows" checked in my orgs, as stated under Important Setup Notes: https://github.com/alexed1/LightningFlowComponents. Perhaps the install checks that? We'll soon see...

**Comment by alexed1** [comment]
That problem appears to have been caused when someone tried to install a package that we created on a Summer '18 org to their own Spring '18 org. As a result, we put up two versions. Problem addressed ?

**Comment by dbruce94117** [comment]
Yes! Thank you.
