### ISSUE TITLE
Unable to add link to toast

### ISSUE THREAD

**Issue by AndersonKatharineTNC** [alexed1/LightningFlowComponents#220]
Is there any way to make it so that a link is displayed in the toast message (like to the record that was just created in the flow)? I know I can add the URL as text, but making it a hyperlink (like the toast that shows after a custom action completes) would make the experience much more user friendly.

**Comment by ericrsmith35** [comment]
@AndersonKatharineTNC I have just created a Pull Request#222 for an updated version of the component that will support adding a URL to the message.  The update also adds support for setting the title, mode, duration and icon.

**Comment by ericrsmith35** [comment]
@AndersonKatharineTNC You can also use the NavigateToRecord component to redirect your flow to a record in either View or Edit mode.
