### ISSUE TITLE
Datatable - An unexpected error occurred

### ISSUE THREAD

**Issue by pcarass** [alexed1/LightningFlowComponents#224]
Hi @alexed1 / @ericrsmith35 ,
I'm just installed the Datatable component and am having some trouble with it.

![screenshot-sensys--preprod lightning force com-2019 12 17-12-42-40](https://user-images.githubusercontent.com/17454963/70996711-45d10e80-20cb-11ea-9097-e5b7acbd8325.png)

I have customized the DatatableFSC.cmp and DatatableFSC.design to included "Products Consumed" (Field Service Lightning). This has been added and unmarked in both files:

![screenshot-sensys--preprod my salesforce com-2019 12 17-12-40-18](https://user-images.githubusercontent.com/17454963/70996752-5aada200-20cb-11ea-8f79-9ef861622c2c.png)

![screenshot-sensys--preprod my salesforce com-2019 12 17-12-41-34](https://user-images.githubusercontent.com/17454963/70996761-5d0ffc00-20cb-11ea-902e-91e46ab08e96.png)

Within the screen component, the Products Consumed option is displaying correctly, and allowing me to choose my record collection variable , and choose my output collection for selected items.
In the below screen shot I am just adding the one column of Quantity Consumed

![screenshot-sensys--preprod lightning force com-2019 12 17-12-49-05](https://user-images.githubusercontent.com/17454963/70996925-b710c180-20cb-11ea-90ec-3953b529099d.png)

![screenshot-sensys--preprod lightning force com-2019 12 17-12-55-10](https://user-images.githubusercontent.com/17454963/70997260-89784800-20cc-11ea-9c7e-1f8692736811.png)

Can you see what might be causing the error? I've uninstalled and reinstalled the component, and still no luck.
Thanks
Paul

**Comment by ericrsmith35** [comment]
Did you also uncomment the corresponding code lines in the
datatableFSCController.js file?

Eric

**Comment by pcarass** [comment]
Hey @ericrsmith35,
I hadn't uncommented them , but I have now and still receiving the same error:

![screenshot-sensys--preprod lightning force com-2019 12 18-09-35-43](https://user-images.githubusercontent.com/17454963/71075247-a28c0200-217b-11ea-8a08-3835a1f53d1e.png)

![screenshot-sensys--preprod lightning force com-2019 12 18-09-48-16](https://user-images.githubusercontent.com/17454963/71075257-a61f8900-217b-11ea-9270-263f953b6de6.png)

Paul

**Comment by ericrsmith35** [comment]
In your Get Consumed Products, manually assign an output sObject collection variable and use that as the input to the datatable component.

**Comment by pcarass** [comment]
@ericrsmith35 You're a gent!!!
That did the trick. I just threw in the one column to test it and its working correctly 👍 
![screenshot-sensys--preprod--c visualforce com-2019 12 18-17-03-30](https://user-images.githubusercontent.com/17454963/71107135-780c6a00-21b8-11ea-8fea-bf71daa2f859.png)

Thanks for jumping on so quickly. Really looking forward to working with this Component. Got high hopes!
Paul
