### ISSUE TITLE
Not clear where to enter default value in richTextInputFSC component

### ISSUE THREAD

**Issue by DMarx-UWW** [alexed1/LightningFlowComponents#241]
The [documentation](https://github.com/alexed1/LightningFlowComponents/blob/master/flow_screen_components/richTextInputFSC/README.md) clearly shows a display with the "my default value" populating the input, but no where in the component configuration is it clear where this can be set.

Am I missing something?

Thank you again for putting this together!

**Comment by janvanlishout** [comment]
You can check the fix in https://github.com/alexed1/LightningFlowComponents/issues/189
There is a new package generated on https://unofficialsf.com/rich-text-input/

**Comment by DMarx-UWW** [comment]
@janvanlishout - YES! 1.51 fixed it. Thank you and @alexed1 for this great dev
