### ISSUE TITLE
Still getting his page has an error. You might just need to refresh it. Action failed: c:LightningLookup$controller$hover [$ is not defined] Failing descriptor: {c:LightningLookup$controller$hover} error

### ISSUE THREAD

**Issue by kensation** [alexed1/LightningFlowComponents#25]
I installed the Spring 18 package, but I am still getting this error when testing. Has this been resolved in the Summer 18 package?

**Comment by alexed1** [comment]
yep. you spotted it. Just pushed a new version that includes it and should resolve this.
