### ISSUE TITLE
Quick Choice FSC: Visual Cards do not scale on mobile devices

### ISSUE THREAD

**Issue by clifford-fra** [alexed1/LightningFlowComponents#251]
Visual Cards do not scale on mobile devices:

![Example_Screen](https://user-images.githubusercontent.com/55443386/72418899-05bd8400-377c-11ea-8f26-dad561c85c68.png)

It would be nice, if the cards would be within the borders.

Edit: Happens only on devices with a resolution of 720p and looks good on devices with 1080p. This makes this issue less severe.

**Comment by ericrsmith35** [comment]
Currently, they are a fixed size.  It would be a nice enhancement for someone to make to size these for a smaller device.

**Comment by clifford-fra** [comment]
Hey Everyone,

almost one year later, I fixed the issue by adding the following code to the css:

```
/** Responsive Layout **/
.slds-visual-picker_vertical .slds-visual-picker__figure {
    min-height: var(--lwc-sizeXxSmall,6rem) !important;
    height: auto !important;
}

.slds-visual-picker_vertical {
    max-width: var(--lwc-sizeLarge,25rem);
    width: auto !important;
}

.slds-visual-picker_vertical .slds-visual-picker__figure {
    width: inherit !important;
}
```

This fix addresses issues with the width and the height and makes both responsive.

I still need to test with the current Quickchoice component v2.31 and dual columns view.

**Comment by ericrsmith35** [comment]
I look forward to learning the results of your testing.

**Comment by clifford-fra** [comment]
I tested today and the plain CSS fix didn't do the trick for dual columns view. That's why I decided to make responsive cards only for the single column view. Here's the code:

1. Add two new functions to the javascript file:


```
get cardSize() {
    return this.dualColumns ? 'width:25rem' : 'min-height: var(--lwc-sizeXxSmall,6rem) !important; height: auto !important; width: inherit !important;';
}

get responsiveSize() {
    return this.dualColumns ? '' : 'max-width: var(--lwc-sizeLarge,25rem); width: auto !important;';
} 
```

2. Change the HTML file by adding `style={responsiveSize}` to the line, where you call the `columnClass`:

```
...
<div class={gridClass} style={gridStyle}>
                <template for:each={items} for:item="item">
                    <div key={item.name} class={columnClass} style={responsiveSize}>
...
```

3. Now, add the `cardSize()` function call at two places. First, for cards with icons:

```
...
<!-- Display Visual Card Pickers with Icons-->
                            <template if:true={includeIcons}>
                                <span
                                    class="slds-visual-picker__figure slds-visual-picker__text class=slds-box slds-box_link slds-box_x-small slds-media"
                                    style={cardSize}>
...
```

and after that for cards without icons:

```
...
 <!-- Display Visual Card Pickers without Icons-->                            
                            <template if:false={includeIcons}>
                                <span
                                    class="slds-visual-picker__figure slds-visual-picker__text"
                                    style={cardSize}>
...
```

The width will be responsive and the height adapts to the content inside:
![updated_1](https://user-images.githubusercontent.com/55443386/104919499-a4d01980-5996-11eb-9c4f-20bacffbdf75.png)
![updated_2](https://user-images.githubusercontent.com/55443386/104919502-a568b000-5996-11eb-9c22-040857ffdf73.png)

**Comment by ericrsmith35** [comment]
This is great.  Are you up to creating a Pull Request for the changes here
and writing up a brief blog post?
https://github.com/alexed1/LightningFlowComponents/tree/master/flow_screen_components/FlowScreenComponentsBasePack/force-app/main/default/lwc/fsc_quickChoiceFSC

**Comment by clifford-fra** [comment]
I will create a pull request and write a blog article. It may take some days because I have to finish some other work first.
