### ISSUE TITLE
Flow with datatable in Spring 20 won't run in Winter20

### ISSUE THREAD

**Issue by dschueler** [alexed1/LightningFlowComponents#256]
Are there known issues with latest Datatable in Winter20? Did a flow in Spring20..tried to deploy it over to another Sandbox with Winter20 and we are getting internal SF errors.

**Comment by ericrsmith35** [comment]
No issues that I am aware of.  What are your errors?

**Comment by cchrisv** [comment]
Did you use features only available in Spring20?
