### ISSUE TITLE
Create announcement for SaveRecordsAsync

### ISSUE THREAD

**Issue by alexed1** [alexed1/LightningFlowComponents#258]
Need to post on this.

David, I'm assigning this to you to give you first crack it: a lot of developers have their own blogs and like to post. If you do that, I'll then post on unofficialsf and link out to your page. However,there are two equally great things we can do:
2) I'll give you author rights on unofficialsf and you can write the post right there 
or
3) if you don't have time to write up the post, I'll do it myself (or seek another volunteer)
your call....

**Comment by davidentremont** [comment]
Thanks Alex, I can handle writing a post and finishing up an example to
use. I had to step away for a couple days but will get back on Monday.

Cheers,
David

**Comment by adwhite75** [comment]
https://success.salesforce.com/issues_view?id=a1p3A0000003fH1QAI I seem to have hit this issue using your invocable @davidentremont  - I passed in an empty string for a multi-select picklist field for a record in a collection and got the following error:

Upsert failed. First exception on row 0; first error: INVALID_TYPE_ON_FIELD_IN_RECORD, Role: value not of required type: []: [Role__c]
--

**Comment by adwhite75** [comment]
It seems like KatieKodes over at Reddit / SF Discord brought up an interesting workaround - https://katiekodes.com/salesforce-error-invalid-type-picklist-flow/

**Comment by adwhite75** [comment]
All - looks like Clint over at SF Stack Exchange found a fix for this - https://salesforce.stackexchange.com/questions/299459/flow-passing-in-record-with-picklist-value-into-invocable-apex-method-causes-err

We plan to implement this in our own queueable coming soon
