### ISSUE TITLE
datatableFSC - Picklist Values - Question

### ISSUE THREAD

**Issue by AndyHaas** [alexed1/LightningFlowComponents#273]
Can the Datatable work with picklist values? I want the user to be able to edit the column which is a picklist and get a list of values they can choose from. 

Thanks in advance

**Comment by ericrsmith35** [comment]
Editing a field as a Picklist or Lookup is not currently supported in this component.

**Comment by AndyHaas** [comment]
If I was an ambitious developer. How would I go about and doing this? And maybe doing a pull request for everyone.

**Comment by ericrsmith35** [comment]
I'm thinking you might be able to do it by mimicing a picklist with row actions.  Take a look here:
https://developer.salesforce.com/docs/component-library/bundle/lightning:datatable/example#lightningcomponentdemo:exampleDatatableStaticRowActions

**Comment by AndyHaas** [comment]
I will definitely check this out. I found this component the other day and updating so much! How about checkboxes? Can this data table update checkboxes?

**Comment by ericrsmith35** [comment]
Yes, I'm pretty sure it can.

**Comment by AndyHaas** [comment]
Yeah, just figured it out. I was being to smart for my own good. A checkbox programmatically is a boolean. I was typing in Checkbox, not Boolean. I for quick deployment will just do a slide of hand with a checkbox and a flow update.

**Comment by AndyHaas** [comment]
Closing - Feature Request to enable editing of checkbox
