### ISSUE TITLE
Apex action "FindRecordsInCollection" is missing the value for type mapping "T__inputCollection".

### ISSUE THREAD

**Issue by adwhite75** [alexed1/LightningFlowComponents#287]
When trying to deploy a Flow to another environment using the FindRecordsInCollection action I get the following error: 

Apex action "FindRecordsInCollection" is missing the value for type mapping "T__inputCollection".

I tried changing the InputCollection to both a Salesforce-provided collection (from a Get) and one that I made within the flow - both seem to trigger the same error.

The action works just fine in the Flow, it seems to be a deployment issue.

**Comment by adwhite75** [comment]
@alexed1

**Comment by adwhite75** [comment]
Could be related to the fact that I am only deploying that action and not others in the package? Is it reliant on another class I am missing?

**Comment by adwhite75** [comment]
I wonder if this is an issue with making deployments via the API - I was able to get this to validate using a traditional (albeit awful) Changeset. When using the exact same components using ClickDeploy, it gave the error message.

**Comment by alexed1** [comment]
I think you're right. It was pointed out to me that dynamic sobject support
is beta and doesn't have full packaging support. That's probably causing
what's happening here.

Can you list out your exact set of steps?
alex

Alex Edelstein
Sr. Dir. Product Management - Automation and Decisioning
Salesforce

<http://smart.salesforce.com/sig/aedelstein//us_mb/default/link.html>

**Comment by adwhite75** [comment]
Sure - in my flow I have:

Object for "inputCollection" (Input) mapped - Set to a custom object
Object for "multipleOutputMembers" (Output) - Set to a custom object
Object for "singleOutputMember" (Output) - Set to a custom object

inputCollection - Set to a collection variable of the same sobject type above
Target field - API name of the field I am filtering on in the input collection
targetObject - API Name of the input collection / object of the Target field
targetValue - the value I am filtering on

And my outputs are all set accordingly.

In ClickDeploy I am packaging:
- The Flow
- Two custom fields
- The FindRecordsInCollection apex class
- 4 Profiles (including Sys Admin)
- a datatableFSC-derived component that sits in the flow

I then try to validate and get that error.

**Comment by adwhite75** [comment]
Related to the outputs of this class - I saw something odd:

FINDRECORDSINCOLLECTION (APEX): Find_properties_tied_to_contact
Inputs:
targetObject = Contact_Association__c
inputCollection = {!Get_all_Property_Associations_for_Contact} ([Contact_Association__c (a0a0v0000026imeAAA)])
targetField = Property__c
targetValue = {!sobj_PropertyLoop.Id} (a060h00001cEhfCAAS)
Outputs:
**{!sobj_coll_PropertiesForContact} = multipleOutputMembers ([])**
**{!sobj_propertiesFoundForContactAssociation} = singleOutputMember (null)**

Can you explain whats happening here? Why is it that the collection variable output is being set to '[]' vs the single being set to null? Is [] the same as null in the debugger?

**Comment by alexed1** [comment]
I was wrong about there being a packaging gap. This sounds like a bug. Can you open a case and tell Support that I have requested an Investigation? 

The [] is actually [ and ] really close together. it represents an empty list/array/collection. This is saying that nothing came back, but it's not null, because a container had to be initialized in the event that something did come back.

**Comment by adwhite75** [comment]
Unfortunately I dont have access to create cases on behalf of my client - can I create cases without being tied to an org?

On your empty list comment, how would I do a decision on that if it isnt null? Right now I am assigning the returned result count to a number and doing a decision based on that.

**Comment by alexed1** [comment]
Ok, it's looking like this issue comes up when you try to deploy something with an older version. Make sure that your metadata all says version 48 and that your sfdx client is updated.

**Comment by adwhite75** [comment]
Thanks Alex!
