### ISSUE TITLE
Sandbox deployment error

### ISSUE THREAD

**Issue by ChewinChaz** [alexed1/LightningFlowComponents#289]
While validating a large change set, I get this error: table_JS_Quotes (Screen Component) - We can't find this input attribute: "mydata_custom1".  The flow runs flawlessly in my sandbox org, and the object mydata_custom1 is referencing is included in the change set.  Unfortunately, this is the only information salesforce will give me in the validation details, so I was wondering if you may have seen this before or had any insight?  Thanks

**Comment by ericrsmith35** [comment]
Make sure the references to "mydata_custom1" are not commented out in any of these 3 files:
datatableFSC.cmp
datatableFSC.design
datatableFSCController.js
