### ISSUE TITLE
Error installing CollectionProcessors2 

### ISSUE THREAD

**Issue by solo-1234** [alexed1/LightningFlowComponents#291]
Hi! I just tried installing this package in my sandbox and got an error. Any idea what the problem could be?

Thanks!

Here's the error:

Your request to install package "CollectionProcessors2 ver 0.1" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.

Problem:

1.  Apex compile failure
Apex class FilterCollectionTest: line 12, column 21: Variable does not exist: sourceAccountCollection

2.  Apex compile failure
Apex class FilterCollectionTest: line 13, column 64: Variable does not exist: sourceAccountCollection

3.  Apex compile failure
Apex class FilterCollectionTest: line 19, column 21: Variable does not exist: sourceAccountCollection

4.  Apex compile failure
Apex class FilterCollectionTest: line 20, column 59: Variable does not exist: sourceAccountCollection

5.  Apex compile failure
Apex class FilterCollectionTest: line 25, column 21: Variable does not exist: sourceAccountCollection

6.  Apex compile failure
Apex class FilterCollectionTest: line 30, column 21: Variable does not exist: sourceAccountCollection

7.  Apex compile failure
Apex class FilterCollectionTest: line 32, column 21: Variable does not exist: targetValuesCSVString

8.  Apex compile failure
Apex class FilterCollectionTest: line 33, column 21: Variable does not exist: filterField

9.  Apex compile failure
Apex class FilterCollectionTest: line 40, column 48: Variable does not exist: filteredAccountCollection

10.  Apex compile failure
Apex class FilterCollectionTest: line 51, column 21: Variable does not exist: sourceCaseCollection

11.  Apex compile failure
Apex class FilterCollectionTest: line 52, column 61: Variable does not exist: sourceCaseCollection

12.  Apex compile failure
Apex class FilterCollectionTest: line 58, column 21: Variable does not exist: sourceCaseCollection

13.  Apex compile failure
Apex class FilterCollectionTest: line 59, column 56: Variable does not exist: sourceCaseCollection

14.  Apex compile failure
Apex class FilterCollectionTest: line 64, column 21: Variable does not exist: sourceCaseCollection

15.  Apex compile failure
Apex class FilterCollectionTest: line 69, column 21: Variable does not exist: sourceCaseCollection

16.  Apex compile failure
Apex class FilterCollectionTest: line 71, column 21: Variable does not exist: targetValuesCSVString

17.  Apex compile failure
Apex class FilterCollectionTest: line 72, column 21: Variable does not exist: filterField

18.  Apex compile failure
Apex class FilterCollectionTest: line 79, column 48: Variable does not exist: filteredCaseCollection

**Comment by solo-1234** [comment]
Update: I figured out the problem! I already had FilterCollection and FilterCollectionTest in my org (I believe I installed or copy/pasted them from unofficialsf before they were part of this package). I removed those and then this package installed successfully.

Looking forward to using it!

**Comment by alexed1** [comment]
Good luck!
