### ISSUE TITLE
Quick Choice FSC - card view: store choice value but don't display it

### ISSUE THREAD

**Issue by solo-1234** [alexed1/LightningFlowComponents#294]
Hi! Thanks for a great component.

I'd like to show users a few records to choose from in card view. Is there a way for it to return the record id without displaying in the interface? I'd like it to work like radio buttons, where there's a choice label which is displayed, and a choice value (id) which is returned to the flow. Maybe there should be a 3rd optional value, choice description, which would be the text which displays in smaller in the card.

I hope this is possible! Thanks!

**Comment by ericrsmith35** [comment]
For your input attributes, Choice Labels will be what is displayed as the
large text and returned as the selected value and Choice Values will be
what is displayed as the additional smaller text.  To get a recordId, you
could always do a Get Records after the screen to lookup the record that
matches the value returned by the component.

**Comment by solo-1234** [comment]
Thanks for explaining! I'll make it work but I think it would be a nice feature to have the ability to store a record id and display two pieces of text (the big text and the smaller text).
