### ISSUE TITLE
Issue with 2 Column Display

### ISSUE THREAD

**Issue by colePrato** [alexed1/LightningFlowComponents#296]
2 Columns not Displaying Correctly in Flow Action.

![Flow_2Column](https://user-images.githubusercontent.com/43420867/75997636-a3584880-5ecd-11ea-8d61-d11022a308d7.png)

**Comment by ericrsmith35** [comment]
If you are using quickChoiceFSC, the Visual Boxes have a fixed width and do not resize automatically.

**Comment by colePrato** [comment]
@ericrsmith35  is the Fix in 1.27?

**Comment by ericrsmith35** [comment]
No, there is no fix at this time.
