### ISSUE TITLE
Invalid Aura API Error for LightningLookupHelper.js

### ISSUE THREAD

**Issue by goravseth** [alexed1/LightningFlowComponents#3]
I was manually installing the lookup component into a spring 18 developer org, and the helper would not save, giving an invalid API error for the following lines

246:  var ev = $A.getEvt('c:EvtChangeLookup');
262:  var ev = $A.getEvt('c:EvtClearLookup');
275:  var ev = $A.getEvt('c:EvtInitLookup');

I did some googling and then updated var ev = $A.getEvt('c: to  var ev = $A.get('e: and that allowed me to save.  Have not tested yet to see if the flow component actually works though.

Here is the sfse post that indicated the new approach : https://salesforce.stackexchange.com/a/137070/10062

**Comment by alexed1** [comment]
Did you try installing from the package at https://sites.google.com/view/flowunofficial/flow-screen-components/lookup by chance?  

Those lines of code do look obsolete...

**Comment by goravseth** [comment]
Honestly don't recall.  I was building it manually in Dev console. Was able
to install via package.

.
