### ISSUE TITLE
Issue - Store Output Values to Select Variables

### ISSUE THREAD

**Issue by msol723** [alexed1/LightningFlowComponents#301]
When no record is selected, the Output Value within **Collection -** (not the Output Selected) is storing ALL records regardless of whether I made an update or not. Is this intended?

I would imagine only records that I have made any updates to would be added to the new collection variable, just how the **Output Selected** field works.

I do notice that setting the same Collection variable for the Collection & Output Selected sort of fixes this, I'm just worried users might forget to select record(s) and on only inline edit.

**Comment by ericrsmith35** [comment]
It is normal behavior for the Output Collection to store ALL of the records.  That collection will include any field edits.  The Output Selected collection will contain the Ids of only the selected records.  The field values may or may not contain the edited values.

It is not recommended to use the same variable for both.

**Comment by msol723** [comment]
Thanks @ericrsmith35 , I guess I'm unclear how to properly combine both then. My goal is to **only** include any record(s) where an edit was made. What would you recommend?

**Comment by ericrsmith35** [comment]
Here's a workaround:

- Specify 2 separate output variables (colEdited & colSelected)
- Create a new collection variable (colEditedSelected)
- After the Screen with the datatable - Loop through colSelected
- -Set a variable (varIDs) equal to a Formula (varIDs & colSelected.Id) - You are appending each selected Id to a single variable
- After that, loop through colEdited
- -If varIDs CONTAINS colEdited.Id then
- -Add the loop object variable to colEditedSelected
- When this loop finishes, colEditedSelected will contain just the selected records with the edited values.

**Comment by msol723** [comment]
I took a slightly different approach (but you got me most of the way there!), my concern with your workaround is that it still relies on the user to select the record(s) to indicate they want to update it. I'd rather identify any record that has been changed. 

Workaround:
Compare the Original Record Collection (passed to the datatablefsc) to the New Record Collection (colEdited) by looping through them in the same order. If there's a mismatch, add the record to colEditedSelected and then lastly, do a fast update. Please let me know if you have any feedback.

Thank you!

![image](https://user-images.githubusercontent.com/62157474/76809272-85c98f80-67a7-11ea-9239-71d565b005f1.png)

**Comment by ericrsmith35** [comment]
I think your solution should work fine for a limited number of records.

Eric

**Comment by msol723** [comment]
I see, thanks again!
