### ISSUE TITLE
'Enter a Valid Value' error when trying add 1 to single or multiple selection

### ISSUE THREAD

**Issue by dbarks1024** [alexed1/LightningFlowComponents#303]
On DatatableFSC I am gettting the below error. 
![image](https://user-images.githubusercontent.com/34486647/77192649-43f45e00-6ab3-11ea-8e38-e65d6a8b9d32.png)

**Comment by ericrsmith35** [comment]
Do you know what version you have installed?

**Comment by dbarks1024** [comment]
2.7

**Comment by ericrsmith35** [comment]
Could you share a screenshot of all of the attribute values?

**Comment by dbarks1024** [comment]
I was apparently using the advanced section to output the collection variable then trying to select 1 on the regular section. I switched to not using the advanced and the regular output worked.
