### ISSUE TITLE
recordDetailFSC: Boolean only selectable by clicking label

### ISSUE THREAD

**Issue by Feldstrom** [alexed1/LightningFlowComponents#305]
Booleans in live flows are only able to have the value set by clicking the label, you are not able to click the checkbox to set a value. 

In debug mode, the label is also clickable however you are also able to set the value by clicking the checkbox. 

This is seen on a sandbox installation - package version 1.4. 

Instance name
CS91 
Release
Spring '20 Patch 14.4

Debug mode:
![ezgif-3-8e95f8340937](https://user-images.githubusercontent.com/30249667/77367430-4f47c380-6d17-11ea-9fbf-f64abcac216f.gif)

Live in flow:
![ezgif-3-29ea27228fe1](https://user-images.githubusercontent.com/30249667/77367446-57076800-6d17-11ea-8b4d-0bdf67eba25a.gif)

This may be due to the input id being incorrectly mapped to the label. https://www.lightningdesignsystem.com/components/checkbox/

**Comment by alexed1** [comment]
I can't reproduce this....do you have an org with this manifesting?  do you want to send some credentials to aedelstein@salesforce.com?

**Comment by Feldstrom** [comment]
I moved this to a DE and had no issues there - I suspect an issue with my environment.
