### ISSUE TITLE
Collection Sort Component doesn't correctly parse sortKeys input

### ISSUE THREAD

**Issue by chrispphillips** [alexed1/LightningFlowComponents#313]
No matter how you format the sortKeys input in the flow action, it will not correctly parse it to have a sorting direction.

I can get it to recognize a field name but no way to tell it to sort in a given direction.

MOD:

1. Modify the SortCollection apex class to add the following lines after 113
System.debug('fieldName=' + fieldName);
System.debug('d.fields.getMap().get(fieldName)=' + d.fields.getMap().get(fieldName));
2. Build a flow with a custom object collection and add the Sortcollection action
3. Set the Input and output collection object as your custom object and set your collection to be the collection you created
4. for sortkey enter: 
"{“sortkeys”: [
{“field”:”Name”,
“direction”:”asc”} ]}"
Be sure to confirm that the quotation marks are correct since copying/pasting them may not work correctly
5. Save and debug the flow and note that it fails.
6. Check your Developer console log and note the following lines:
USER_DEBUG [114]|DEBUG|fieldName=direction
USER_DEBUG [115]|DEBUG|d.fields.getMap().get(fieldName)=null
7. Update your sortkey value to be:
"{"sortkeys": [ {"field":"Name", "Name":"asc"} ]}"
8. Debug the flow again, note that it doesn't fail this time.
9. Check your debug log and note the line:
USER_DEBUG [114]|DEBUG|fieldName=Name
USER_DEBUG [115]|DEBUG|d.fields.getMap().get(fieldName)=Name
10. No matter what is entered into sortkeys, it will not accept a sort direction

**Comment by alexed1** [comment]
There was a documentation error. The correct syntax is now available at https://unofficialsf.com/list-actions-for-flow/  Are you seeing the old syntax anywhere else? 

Really sorry about wasting your time because of a stupid documentation mistake.

**Comment by chrispphillips** [comment]
Hey Alex. I posted this on the unofficial SF site but figured I'd add it here also.

If you could expand the documentation to call out these things I think that would help people who use it going forward.

1. It does not work on picklist fields
2. If some of the records in your collection have a blank value for the field you’re sorting on, it will sort the blank ones first no matter which direction you sort
3. The sorting priority is reversed from what I would have thought. It sorts first on the last key pair and then works backwards to the first.
4. Use DESC not Descending

**Comment by hayeswise** [comment]
@chrispphillips SortCollection has been updated.  I've also submitted an additional pull request providing 100% test coverage.  See pull requests #360 and #394.
Regarding 1: Picklists are now supported; they sort by API Name and not picklist order.  Null/empty values.
Regarding 2: Null/empty SObject field values are considered smaller than non-null/non-empty values. 
Regarding 4: I noticed that that DESC is explicitly tested for and anything else is considered ascending.

**Comment by chrispphillips** [comment]
@hayeswise 

Regarding 2, that makes sense and I would expect that if you were sorting ascending then null/empty values would show first but if you were sorting descending then I would expect null/empty values would come last.

My testing showed however that null/empty were displayed first no matter which direction you sorted.
