### ISSUE TITLE
Child Lookup show all values instead of filter out with parent value when parent lookup is not selected.

### ISSUE THREAD

**Issue by pawanpatel85** [alexed1/LightningFlowComponents#315]
So I have used Parent lookup on Account Object.
![image](https://user-images.githubusercontent.com/45493653/78599541-55619800-781f-11ea-9fb6-298d070e0080.png)
![image](https://user-images.githubusercontent.com/45493653/78599598-6ca08580-781f-11ea-9e7f-81ff04d403fe.png)

And below is child lookup on Account Object as well but ParentId would be {!InstituteIdVariable} which we got from above lookup.

![image](https://user-images.githubusercontent.com/45493653/78599900-ee90ae80-781f-11ea-8c9b-c9ff2a73a5a0.png)

![image](https://user-images.githubusercontent.com/45493653/78599941-ffd9bb00-781f-11ea-95f3-c378e8c25afa.png)

Child lookup show all accounts in list until I select parent account, once I select parent account from Parent Lookup, Child lookup show only related child account.

**Comment by ericrsmith35** [comment]
What you are describing is exactly what the component is designed to do.  The value selected in the Parent component is what is used to filter the available selections in the Child component.

**Comment by pawanpatel85** [comment]
Thank you so much @ericrsmith35 for this wonderful component. I understood totally that component is doing exactly what it supposed to do however I wast thinking if is there way I can limit child lookup to show records until I select parent record first?

**Comment by ericrsmith35** [comment]
Any value selected in a Child component will be cleared when the Parent
value changes.

I haven't experimented with conditional visibility on a Child component,
but that is something you could try.

**Comment by dmhoffritz** [comment]
@ericrsmith35 - Do you happen to have any additional documentation explaining how to set up the Parent/Child component relationships? I tried adding two Quick Lookup components: Account (Parent) and Contact (Child) with the necessary component settings and cannot get the Contacts to filter on the same flow screen. 

Note: I have 3 Quick Lookup components on the same flow screen, all three have different Component IDs. 

**Account:**
![Screen Shot 2022-10-10 at 3 06 16 PM](https://user-images.githubusercontent.com/69207145/194944420-bb1724c0-b6da-4c88-82b2-9d1f1d491e09.png)
![Screen Shot 2022-10-10 at 3 06 29 PM](https://user-images.githubusercontent.com/69207145/194944431-c8abc03a-438e-4608-8d7d-76385c16a33d.png)

**Contact**
![Screen Shot 2022-10-10 at 3 07 22 PM](https://user-images.githubusercontent.com/69207145/194944470-21c9fcd8-76b9-4e46-ad06-87ce79c8d065.png)
![Screen Shot 2022-10-10 at 3 07 33 PM](https://user-images.githubusercontent.com/69207145/194944483-327394b4-7a99-42d0-8b84-6fbb0a5067d9.png)

Thank you for your help in advance!
-Derek

**Comment by AndyHaas** [comment]
@dmhoffritz 
In the Child Component, you need to fill out the Parent Id Field with the component Id from the parent. In this case, it would be 2. 

Let me know if that works for you.

**Comment by ericrsmith35** [comment]
@AndyHaas is correct.  The Child component needs to reference the Parent component Id.  You can even have Grandchild components using this method.

**Comment by dmhoffritz** [comment]
@AndyHaas @ericrsmith35 That worked beautifully. Thank you, gentlemen!
