### ISSUE TITLE
Set attributes of Task created from saveAsActivity (sendHTMLEmail)

### ISSUE THREAD

**Issue by ChrisFromAlaska** [alexed1/LightningFlowComponents#316]
When sending a templated email, and enabling saveAsActivity, a completed task is created against the Related Record ID.   Would be great to set the variouse fileds on the completed task which is created? Currently, the task is created against the RelatedRocordID with the following fields/values: Sent Email: “null”, Subject: “Send Email: null”, Name: “”.

I would like to capture the template name and perhaps capture some additional values within completed task including setting custom task fields.  

Jack Pond reproduced the current behavior and requested this issue to be created.

**Comment by jdpond** [comment]
This is because, when using a template, by default, no subject is specified because it will override the template subject.  Looking into fixing this by querying the template and putting in the subject line.  TBD - Merging fields in Subject for task.  Probable phase I, won't

**Comment by jdpond** [comment]
Development Done will be in release 1.33.1
Also added ActivityDate=Date.Today();
Updating documentation and adding tests.
