### ISSUE TITLE
Datatable - LWC Issue - [PromiseRejection: [object Object]]

### ISSUE THREAD

**Issue by pcarass** [alexed1/LightningFlowComponents#321]
Hey @ericrsmith35 ,
Just giving the new LWC version of the datatable a test run. Simple enough flow, grabbing all my open opportunities, displaying them on a screen, selecting a few of them, then looping through each selected OppId to retrieve their OpportunityLineitems and displaying them on another screen:

![Screen Shot 2020-04-12 at 23 02 15](https://user-images.githubusercontent.com/17454963/79081042-b0a8f400-7d11-11ea-906c-0e5c697a7d77.png)

The First screen works perfect. I didn't have to trouble shoot it at all. Was very easy to configure .

The Opp Line items though seems to be giving some trouble.
The loop is retrieving their line items no problem and storing them in a manual collection variable, but seems to have trouble displaying them:

![Screen Shot 2020-04-12 at 22 59 27](https://user-images.githubusercontent.com/17454963/79081073-f4036280-7d11-11ea-92d4-811c77659ef0.png)

The debug log i showing that the loop is working correctly (Grabbing one of the IDs from the collections and retrieving the matching Opp Line Items):
![Screen Shot 2020-04-12 at 23 06 59](https://user-images.githubusercontent.com/17454963/79081135-7ab83f80-7d12-11ea-9620-dd8d4f401042.png)

Here's how the LWC is configured:
![Screen Shot 2020-04-12 at 23 05 25](https://user-images.githubusercontent.com/17454963/79081097-2b720f00-7d12-11ea-9582-1969a40808b0.png)

Have you seen this error before: This page has an error. You might just need to refresh it. [PromiseRejection: [object Object]]

Cheers
Paul

**Comment by ericrsmith35** [comment]
The Product ID is not supported as a Lookup value for OpportunityLineItem.
I use a formula field in my OpportunityLineItem record for Product Name (
PricebookEntry.Product2.Name )   .

Eric

**Comment by pcarass** [comment]
Cheers @ericrsmith35 . I was lying in bed this morning, pondering about the Product2ID and then I saw the update from you 😄 
Thankfully I already have that Product Name Formula built for other purposes 😃 
![Screen Shot 2020-04-13 at 11 59 54](https://user-images.githubusercontent.com/17454963/79115717-7de91500-7d7e-11ea-9c61-e850b50031ec.png)
