### ISSUE TITLE
MockHttpResponseGenerator prevents Quick Choice from being deployed

### ISSUE THREAD

**Issue by congmingwudi** [alexed1/LightningFlowComponents#323]
Can you rename MockHttpResponseGenerator.cls to be specific to the Quick Choice component? This name is used unfortunately in other managed packages likely because people are following the trailhead module around writing the apex mock response class, and this prevents the Quick Choice component from being deployed into orgs w/ conflicting existing classes.

**Comment by ericrsmith35** [comment]
Ryan,

One workaround would be to install the package in a sandbox that does not
have any managed packages installed and then use a Change Set to install it
into your target org.

Eric

**Comment by alexed1** [comment]
I'll put this on the list of things to change when we rev this component

**Comment by alexed1** [comment]
Fixed in v1.3 at https://unofficialsf.com/quick-choice-v1-3-new-outputs-a-test-class-fix/
