### ISSUE TITLE
Quick Choice FSC: Multiple components interfere with each other

### ISSUE THREAD

**Issue by clifford-fra** [alexed1/LightningFlowComponents#328]
Hi guys,

if you add two quickChoice components to one screen in Card mode, then the components behave strangely. The blue border of the selected value will only be rendered on one component. In the example below, i have first chosen 123 and afterwards Option 01.

The outputted value of both components work, so it's just a rendering/display issue. The question is, how can this even happen?

edit: It's not related to displaying the default value in the renderedCallback function. I removed the code and the components still won't work properly together.

![qc1](https://user-images.githubusercontent.com/55443386/79434484-c0089580-7fce-11ea-8750-344a98f0816d.png)

**Comment by alexed1** [comment]
this kind of interaction usually means the events generated by the components are getting intermingled, and it's usually straightforward to solve by adding a unique ID to each component and then passing that id around with any events that bubble up beyond the component. @ericrsmith35

**Comment by ericrsmith35** [comment]
Was this update made in the recent code you just pulled for the component?

Eric

**Comment by clifford-fra** [comment]
Seems like a different update, but I can't really figure out what happens in detail.

Looks like the update affects the picklist input mode by adding all values, all labels and the label of the selected picklist value to the components' output api.

**Comment by alexed1** [comment]
A developer I collaborate with said that he thought the reported idiosyncrancies might have to do with the use of CSS instead of javascript in certain areas....

**Comment by clifford-fra** [comment]
I copied the code of the SLDS visual picker from here:
https://www.lightningdesignsystem.com/components/visual-picker/#Base-3

Inserted it into the Lightning Playground and duplicated the code to simulate a second visual picker (of course changed the IDs).

Result: Same behavior, same problem. So the guilty ones are the Visual Picker styles in the SLDS.

**Comment by ericrsmith35** [comment]
This has been fixed
