### ISSUE TITLE
ExecuteSOQL Error - Error Occurred: An Apex error occurred: System.StringException: No match found

### ISSUE THREAD

**Issue by adwhite75** [alexed1/LightningFlowComponents#344]
In the newest version the Action seems to fail if you pass in a relationship query into the WHERE clause. This query worked for me in 1.0, but fails in 1.2.

Error Occurred: An Apex error occurred: System.StringException: No match found

Fieldnames/object names obfuscated:

`SELECT Id, Name,Status_DD__c,Region__c
FROM Object2__c
WHERE Status_DD__c in ('Option 1','Option 2','Option 3') 
	and id not in 
		(SELECT Id 
		 FROM Object1__c 
		 WHERE Contact__c = '{!recordId}')
	and Field1__r.Parent_Reporting_ID__c = '{!Get_Selected_Company_Details.Ultimate_Parent_Reporting_ID__c}'`

When I take out the 'And id not in' piece, it runs.

@alexed1

**Comment by adwhite75** [comment]
The last working version that supported this query was back on Feb 23rd

**Comment by adwhite75** [comment]
I tried cleaning up the 'text template' containing the query string (it's plain text, btw) so that it's a single line with no extra spaces then I got this error:

Error Occurred: An Apex error occurred: System.ListException: List index out of bounds: -1

**Comment by sillyrags** [comment]
The regexes added in this [commit](https://github.com/alexed1/LightningFlowComponents/commit/fb53c9c8948abfbc87879423aba06c5eb2358ed0) to parse the soul query do not properly evaluate queries with embedded relationship queries. I'm submitting a PR to recursively search through any nested queries, as well as fixing other issues I noticed around formatting:
- time formatting was broken and new lines, carriage returns
- tabs need to be parsed out of the query string is coming from a text template in flow
- fix original provided unit suite

**Comment by sillyrags** [comment]
https://github.com/alexed1/LightningFlowComponents/pull/347

**Comment by adwhite75** [comment]
This is now closed and done with the latest versions.
