### ISSUE TITLE
GetPicklistValues always has validation errors

### ISSUE THREAD

**Issue by liamlevesque** [alexed1/LightningFlowComponents#345]
Hey - I'm trying to use the getpicklistvalues action in my flow and every time I get a validation error when I run the flow. 

Here's the configuration: 
![image](https://user-images.githubusercontent.com/5396784/80547550-5cd31780-896d-11ea-94fc-791476bef2f8.png)

And here is that field definition with it's values:
![Screen Shot 2020-04-28 at 4 30 37 PM](https://user-images.githubusercontent.com/5396784/80547706-c05d4500-896d-11ea-965f-eedc1eb72995.png)

And here is the error:
![Screen Shot 2020-04-28 at 4 33 18 PM](https://user-images.githubusercontent.com/5396784/80547804-ff8b9600-896d-11ea-98a6-59f4e2d83c98.png)

Am I missing something?

BTW - thank you so much for all of your components - such a huge help!!!

**Comment by alexed1** [comment]
do you happen to have this in an org that you can provide credentials to via email?

**Comment by Garywoo** [comment]
I'm also experiencing this error now. The action was initially working fine while I was developing the flow. I worked on the flow a little more (without changing anything about this action), and I now get the same '_has validation errors_' message when debugging.

**Comment by Garywoo** [comment]
I was able to resolve the error, but I'm not 100% sure how. 

I first tried reinstalling the package, however then when I was re-saving the flow, I noticed I had an invalid variable defined in one of the Quick Choice FSC component properties. I had a warning message telling me the variables type did not match the requirement. I resolved that, then I was no longer getting the validation error.
