### ISSUE TITLE
sendHTMLEmail - Address bulkification consistent with Apex Gov Limits

### ISSUE THREAD

**Issue by jdpond** [alexed1/LightningFlowComponents#351]
sendHTMLEmail uses both the sendEmail and SingleEmailMessage method. Enhance to bulkify effectively to achieve the 10x10 maximum allowed under [Apex Governor Limits](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_gov_limits.htm)

Per-Transaction Apex Limits
Total number of sendEmail methods allowed 10
Per-Transaction Certified Managed Package Limits
Total number of sendEmail methods allowed 110

- The single and mass email limits don't take unique addresses into account. For example, if you have johndoe@example.com in your email 10 times, that counts as 10 against the limit.
- You can send an unlimited amount of email to your org’s internal users, which includes portal users.
- You can send mass emails only to contacts, person accounts, leads, and your org’s internal users.
- In Developer Edition orgs and orgs evaluating Salesforce during a trial period, you can send mass email to no more than 10 external email addresses per day. This lower limit doesn’t apply if your org was created before the Winter ’12 release and already had mass email enabled with a higher limit. Additionally, your org can send single emails to a maximum of 15 email addresses per day.

**Comment by jdpond** [comment]
@alexed1 In bulkification, any given message may fail.  What would you think if we eliminate (generally) the use of the "throw new InvocableActionException" and expect the flow user to check Response.isSuccess.  This would allow (for example) 5 of 7 to sent and provide for consistent handling of errors.

**Comment by alexed1** [comment]
sounds like a good idea

**Comment by jdpond** [comment]
OK, will do.  I've done the bulkification - sorry about yesterday afternoon's brain snarl.  I'm going to also add a condition to "throw new InvocableActionException" if all sends fail with the first failure message.

**Comment by jdpond** [comment]
Added the bulkification - works as follows:
1) All requests are mapped for responses in serial order (e.g., if there are 5 requests, map of 1-5 responses created) using a new private class that includes the response and various information that may also be needed for post send processing (e.g., activity information such as toAddresses)
2) If a request has an error in one of the error checks, it is noted in the mapped, but not included in the  sendemail collection
3) Upon response, SendEmailResult is mapped back to the responses maps.
4) For successful sends, activity tasks are created if requested through parameters
5) If an error occurs in task activity creation, it is recorded in the error message, but isSuccess remains true
6) Response list is created from mapped requests
7) If no successful sends, throws an InvocableActionException with the error message from the first unsuccessful request
8) Returns list of responses

**Comment by jdpond** [comment]
Did NOT attempt to match and prevent limit issues. You can only use 10 "External" emails per invocation of SendEmail and 10 total.   The logic for determination of whether internal/external would just be too complex and would have to be updated every time SF Governor Limits are adjusted.  Simply too much effort to address at this time.
