### ISSUE TITLE
action icons not displaying correctly

### ISSUE THREAD

**Issue by fosternow** [alexed1/LightningFlowComponents#366]
SLDS action icons are cut off when used in the Visual Text Box display mode.

![2020-05-18_16-08-33](https://user-images.githubusercontent.com/16104497/82267660-dda88200-9921-11ea-81f6-ece7f2fa7073.png)

Seems to affect action icons. All other SLDS icon types display correctly.

**Comment by ericrsmith35** [comment]
If you are using version 1.4 of the component, you can edit the quickChoiceFSC.html file to correct this issue.

Comment out Line 66 like this:


Uncomment out Lines 67-70 like this:
<span class="slds-icon_container">
    <lightning-icon icon-name={item.icon} size={iconSize}>
    </lightning-icon>
</span>

**Comment by fosternow** [comment]
Thanks Alex. I'll try the recommended update.

**Comment by fosternow** [comment]
Sorry, thanks Eric. My apologies for the mix up.
