### ISSUE TITLE
Trying to get the Selected records in a record Collection v/ble 

### ISSUE THREAD

**Issue by risoco10** [alexed1/LightningFlowComponents#375]
Hi Eric,

I have a flow using your tool that display a list of records. I'm using Single Row Selection (Radio Buttons) to grab only one record.

I'm using the output parameter "Output Selected Rows" and I specified a record collection variable. However when I debug my process the output of the output v/ble is null.  Is there something that I'm missing here? Thanks for any help you can provide.
[DEBUG RESULTS.docx](https://github.com/alexed1/LightningFlowComponents/files/4714855/DEBUG.RESULTS.docx)

**Comment by risoco10** [comment]
Having issues mapping the Record collection output of the datatable and assign it to my Flow Variable. Is there any know issue?

**Comment by rowanlean** [comment]
Hi Eric, I also just started having this issue as of yesterday when my sandbox was updated to Summer'20. Using the LWC Datatable (not the latest version, in my case it is datatable_Contact_V1.0), all of my existing flows using this successfully just started not working, and debugging displays null value for output just as @risoco10 mentions.

**Comment by risoco10** [comment]
Is there anyone out there that is facing this issue? I've been trying several options without any success. I would really appreciate if anyone can help.

**Comment by ericrsmith35** [comment]
I will be posting a new version 2 this week that is designed to work directly with Summer 20 orgs.

**Comment by rowanlean** [comment]
> Is there anyone out there that is facing this issue? I've been trying several options without any success. I would really appreciate if anyone can help.

Really just looks like there is no option here but to use the Summer'20 version that allows a single component that can reference any SObject. This of course means that you can't use this in production until Summer'20

**Comment by risoco10** [comment]
Eric, I'm not in Summer 20. Is there any known issue on that? receiving the Record Selection Collection property empty?

**Comment by ericrsmith35** [comment]
The new version that I am releasing will allow you to comment out the
Summer 20 specific code and use the Object specific code.

**Comment by ericrsmith35** [comment]
Try installing this temporary version
https://test.salesforce.com/packaging/installPackage.apexp?p0=04t6C000000Hrzg&isdtp=p1

**Comment by risoco10** [comment]
Eric.. so if I moved to summer20 (which I will do soon) we will be able to get the Results of the records selected in the Record Collection?

**Comment by ericrsmith35** [comment]
yes

**Comment by ericrsmith35** [comment]
You can try this temporary version in your sandbox
https://test.salesforce.com/packaging/installPackage.apexp?p0=04t6C000000Hrzg&isdtp=p1

**Comment by risoco10** [comment]
Eric, With this Beta version do we need to specify the object name in the XML metada file we need to work with? Having issues accepting the input data collection. Does not show up any available v/ble.

**Comment by ericrsmith35** [comment]
Yes, Pre-Summer '20 requires the Object be specified in the source code.

**Comment by risoco10** [comment]
Can you provide an example of the XML as well as the input and output parameter of the Screen's flow? Really appreciate your help on this. Trying to use it for the first time.

**Comment by ericrsmith35** [comment]
What Object are you trying to display records for?

**Comment by risoco10** [comment]
It is a custom object named EmployeeStore__c.. I got a bit confuse on what part to change the name...

**Comment by risoco10** [comment]
Thanks Eric. I was able to fix the issue.

**Comment by ericrsmith35** [comment]
That's great!  Glad to see you have it working.

**Comment by risoco10** [comment]
For others interested. I just changed the 4 lines with the Custom object name (as recommended in previous version) and use _Datatable record Collection Parameter in the Screen Step with a collection that map the custom object.

**Comment by Jnew21** [comment]
@ericrsmith35 I tried to install the temporary version in a sandbox that is currently on summer 20' because we are having the same issue with the output collection variable being null.  I had to rename the two apex classes and the LWC component bundle in order to install the version you provided.  I was able to successfully install the new version, but I only see datatablelwcfsc as a component I can add to the flow.  Once I add that component I do not see the ability to define which object.  I am trying to replace the prior version LWC datatable with your new release.  Please see screenshot below and let me know what I might be doing wrong or missing.  Thank you very much.
![LWCDatatable](https://user-images.githubusercontent.com/61887157/83593266-56b2f680-a52a-11ea-9fc1-e23bc6ef307d.jpg)

**Comment by ericrsmith35** [comment]
You can edit the label that is displayed in the Screen Components list and
you must set the name of your SObject in 4 places in the
datatableLwcFsc.js-meta.xml file.

[image: image.png]
