### ISSUE TITLE
Add color and label to inputRichTextFSC

### ISSUE THREAD

**Issue by jdayment** [alexed1/LightningFlowComponents#376]
I'm new but tried to do a pull request and said I had to have a commit first. I updated the inputRichTextFSC in my org to have a label as well as allow to change text color. Just wanted to share my changes.

**Comment by alexed1** [comment]
Welcome to the project. We'd love to have your pull request. The pull request system is based on git. There's a learning curve involved where you learn how to make commits, push them from your local repository to your github repository, and then use them to create a pull request. If you haven't already, I always recommend starting with https://git-scm.com/book/en/v2 and going up to section 3.5 (the stuff after that is advanced and isn't necessary). you can also do tutorials on github itself.

**Comment by jdayment** [comment]
Awesome I read through tested the Pull Request docs in my own GitHub account. I think I understand it all.
