### ISSUE TITLE
Summer '18 Lookup Issue

### ISSUE THREAD

**Issue by sfdc-luke** [alexed1/LightningFlowComponents#38]
Hi, 

I've installed the lookup component into a sandbox environment (Lightning and My Domain enabled), configured in a visual flow, and added this flow to a Lightning App page, however when I access the page the flow runs correctly, displaying the Lookup component, however I'm receiving the following component errors when attempting to use the lookup:

Uncaught Action failed: flowcomponents:LightningLookup$controller$hover [$ is not defined]
Uncaught Action failed: flowcomponents:LightningLookup$controller$highlight [$ is not defined]

When inspecting the page I can see the jQuery script is not loading from the static resource:
Failed to load resource: the server responded with a status of 404 (Not Found): /resource/jQuery_LookupCmp/jQuery1_11_2.js

Is this a known issue at all, possibly with My Domain enabled environments? 

Thanks.

**Comment by sfdc-luke** [comment]
Ah sorry, blonde moment, My Domain is required for Lightning components! Any other ideas why this would be occurring?

**Comment by sfdc-luke** [comment]
Hi there,

I've downloaded the source into a dev environment and commented the line:
`<ltng:require scripts="/resource/jQuery_LookupCmp/jQuery1_11_2.js"/>`
in the main controller LightningLookup.cmp and uncommented the line:
`<ltng:require scripts="{!$Resource.jQuery_LookupCmp + '/jQuery1_11_2.js'}"/>`

This now loads the jQuery library correctly from the static resource.

Not sure why this line was used in place of the commented line, as {!$Resource.Static_Resource} is the usual method for referencing static resources?

Regards, Luke

**Comment by spilzer** [comment]
I am also experiencing this error even after updating to the latest published package (from June 11). I'm relatively new to Apex and Lightning Components so I'm not sure how to go in an modify the code to get the correct line working. More specific instructions for a fix would be much appreciated if possible. Thanks!

**Comment by sfdc-luke** [comment]
Hi @spilzer, I've just noticed this has already been reported in the closed issue #28. From what I've read, this should be fixed in a new version of the managed package soon.

**Comment by alexed1** [comment]
I think the latest cause of the problem may be that when we made it a managed package it applied a namespace to the jquery staticresource, changing its name. However the code was looking for the old name.

I've created a new version with an unmanaged package at https://login.salesforce.com/packaging/installPackage.apexp?p0=04tB00000006Gl1

Try it and let me know if it solves the problems. I recommend that you first uninstall the old one if you have it installed.

**Comment by sfdc-luke** [comment]
Hi @alexed1,

Thanks for this. I uninstalled the previous managed package and install this version, however the problem persists. I opened up the LightningLookup component in dev console and commented out line 18, replacing this with:
`<ltng:require scripts="{!$Resource.jQuery_LookupCmp + '/jQuery1_11_2.js'}"/>`
and this once again did the trick.

Regards, Luke

**Comment by spilzer** [comment]
The newest package seems to have finally fixed the problem for me. Thank you, @alexed1, for your dogged efforts to get it working! It's a really handy tool and I'm glad to have it available in my flows.

**Comment by alexed1** [comment]
The latest version, published today, eliminates the need to tinker with that require line.
