### ISSUE TITLE
GetLayoutFields Returns 'Index out of Bounds'

### ISSUE THREAD

**Issue by adwhite75** [alexed1/LightningFlowComponents#381]
It looks like the GetLayoutFields action just doesnt work - I pass in the correct layout name (without underscores) and the object name it seems to refuse to work.

**Comment by adwhite75** [comment]
For what it's worth I'm 99% sure it was a recent commit that broke this - I loaded up code before the 'exclude fields' action and it worked fine.

**Comment by alexed1** [comment]
@aleksandarbasic can you take a look at this?

**Comment by aleksandarbasic** [comment]
@adwhite75 I wasn't able to reproduce the issue but I did find an error in the code logic that might fix it. Created a pull request.

Can you you please provide the inputs you are using for the apex action so I can troubleshoot on my end?

**Comment by aleksandarbasic** [comment]
@adwhite75 Fixed the issue in the latest PR. 
workaround for the meantime is set the excludeFields toggle in the apex action to true, but leave blank.

**Comment by alexed1** [comment]
package version 1.24 available at https://unofficialsf.com/get-a-layouts-field-names-flow-action/
