### ISSUE TITLE
ExecuteSOQLQuery - query 'FieldPermissions' object on Summer 20

### ISSUE THREAD

**Issue by danifin** [alexed1/LightningFlowComponents#395]
On summer 20 when try to query 'FieldPermissions' object get an error, the query I use:

SELECT Id, ParentId, Field, PermissionsRead, PermissionsEdit FROM FieldPermissions WHERE SobjectType = 'Opportunity' and parentId IN ( SELECT id FROM permissionset WHERE PermissionSet.Profile.Name = 'System Administrator')

the Error:
Error Occurred: An Apex error occurred: ExecuteSOQL.ExecuteSOQLException: Unable to get sObject Type for name: FieldPermissions WHERE SobjectType = 'Opportunity' and parentId IN ( SELECT id FROM permissionset

this doesn't happen in Spring 20

**Comment by adwhite75** [comment]
I believe this was closed with Gidi re-creating the flow, no?

**Comment by danifin** [comment]
No, we worked on sandbox with the Spring 20 release and everything was fine, but after that, we tried the same on the query on Summer 20 release and started to get this error.
maybe it related to the API version?

**Comment by 96DaveWright** [comment]
I'm having the same issue trying to get a list of products on Winter '21

SELECT 
    Id, Product_Suite__c, Product_Family__c, Name, Capability__c, Requires_CR__c 
FROM 
    Product2 
WHERE 
    Sellable_Product__c = true 
    AND Product_Status__c = 'active' 
    AND Id IN ( SELECT Product2Id FROM PricebookEntry WHERE pricebook2.name LIKE 'airline%') 
ORDER BY
    Product_Suite__c, Product_Family__c, Capability__c

Error:
An Apex error occurred: ExecuteSOQL.ExecuteSOQLException: Unable to get sObject Type for name: Product2 WHERE Sellable_Product__c = true AND Product_Status__c = 'active' AND Id IN ( SELECT Product2Id FROM PricebookEntry

**Comment by adwhite75** [comment]
Hi there - Did you try entering the output of the query in the debug log into the dev console / workbench to confirm it works fine? Is the running user of the flow in system or user context?

**Comment by 96DaveWright** [comment]
> Hi there - Did you try entering the output of the query in the debug log into the dev console / workbench to confirm it works fine? Is the running user of the flow in system or user context?

Query runs fine. I was able to fix this by removing the space at the start of my subquery. So IN (Select ... insteaad of IN ( SELECT

**Comment by adwhite75** [comment]
Nice find Dave!

@danifin please remove that space at the start of your subquery - looks like that should fix it

**Comment by danifin** [comment]
thank you **@96DaveWright** !
it worked
