### ISSUE TITLE
GenerateCollectionReport only has 50% test coverage

### ISSUE THREAD

**Issue by solo-1234** [alexed1/LightningFlowComponents#403]
I recently updated to the newest version and I see that the GenerateCollectionReport class only has 50% coverage. Specifically, the generateCellFromFieldName and generateTableMode methods have zero coverage. Is that something that can be fixed?

Thank you!

**Comment by alexed1** [comment]
It's a good idea. I doubt I'm going to have time to get to it myself though. Any volunteers?

**Comment by adwhite75** [comment]
@solo-1234  is this something you can contribute? :)

**Comment by solo-1234** [comment]
I opened it up and ran all tests to see what it would entail (and if it would be over my head) and with the latest version, it looks like it's at 91% coverage. So I guess someone else took care of it :)
