### ISSUE TITLE
radio buttons both become selected

### ISSUE THREAD

**Issue by forcethesales** [alexed1/LightningFlowComponents#41]
Hi! I'm building dynamic questions in flow and have hit a snag. Thanks!
![yes or no](https://user-images.githubusercontent.com/22670460/41442204-e569a12a-6fea-11e8-8a90-57f64efa276b.gif)

**Comment by alexed1** [comment]
I haven't had a chance to take a look at this yet...if you want to share your credentials with me at aedelstein@salesforce.com I'll try to take a look
