### ISSUE TITLE
LookupFSC: Namespace mismatch for managed package?

### ISSUE THREAD

**Issue by karenzelevinsky** [alexed1/LightningFlowComponents#415]
I have the "LookupComponentFSC" managed package version 1.4 installed on 8/14/2018. I wanted to upgrade it, but when I tried to upgrade to version 2.2, it instead added a new LookupFSC component rather than upgrading my existing one. I believe that's because the namespace from the version I have is "flowcomponents" and is version 2.2 the namespace seems to be "mp35". Can anyone help me understand this? What is the right upgrade path now, given that my org is using this component extensively and don't want to have to rebuild a whole bunch of lookups. Thanks for any guidance! 

![image](https://user-images.githubusercontent.com/20665822/87610945-c218e800-c6d4-11ea-8113-5523f79d6d1a.png)

**Comment by ericrsmith35** [comment]
If your existing Flows are working ok with the older version, you should probably leave those alone.  For new Flows, it would be ok to start using the newer version.  If you can, install the unmanaged package and use that.  If not, just use the newer LookupFSC.

@alexed1 [This post](https://unofficialsf.com/lookup/) mentions a Summer '20 version but there is no link.  ALso, do you know what org hosted the managed V2.2?

**Comment by karenzelevinsky** [comment]
@ericrsmith35 Thanks! A concern I have with having both packages installed is that then two LookupFSC components show up and they seem to look the same, so it would be hard to know which one you are choosing.

**Comment by karenzelevinsky** [comment]
@alexed1 Hi Alex, Hoping you'll be able to chime in on this question. Thanks!

**Comment by EdRedSled** [comment]
Following (same challenge, two LookupFSC Elements old/new).   Recently we noted (in Sandbox, pre Winter 21) that the filter functionality was not working, so we too downloaded the latest version, but getting the same result (filter not working).  I will open a ticket for that as well.
