### ISSUE TITLE
RichTextInputFSC: component requires existing / placeholder text in the value

### ISSUE THREAD

**Issue by davidchengIC** [alexed1/LightningFlowComponents#417]
The component only works if there is existing text in the value’s variable. If the variable starts as blank, then the resulting output is also blank, even if the user inputs text.

Is there any fix for this? We don’t want to display any existing or placeholder text for the user.

**Comment by alexed1** [comment]
try the latest version 1.3 https://unofficialsf.com/nick-sauer-adds-smart-word-processing-features-to-rich-text-input/
