### ISSUE TITLE
Default value in lookup field

### ISSUE THREAD

**Issue by cgerth** [alexed1/LightningFlowComponents#42]
Is it possible to specify a default value (variable) to display in the flow component field when the flow runs? If not, I'd like to request it. Perhaps an additional input attribute.

My use case is that my flow displays a form to update fields on a record (and do other things). I'd like the updater to be able to see values already in the field on the record if they exist (provided by prior lookup).

And thank you hugely for fixing the jQuery issue. It was really appreciated. I LOVE this component.

**Comment by ericrsmith35** [comment]
I will see what I can do when I get a chance.

**Comment by ericrsmith35** [comment]
I have submitted a pull request with these changes added.

**Comment by ericrsmith35** [comment]
@cgerth This is now included in the current version of the component.
