### ISSUE TITLE
QuickChoce FSC - Custom Image Help

### ISSUE THREAD

**Issue by pcarass** [alexed1/LightningFlowComponents#430]
Hey @ericrsmith35 
I have added some custom .jpgs to the Quick Choice Images static resource and replaced the file. But I am struggling to reference them in V2.0.
I’m not seeing any options to reference them.
I use a text string collection variable and add the filename.extension (gate.jpg) as it appears in the static resource and then used this in the Icons Collection thinking it would pick up on them, but no luck.
Where am i going wrong with this?
Thanks,
Paul

**Comment by ericrsmith35** [comment]
Did you try the instructions found [here](https://unofficialsf.com/ersquickswitchapp-instructions/) for creating the Static Resource Zip File?

**Comment by pcarass** [comment]
Hey @ericrsmith35 Thanks for coming back so quickly.
I have yes. I have updated the images in the zip folder and replaced it back into the static resource. But I can't figure out how this applies to the Visual Cards element of the QuickChoice FSC.
![screenshot-sensys--c visualforce com-2020 07 31-15_16_23](https://user-images.githubusercontent.com/17454963/89044494-f4b41900-d341-11ea-88f8-1e7662712bf4.png)

![screenshot-sensys lightning force com-2020 07 31-15_17_28](https://user-images.githubusercontent.com/17454963/89044503-f7167300-d341-11ea-81c1-f2c172d4975e.png)

It could just be Friday evening blues getting to me here! haha

**Comment by ericrsmith35** [comment]
send me your Zip File and I'll take a look later. (ericrsmith35@gmail.com)

**Comment by pcarass** [comment]
Thanks @ericrsmith35 
There's the zip I'm using;
[Quickchoice_Images.zip](https://github.com/alexed1/LightningFlowComponents/files/5007509/Quickchoice_Images.zip)

No panic on it. I'm extremely grateful for any help I can get.

**Comment by ericrsmith35** [comment]
Quickchoice_Images folder should be at the top level
