### ISSUE TITLE
QuickChoice FSC 2.1 text collection variables not recognized by object fields

### ISSUE THREAD

**Issue by Zyxil** [alexed1/LightningFlowComponents#433]
Despite having multiple text collection variables in the flow, the object picker does not recognize that any exist. And when I enter the correct name of a text collection var, the control still complains that a valid one is not set:

> qcChoices (Screen Component) – The input parameter “Choice Values (String Collection)” can accept multiple values, so the assigned value must be a flow variable with the isCollection property set to true.

![image](https://user-images.githubusercontent.com/974997/89245105-19282380-d5d6-11ea-8f5f-17df79d55450.png)

**Comment by ericrsmith35** [comment]
@alexed1 This seems similar to one of the dualListBox issues.

**Comment by alexed1** [comment]
This is a bug that's fixed in Flow Base Components 1.2.3. Just install it over what's there now. https://unofficialsf.com/introducing-flowbasecomponents/
