### ISSUE TITLE
Mass Email Bug

### ISSUE THREAD

**Issue by shasta824-deli** [alexed1/LightningFlowComponents#449]
The setTargetObjectIds section of the mass send code had an error when setting the whatIds.  It was resetting the targetobjectIds to the whatId list.  This was on line 119 of SendHTMLEmail version I got from the 1.33.2 version.

Sorry I am not sure how to notify or go through GitHub to announce these.  

I really like that you can send mass emails getting around the 10 email limit per call to the single message version.

**Comment by jdpond** [comment]
Could you retry this with https://login.salesforce.com/packaging/installPackage.apexp?p0=04t3h0000045qiMAAQ

**Comment by shasta824-deli** [comment]
Yes.  I am still documenting the other changes I needed to make to allow
for Document Attachments vs content document links.  Then I will uninstall
and give this a try.

Thanks and again I apologize that I do not know my way around GitHub very
well.

**Comment by shasta824-deli** [comment]
I got the same error. "EXCEPTION_THROWN [349]|SendHTMLEmail.InvocableActionException: No Messages were sent.  First Error: Error Code: INVALID_ID_FIELD - Only Users, Contacts, Leads, and Person objects are allowed for targetObjectIds."

Looks like the same line of code(now line 123) is still setting the target object instead of the what ids.

I did like the lightning component interface for the action. However it did not include parameters for attachments.  Which also don't include document attachments instead of just document links.  I added a parameter for this type of attachment.  Not sure if you would be interested in adding that to the code or not.  I had to do it because Salesforce CPQ still builds their Quote documents as the old version document instead of the new lightning files.

**Comment by jdpond** [comment]
This is a problem with Collections in CPE - working on it now

**Comment by jdpond** [comment]
shasta, I just found the problem in the sendHTMLEmailCPE for collections too.  Will release them both in a couple hours.

**Comment by jdpond** [comment]
Fixed in latest pull request - test as soon as the package comes out and we can close.  THANK YOU!
