### ISSUE TITLE
sendBetterEmail - Code refactoring and optimization

### ISSUE THREAD

**Issue by jdpond** [alexed1/LightningFlowComponents#454]
1. Bulkify DML on tasks.
2. Eliminate SOQL Queries in FOR loops with dynamic SOQL and Maps.
3. Simplified logic for error handling and sending Emails. Using the Base Email 
4. Improved Efficiency of the component. 
5. Prettier to the code
6. Split if-then-else into bracketed code
7. Re-examine the test classes
9. Examine wire connects and eliminate unnecessary
10. Split the code into SOC segments

**Comment by alexed1** [comment]
Here's a package candidate 2.0.2 including all of Mohith's changes. Can you guys give it some testing? https://login.salesforce.com/packaging/installPackage.apexp?p0=04tf4000004PuMBAA0
