### ISSUE TITLE
sendBetterEmail - saveAsActivity for sending emails to Leads

### ISSUE THREAD

**Issue by jayomayan** [alexed1/LightningFlowComponents#477]
This might be already reported or even resolved.
I'm using version 1.33.01 and I go this error when sending from Lead.

`Error Occurred: An Apex error occurred: SendHTMLEmail.InvocableActionException: SendEmail failed. First exception on row 0; first error: INVALID_ID_FIELD, WhatId is not available with saveAsActivity for sending emails to Leads.: [whatId, 00Q1V00000w5g8v] `

**Comment by jdpond** [comment]
I just tested this in 2.00.02 and it worked.  Possible explanation, in 1.33.1, saveAsActivity and saveAsTask were conflated.  An error might have occured when trying to saveAsTask.  Will wait to close this until confirmed when using the upcoming package 2.00.02

**Comment by adwhite75** [comment]
@jdpond  can this be closed?
