### ISSUE TITLE
Extract Text From Non-Text Field - link is wrong

### ISSUE THREAD

**Issue by solo-1234** [alexed1/LightningFlowComponents#482]
The Extract Text From Non-Text Field action links to Send Rich Email instead of to the correct page.

**Comment by adwhite75** [comment]
@solo-1234  is this one the main page? Can you provide a link to both?

**Comment by solo-1234** [comment]
Looks like this has been fixed. Thanks for following up!

**Comment by ericrsmith35** [comment]
I fixed this today ;-)
