### ISSUE TITLE
Multiple Selections for Visual Card

### ISSUE THREAD

**Issue by wilsonwong13** [alexed1/LightningFlowComponents#487]
Is anyone else having this bug where you can select multiple visual cards? I have download the latest version for both the quick choice and the base component

![Screen Shot 2020-09-11 at 12 41 05 PM](https://user-images.githubusercontent.com/23243527/92951895-1ae2d380-f42d-11ea-9aa3-ab9975242a41.png)

**Comment by ericrsmith35** [comment]
Wilson,

I install FBC v1.2.6 and quickChoice v2.2 in a new Dev Org and I am not able to reproduce that issue using the sample flow that gets installed with quickChoice.  Can you share how you have the component configured?

Eric Smith

**Comment by wilsonwong13** [comment]
Here is my current setup 
![image](https://user-images.githubusercontent.com/23243527/93007185-df7efc80-f533-11ea-9d1a-742ce78a9800.png)

![image](https://user-images.githubusercontent.com/23243527/93007188-ead22800-f533-11ea-8a99-7b01b99deccb.png)

![image](https://user-images.githubusercontent.com/23243527/93007194-f6bdea00-f533-11ea-8f12-e59b7aff291d.png)

![image](https://user-images.githubusercontent.com/23243527/93007198-01787f00-f534-11ea-80d0-e7d30fcd4faf.png)

**Comment by ericrsmith35** [comment]
Wilson,

For now, add a value to the *Master Label* attribute.  This should get the
component working for you for now why we work on a fix.

Eric Smith

**Comment by ericrsmith35** [comment]
Wilson - v2.3 with a fix should be posted online in the next day or two. -
Eric

**Comment by wilsonwong13** [comment]
Yup, I just tried this out and it works. Thanks Eric for the quick response! Will closed this issue
