### ISSUE TITLE
NavigateButton object action stopped working

### ISSUE THREAD

**Issue by mfraker** [alexed1/LightningFlowComponents#490]
Hi, I love the NavigateButton and it has been working for months and then over the weekend it stopped working for all my users.  It opens flows just fine but it no longer opens abject quick actions.  This is production so I am getting lots of calls so please help.  Thank you.

**Comment by mfraker** [comment]
Some more detail I am using NavigateButton managed package 1.12 installed 4/17/2020

**Comment by ericrsmith35** [comment]
For Quick Actions to work, they still must be available on the Record Page.

**Comment by mfraker** [comment]
Thank you @ericrsmith35 that was it, a team member removed them.
