### ISSUE TITLE
quickChoiceCPE TypeError: e.path is undefined

### ISSUE THREAD

**Issue by AndyHaas** [alexed1/LightningFlowComponents#495]
When I am in a flow and I edit a screen that has a quickChoiceCPE component then click done on the flow builder screen I get the following error.

The only way to get out is to refresh the page which then we lose everything we have done. 

Error:
TypeError: e.path is undefined
throws at https://por--qa.lightning.force.com/auraFW/javascript/2n4GPhmhXMSdrL9aa7sIlA/aura_prod.js line 37 > Function line 8 > eval:4:12607

**Comment by AndyHaas** [comment]
@ericrsmith35 Is this a known issue? I have installed the latest version

**Comment by ericrsmith35** [comment]
I am not aware of this issue.  Maybe @alexed1 has an idea?

**Comment by AndyHaas** [comment]
Video showing the error message.

https://www.loom.com/share/098c3d634fc5429b825f584a92bab12b

**Comment by AndyHaas** [comment]
Further testing just because I was curious if it was my org. I opened a clean dev org installed the latest Flow Base Components and the latest Quickchoice and got the same error happening.

**Comment by AndyHaas** [comment]
@ericrsmith35 and @alexed1 
We are getting the same error on Send Better Email? 

I have also tested in a brand new dev org and got the same error. 

![image](https://user-images.githubusercontent.com/22582720/94474608-8057f380-0193-11eb-81bb-67c13b0e09f7.png)

TypeError: e.path is undefined
throws at https://por.lightning.force.com/auraFW/javascript/7p9HLMpgnV2GO9MqZhXGUw/aura_prod.js line 37 > Function line 8 > eval:4:12599

Any suggestions on what to look at would be much appreciated

**Comment by alexed1** [comment]
If it's showing up when you dispel the property editors for both Send Better Email and Quick Choice, it's a bug in the Custom Property Editor framework. 

are the orgs you're creating Summer 20 or Winter 21?

**Comment by AndyHaas** [comment]
Alex,
We have tested in Winter 21 and Summer 20 and we are getting this error. 

Thanks for letting us know. I was thinking it was something I was doing.

**Comment by AndyHaas** [comment]
@alexed1,
I would assume that this bug will be fixed in Winter '21?

**Comment by alexed1** [comment]
There's a theory that this is browser-specific. What browser are you using? If you are not using Chrome, can you try this using Chrome and let me know if it works or not?

**Comment by AndyHaas** [comment]
Alex,
I am using Firefox as my default browser. This isn't the first browser bug I have run into that the Platform had. Firefox consumes a lot less RAM when you have Salesforce open in 20 tabs. 

I have tested in Chrome this morning and no error. Retested in Firefox and got an error.

**Comment by AndyHaas** [comment]
The issue is that Firefox has an issue with CPE. This is still an issue in Winter '21. But now my main browser for editing flows will be Chrome.
