### ISSUE TITLE
fbc_FormulaEvaluatorTest - Line 61 - Test evaluation should be '19' not '16'

### ISSUE THREAD

**Issue by SDJCorp** [alexed1/LightningFlowComponents#499]
https://github.com/alexed1/LightningFlowComponents/blob/9fc80b515558596d49b8ac93041ef04a7fb710e4/flow_process_components/FlowBaseComponents/force-app/main/default/classes/fbc_FormulaEvaluatorTest.cls#L61

This fails:
`        System.assertEquals('16', fbc_FormulaEvaluator.parseFormula('HOURS(DATETIME(2019,12,26,0,0,0))', stringContext));`

This Passes:
`        System.assertEquals('19', fbc_FormulaEvaluator.parseFormula('HOURS(DATETIME(2019,12,26,0,0,0))', stringContext));`

**Comment by alexed1** [comment]
When I merged in this change the test started failing. Restoring the value to 16 made the test pass again. So, I'm confused. 

Reverting this for now.

**Comment by SDJCorp** [comment]
Weird, maybe because of timezones or something? (the org I am using this on is based in Ireland)

**Comment by alexed1** [comment]
That's a great hypothesis. Let's just comment out that assert for now until someone has time to dig into it.

**Comment by adwhite75** [comment]
Closing this out as we have moved fbc over to a managed package which will alleviate any install/test class coverage issues.
