### ISSUE TITLE
Code Coverage Missing or under 75% for these classes

### ISSUE THREAD

**Issue by SDJCorp** [alexed1/LightningFlowComponents#500]
**As of Version: 1.3.2**
The flowing classes have code coverage under 75%, what test that were present ran successfully, except for parseFormulaTest (opened issue #499 for this):
- fbc_DeployMetadata - 0%
- fbc_FieldDescriptor - 0%
- fbc_GetFieldInformation - 0%
- fbc_HexUtil - 0%
- fbc_Puff - 0%
- fbc_RetrieveMetadata - 0%
- fbc_XmlUtils - 0%
- fbc_Zippex - 0%
- fbc_RegExps - 42%
- fbc_FormulaEvaluator - 51%
- fbc_SearchUtils - 68%

Here is an image of the results:

![fbc (v1 3 2) Code Coverage results](https://user-images.githubusercontent.com/35976436/94933577-92d67380-0498-11eb-8e57-040c9522dd6a.png)

**Comment by SDJCorp** [comment]
As a note, this dropped an org that I installed it into to go from 98% coverage down to 76% -- making it hard to justify putting this into production.

**Comment by ericrsmith35** [comment]
@alexed1 I've created PR #502 to add Test Coverage for fbc_Zippex, fbc_HexUtil and fbc_Puff.  

I think fbc_DeployMetadata, fbc_XmlUtils & fbc_RetrieveMetadata are from your PB to Flow conversion tool.  I don't have any test code for those.
