### ISSUE TITLE
QuickChoiceFSC in flow modal - getting cut at modal end

### ISSUE THREAD

**Issue by raz235** [alexed1/LightningFlowComponents#511]
Hi,

I used the QuickChoiceFSC as picklist inside a flow that overrides the new button of a standard object.
The values that appear are correct and the default value also work as expected but the values of the picklist are making the modal overflow and the user needs to scroll the modal to see the values.

Example:
![QuickChoiceCutOff](https://user-images.githubusercontent.com/16794402/96109181-1061a100-0ee7-11eb-8013-347d7c5d3889.png)

In my opinion you can set the modal to overflow : intial (Aura component needed to override CSS) or set lightning-combobox that show the dropdown to have dropdown-alignment="auto" property so it will not cause the overflow.

Thank you for a great LWC
Hope you can help me fix my issue

Raz

**Comment by ericrsmith35** [comment]
The standard behavior of the lightning-combobox is to respect the attributes of its container.  The modal is scrollable, so the combobox is designed to stay inside of that.

Your best bet is to override the modal container similar to this:
```
.THIS .slds-modal__content{
    overflow: initial;
}
```
