### ISSUE TITLE
The package you're installing depends on package 'FlowBaseComponents', version '1.2'

### ISSUE THREAD

**Issue by dschach** [alexed1/LightningFlowComponents#530]
I want to install Send Better Email, but the link on UnofficialSF tries to install a package that depends on FlowBaseComponents... which apparently have been superseded by Flow Action BasePack and Flow Screen Component Base Pack. 
How do I install the email components (which are in this repository)? Can the code here be updated to depend on the new packages? Or do I have to install the old basepack as well as the new code? I noticed, for example, that TransferMetadata is in the new package, so I doubt I'd need to install the old basepack... except that Send Better Email wants me to.
Thanks!

**Comment by ericrsmith35** [comment]
Until this component is updated, you still need the old Base Pack.  You can install it from here: [1.3.4 Unlocked](https://login.salesforce.com/packaging/installPackage.apexp?p0=04tf4000004PuQrAAK)

**Comment by alexed1** [comment]
The new version of Send Better Email (2.0.4) uses the Base Packs.
