### ISSUE TITLE
Quick Choice Timeout when using a picklist field and Section(Pilot)

### ISSUE THREAD

**Issue by mhosveolia** [alexed1/LightningFlowComponents#531]
**Problem**
I am currently in the Multi-Column Screens in Flow Builder (Pilot).  I am not sure which component the issue is in(Section or Quick Choice).  I am getting timeout errors when I add a Quick Choice to a screen that has a Section(Pilot) on it anywhere.   The screen freezes and no selections can be attempted.

**Expected behavior**
QuickChoice populates with picklist values from selected field and object.

**Reproduction**
In one screen add a section and QuickChoice component using a picklist field lookup.

**Error Messages**

This is not the error message but when I go into the Chrome Developer Tools I see what looks to be an infinite loop of getting the picklist values in fsc_quickChoiceFSC.js:4 
Here is what loops :
displayMode isPicklist
in getter: objectApiName is: customobject__c
in getter: fieldApiName is: customfield__C
satisfied calculatedObjectAndFieldName test
gtPicklistValues returned data

**Comment by KarlLivesey** [comment]
I am also getting this error

**Comment by adwhite75** [comment]
@alexed1  - Potential conflict with multi-column and QuickChoice

**Comment by JodieM** [comment]
I'm having the exact same issue in Spring '21. I have done a video let me know if you want me to email it @alexed1 as I can't link it here as it's from a client's sandbox. 

I thought it was something to do with it being from a field, or something to do with sections being conditionally displayed, but no it seems to be pretty broken whenever it's on a screen with a section.

**Comment by cadillacben** [comment]
+1 @

**Comment by ImagineCRM-vcs** [comment]
Any updates on this issue?

**Comment by rutgergernandt** [comment]
I am encountering the same bug (also in the beta version that is).  

@ericrsmith35 is the author of fsc_quickChoiceFSC. I do not have the time to look into this deeper atm, but is there something in how the events are communicated between the section and the component in the section causing this perhaps?

**Comment by ericrsmith35** [comment]
@alexed1 Any ideas on where to start to see why sections and QuickChoice don't work together?

**Comment by alexed1** [comment]
The important thing is that this was fixed for Summer '21. Sorry I didn't respond earlier on this.

The technical reason is: "A complex attribute value change event from lwc lc wire service method causes infinite loop".
