### ISSUE TITLE
Unable to open Configuration Section window

### ISSUE THREAD

**Issue by CloudTechRaz** [alexed1/LightningFlowComponents#540]
> Do you have the original datatable Aura component installed in that Sandbox?

Would that be an issue? I have the older version installed but cannot open the Configure Sections window
![image](https://user-images.githubusercontent.com/76010050/102130395-7b811280-3e59-11eb-943a-adc2ca5414dc.png)

_Originally posted by @CloudTechRaz in https://github.com/alexed1/LightningFlowComponents/issues/538#issuecomment-744682910_

I kind of hijacked the previous unrelated thread and did not want to mix the two so I opened a new one. Hope it's not a problem.

Good news, I may have found the reason for the described issue and a possible workaround. 

After trying to reproduce the problem on Firefox I encountered a more detailed error message:
![image](https://user-images.githubusercontent.com/76010050/102146906-7d0b0480-3e72-11eb-8bfe-df787eabd144.png)
The explanation suggested this was to prevent clickjacking. Opening the frame in a new tab was successful and it appears it does open in does use a different domain **https://*.visualforce.com/apex/screenFlow**

I went back to **Session Settings** in my org and disabled "_Enable clickjack protection for customer Visualforce pages with headers disabled_" and the frame opened successfully.
![image](https://user-images.githubusercontent.com/76010050/102147928-40d8a380-3e74-11eb-813f-9727212f8b6a.png)

I have to admit I am not exactly sure what this setting does or the implications of disabling it, but it does work for the time being. If you have any alternative suggestion regarding this matter please let me know.

-Raz

**Comment by ericrsmith35** [comment]
That should not be the issue.  Did you mean Configure Columns?

Did you try looking at the Console Log after pressing CTRL-SHIFT-I?

**Comment by CloudTechRaz** [comment]
> That should not be the issue. Did you mean Configure Columns? Did you try looking at the Console Log after pressing CTRL-SHIFT-I?

Sorry for the delayed response. I've updated my original post with additional information which might shed some light on the issue.

-Raz

**Comment by CloudTechRaz** [comment]
Any comments regarding the update I mentioned [above](https://github.com/alexed1/LightningFlowComponents/issues/540#issue-767004113)? Should I be concerned about the relaxed security setting?
![image](https://user-images.githubusercontent.com/76010050/102197369-b7ec5700-3ec9-11eb-8b44-d0837dc799b9.png)

**Comment by ericrsmith35** [comment]
@alexed1 Could this be an issue with the "ScreenFlow" piece of the Datatable LWC?

**Comment by jbatt08** [comment]
FWIW - I've encountered the same issue and temporarily resolved it by disabling the clickjack protection setting.

**Comment by ericrsmith35** [comment]
I've added a note about this behavior to the documentation page @ unofficialsf.com
