### ISSUE TITLE
*Collection Processors* - needs FlowBaseComponents to install, even if you have Flow Actions Base Pack and Flow Screen Components Base Pack

### ISSUE THREAD

**Issue by solo-1234** [alexed1/LightningFlowComponents#545]
### Steps to reproduce

1. Install Flow Actions Base Pack and Flow Screen Components Base Pack. DO NOT Install Flow Base Components.
2. Try installing Collection Processors.
3. You will get an error. 
4. Install Flow Base Components and try again and it works

### Expected behavior
Since the two base packs have replaced Flow Base Components, I would not expect to need it to install Collection Processors

### Actual behavior
But I needed to!

### Screenshots
https://i.imgur.com/Fr8NRW1.png

**Comment by ericrsmith35** [comment]
Many existing older components still use and require the original Flow Base Components. Unless the component you are looking to install specifically states that it requires the Flow Base Packs, you may still need to install the Flow Base Components from the link in the Install section on [this page](https://unofficialsf.com/introducing-flowbasecomponents/).
