### ISSUE TITLE
LookupFSC: Display multiple fields in search results

### ISSUE THREAD

**Issue by JodiNA** [alexed1/LightningFlowComponents#55]
The Lookup FSC is awesome!
Suggestion for improvement:

Add additional display fields to a lookup. This allows a user to distinguish between multiple records that may have the same name (or same whatever value you're searching). 

For example, a name search of contacts might result with:

Joe Shmoe
Joe Shmoe

How do I know which is the one I want?
This would be more helpful:

Joe Shmoe joe@shmoe.com
Jod Shmoe joeisthebest@joeshmoe.com

Thanks!

**Comment by ericrsmith35** [comment]
@JodiNA 
You can use the component as is and still display the values of multiple fields in the lookup.  Just create a formula field that combines two or more fields together and use that for your I2_Display Which Field? parameter.  For example, your formula field could be Name & " " & Email.

**Comment by alexed1** [comment]
I agree it would be nice. Unfortunately it requires surgery to the basic select component, so it's not trivial.
