### ISSUE TITLE
Cannot install datatable 3.0.5

### ISSUE THREAD

**Issue by mikesobczak** [alexed1/LightningFlowComponents#562]
I've installed FlowActionsBasePack v2.12 and FlowScreenComponentsBasePack v2.1.3.  When I attempt to install Datatable 3.0.5, I get the following errors.  I don't see another version of datatable installed in my org.  Any clues on how I can resolve these issues?

(datatable) Can't create lightning component bundle if there is already an aura definition bundle with the same name and namespace. | datatable: Can't create lightning component bundle if there is already an aura definition bundle with the same name and namespace.
-- | --
Cannot find Lightning Component Bundle datatable. | datatable: Cannot find Lightning Component Bundle datatable.
(Datatable_Configuration_Wizard) WizardTable (Screen Component) - We can't find this input attribute: "isConfigMode". | Datatable_Configuration_Wizard: WizardTable (Screen Component) - We can't find this input attribute: "isConfigMode".

**Comment by ericrsmith35** [comment]
Do you have the original Aura version of datatable or some other Aura datatable component installed?

**Comment by mikesobczak** [comment]
Yeah, I think that's it.  I spent some time hunting it down and deleting it.  Trying to install the new version now.

**Comment by mikesobczak** [comment]
Yep, that was the problem.  I'll see about getting that older version removed from our demo template.  Thanks!
