### ISSUE TITLE
DataTable - Maximum Number of Records to Display

### ISSUE THREAD

**Issue by alexandr-yul** [alexed1/LightningFlowComponents#565]
Using v3.0.6, the field [Maximum Number of Records to Display] only allows numeric values.

In v2.x we used to be able to use a variable to specify the maximum. 

Please bring back this functionality.

**Comment by ericrsmith35** [comment]
This has been corrected in the latest release.  v3.0.10  2/27/21
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/
