### ISSUE TITLE
Datatable Error on Colum Config

### ISSUE THREAD

**Issue by fglynn9** [alexed1/LightningFlowComponents#569]
Hey
I am experiencing an error with the latest datatable 3.0.8.
When trying to configure the columns I am met with a wait screen (circling dots) I see from the documentation that this can be rectified by unchecking “Enable clickjack protection for customer Visualforce pages with headers disabled“ I have done this but it still persists so I am not sure if this is related to that problem.
If I close the pop up and open it again I can then access the configuration page which seems to work correctly and I am prompted to close the window which then give the following error#
Uncaught TypeError: Cannot read property 'forEach' of undefined throws at https://......   
And the configuration that was selected does not appear on the settings column leading to a validation error (at least 1 column must be selected) when selecting done.
Is there something I might be doing wrong? I have giving my current profile access to all apex classes as per winter 21 so I’m not sure how to proceed. 
Thanks in advance for the help.
Ps. great work, please don’t think I’m ungrateful for it.

**Comment by ericrsmith35** [comment]
@fglynn9 If you want to email me credentials for the org this is occurring in, I'd be glad to take a look.
pb.oneview@gmail.com

**Comment by fglynn9** [comment]
Issuse was caused by the ueser being in developer mode. Setting found in User Settings - Advanced User Details.
