### ISSUE TITLE
Need correct Installation link for Dependent Picklist

### ISSUE THREAD

**Issue by MarcusFlowMaster** [alexed1/LightningFlowComponents#57]
Hi Alex,

The "Install" link for the Dependent Picklist Component does not work. Can you please update and provide the correct link? I need this for an upcoming deployment. 

Thanks!

**Comment by flyspncr** [comment]
Ditto - It keeps taking me to a defunct youtube page. Thank you!!

**Comment by alexed1** [comment]
fixed. let me know here if the install link gives you further problems.

**Comment by MarcusFlowMaster** [comment]
Thank you Alex!
