### ISSUE TITLE
DataTable (v3) - Input data is Apex-Defined - Settings Not Applied on Return

### ISSUE THREAD

**Issue by jeffolmstead** [alexed1/LightningFlowComponents#573]
On the latest DataTable (v3) which has the dynamic interface (very nice by the way), when you check "Input data is Apex-Defined" then it exposes new options in "Data Source" section as well as the "Column" options under "Advanced". That all works perfectly. However, if you click off the component then return, it does not apply the settings unless you manually uncheck and recheck the "Input data is Apex-Defined":

![image](https://user-images.githubusercontent.com/1848585/104766329-5e7d7f00-5738-11eb-8025-2d37e9dd050f.png)

This is what you would see if you "toggle" it:

![image](https://user-images.githubusercontent.com/1848585/104766403-7f45d480-5738-11eb-8748-7845d65367b1.png)

I haven't looked through the code yet, likely just there is a spot to see if the value is checked on component load to then display properly rather than depending on a click event. If I get to it first, I will let you know!

**Comment by ericrsmith35** [comment]
Thanks for the feedback.  Let me know if you end up tracking this down.

**Comment by ericrsmith35** [comment]
This has been corrected in the latest release.  v3.0.10  2/27/21
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/
