### ISSUE TITLE
*Datatable (V3)* Columns no longer scale automatically to fill component width

### ISSUE THREAD

**Issue by RomanTheCube** [alexed1/LightningFlowComponents#577]
I am not sure if this is intentional or not, however in datatableV2, Adding your columns **without** specifying any column width values would automatically scale the datatable to 100% width, with column headers spaced evenly.

Since Datatable (V3), the same process results in the datatable matching the width of the configuration window:
![image](https://user-images.githubusercontent.com/25043249/105553847-0eb03200-5cbb-11eb-8ced-cd41bcc7aa7c.png)

It would be great to have this working in V3 also.

**Comment by ericrsmith35** [comment]
You can select the Column Attributes Toggle, Clear the Column Widths Setting, and Save to get the behavior you are looking for.

**Comment by RomanTheCube** [comment]
ah so just the default is to set the widths versus the older way. thankyou yet again.
