### ISSUE TITLE
*{!Datatable}* - _({!Datatable})_ - {!Decimal with 0, returning value without 0}

### ISSUE THREAD

**Issue by munawirrahman** [alexed1/LightningFlowComponents#582]
I tried to use datatable with decimal field and the value is: 0,3731428384780884 but when I use it in datatable, the value is converted to : 3.731.428.384.780.884,00 . tried to use special formatting but since the 0, is removed, the formatting is no use

**Comment by munawirrahman** [comment]
my current workarround is: use formula to convert 3.731.428.384.780.884,00 to 0.3731428384780884 (field per 10)

**Comment by munawirrahman** [comment]
my current workarround : convert the comma to dot as a text. and reconvert it again to number

**Comment by ericrsmith35** [comment]
@munawirrahman Does this still occurr with the current version (3.1.1)?

**Comment by munawirrahman** [comment]
@ericrsmith35 just installed the newest version. Somehow the result is not consistent. Some returns with dot, some with comma.

<img width="182" alt="Screen Shot 2021-05-03 at 06 00 14" src="https://user-images.githubusercontent.com/75523812/116830521-02e6dc80-abd5-11eb-95c2-6b6eea360a0c.png">

**Comment by ericrsmith35** [comment]
Those all look consistent.  What are your expected results?

**Comment by munawirrahman** [comment]
The real variable for 8.756.550.550 is 0,8756

I dont know why it works on the 0,913 but doesnt work on the 0,8756

**Comment by ericrsmith35** [comment]
Please confirm the field types and the variable types configurations for
how they are defined.  Number?, Percent?, Number of Decimal Places?
