### ISSUE TITLE
Datatable - LWC - Border setting not retained on initial add to flow

### ISSUE THREAD

**Issue by jkenzer** [alexed1/LightningFlowComponents#583]
I upgraded 4 flows from Datatable v2 to the new v 3.0.9. I'm not sure if this bug exists because I had them both installed concurrently.

### Steps to reproduce

1. Go to a flow screen
2. Add Datatable to the screen
3. Leave the Add border box checked (default)
4. Run flow

### Expected behaviour
Border around the Datatable

### Actual behaviour
No border

### Workaround
1. Uncheck Add border and click done
2. Reopen the screen and check Add border
3. Run flow
4. Border is shown

</details>

**Comment by ericrsmith35** [comment]
That is standard behavior when running from the Flow Builder. The border
works as configured when it is running on a Lightning page.

**Comment by jkenzer** [comment]
Sorry, I realize my steps to reproduce weren't complete enough.

When I first add it to the flow screen and don't alter the Add Border checkbox, and then save and either Run or Debug, there is no border. If I then go back into the flow screen and uncheck the Add Border checkbox (deselecting it) and then close the screen and re-open it and check the Add Border checkbox (essentially toggling it off and then back on), and then save and either Run or Debug, the border is visible.

Just to clarify, I'm not talking about see a border in the flow builder on the flow screen, I'm talking about when I Run or Debug it. Sorry for the lack of clarity in the original post.

**Comment by jkenzer** [comment]
I did a few more tests. I found if I uncheck and check the Add Border box when I initially add the Datatable to the screen, it will retain the setting.

**Comment by ericrsmith35** [comment]
This has been corrected in the latest release.  v3.0.10  2/27/21
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/

**Comment by ericrsmith35** [comment]
This issue has been corrected in the current release of Datatable.
