### ISSUE TITLE
Uninstalling ActionsBasePack 2.2 - validating steps

### ISSUE THREAD

**Issue by hwong103** [alexed1/LightningFlowComponents#585]
Hi all

Not sure if anyone else has had to deal with having version 2.2 installed and being unable to upgrade to the latest versions (from my quick search I couldn't find anything)

I just wanted see if anyone could help validate my thinking if these steps would work since we have used a lot of these components/actions in our org and is currently in production.

1. Extract affected flows (latest version) metadata via SFDX/VSCode as backup
2. Update all affected flows and remove links to components (I was thinking of just saving a blank flow as a new version)
3. Delete historical flows with references to components
4. Uninstall FlowComponentsBasePack
5. Uninstall FlowActionsBasePack
6. Install latest FlowActionsBasePack
7. Install latest FlowComponentsBasePack
8. Deploy flows into the org as a new version (not sure if this is actually possible at this point) without having to rebuild the flows from scratch

Thanks
Henry

**Comment by ericrsmith35** [comment]
Your steps look good.  For some of the flows you should just be able to
make quick updates to the metadata before deploying them back to the org.

**Comment by hwong103** [comment]
Thanks @ericrsmith35 !

This ended up being ok, did it on Friday night. I ended up using a sandbox to backup the flows as they were in production and pushed the flows back into production via a change set instead.
