### ISSUE TITLE
sendBetterEmail - New Function + FSC_Checkbox  -  Fails when contact has no email even if toAddresses are specified

### ISSUE THREAD

**Issue by edmondo1984** [alexed1/LightningFlowComponents#586]
In our org we have contacts who have a different contact email according to which company they are getting contacted for. When we use the SendRichEmail Invocable Apex from a flow, retrieve the email from the AccountContactRelation, but it fails because the contact has no email with the following error:

20:24:10:394 FLOW_ELEMENT_ERROR An Apex error occurred: SendBetterEmail.InvocableActionException: No Messages were sent.  First Error: nullError Code:INVALID_EMAIL_ADDRESS - The target object's email address "null" is not valid

From what I could read on stackoverflow, the answer is the following:

`email.setTreatTargetObjectAsRecipient(false);`

https://salesforce.stackexchange.com/questions/190794/messaging-settargetobjectid-with-custom-objects

**Comment by jdpond** [comment]
![image](https://user-images.githubusercontent.com/271131/106668255-0c31c000-6578-11eb-97ba-2a72a310c2bc.png)
