### ISSUE TITLE
*Datatable* - _Column Text Wrapping_ - Wrapping doesn't seem to work

### ISSUE THREAD

**Issue by graham228221** [alexed1/LightningFlowComponents#587]
I can't seem to get any columns to wrap, they just flow into the next column

### Steps to reproduce

1. Create a new datatable with more than one column
2. Apply wrapping to a column that is not the name field
3. The column does not wrap, but flows into the next column

### Expected behaviour
It should wrap onto the next line, which was working in datatablev2

### Actual behaviour
The column does not wrap, but flows into the next column

### Screenshots
<img width="596" alt="Screenshot 2021-02-05 181626" src="https://user-images.githubusercontent.com/23298731/107072772-5e741a80-67de-11eb-9290-bea6692f030a.png">

How I'd expect wrapping to look from datatablev2:
<img width="582" alt="Screenshot 2021-02-05 181653" src="https://user-images.githubusercontent.com/23298731/107072818-6df36380-67de-11eb-80b4-fa9ea8f80072.png">

If I use the Chrome console to remove "white-space: nowrap;" from the .slds-truncate css class it looks as expected:
<img width="599" alt="Screenshot 2021-02-05 182129" src="https://user-images.githubusercontent.com/23298731/107073226-fffb6c00-67de-11eb-9764-4b310fe7b971.png">

**Comment by adwhite75** [comment]
@graham228221  was this Datatablev2 or v3?

**Comment by graham228221** [comment]
@adwhite75 this issue is with datatable v3 (one screen shot is of v2, just to illustrate what i expected it to look like)

i have an older version of the component base packs installed, so i was going try uninstalling the old version and see if that made a difference.

**Comment by graham228221** [comment]
@adwhite75 just to confirm, i tried uninstalling old versions of the basepacks but there issue is still the same.

I've also tried installing in a dev org and it seems to be the same:

![Screenshot 2021-02-12 195225](https://user-images.githubusercontent.com/23298731/107815932-f7b9a880-6d6b-11eb-89c5-eeb30fb5a9f5.png)

**Comment by ericrsmith35** [comment]
This has been corrected in the current version (3.1.1) of the Datatable component.
