### ISSUE TITLE
ScreenFlow - Listener not receiving flow events.

### ISSUE THREAD

**Issue by chriskarpyszyn** [alexed1/LightningFlowComponents#590]
In this bit of code:

```
    connectedCallback() {
        window.addEventListener("message", (event) => {
            if (event.data.flowOrigin !== this.url) {
                return;
            }
            const moveEvt = new CustomEvent('flowstatuschange', {
                detail: {
                    flowStatus: event.data.flowStatus,
                    flowParams: event.data.flowParams,
                    name: this.name,
                    flowName: this.flowName
                }
            });
            this.dispatchEvent(moveEvt);
        });
        let sfIdent = 'force.com';
        this.url = window.location.href.substring(0, window.location.href.indexOf(sfIdent) + sfIdent.length);
    }
```

I'd expect a message to get caught when the flow transitions pages, but there is no "message" getting caught in the listener. 

Any idea what I could be missing?

**Comment by alexed1** [comment]
Is this specific to something in this repo? You might want to try posting to Salesforce Stack Exchange?

**Comment by chriskarpyszyn** [comment]
Specific to this repo here: https://github.com/alexed1/LightningFlowComponents/blob/master/flow_process_components/ScreenFlow/force-app/main/default/lwc/screenFlow/screenFlow.js

> When ScreenFlow initializes, it sets up some message-passing infrastructure and determines the org URL. It then renders an iframe and passes to that iframe the name of a visualforce page called screenFlow that’s provided in this package. The URL that loads the screenFlow page also contains query parameters with any input parameters.

I'm not catching where the messaging-passing infrastructure is beyond listening for an event from native salesforce.

**Comment by chriskarpyszyn** [comment]
Maybe I am misunderstanding what is happening in that component?

The page is iframing a screen flow.

`<template>
    <template if:true={url}>
        <iframe width={width} height={height} src={fullUrl} frameborder="0"></iframe>
    </template>
</template>`

and then the component is listening for an event from the iframe.

`        window.addEventListener("message", (event) => {
            if (event.data.flowOrigin !== this.url) {
                return;
            }
            const moveEvt = new CustomEvent('flowstatuschange', {
                detail: {
                    flowStatus: event.data.flowStatus,
                    flowParams: event.data.flowParams,
                    name: this.name,
                    flowName: this.flowName
                }
            });
            this.dispatchEvent(moveEvt);
        });`

**Comment by chriskarpyszyn** [comment]
Nevermind, I see what I was missing. This commit https://github.com/alexed1/LightningFlowComponents/commit/d226022c242f756d6e642790dd7a98d6bcf508ab has a VF page that is dispatching events up the iframe.
