### ISSUE TITLE
sendBetterEmail - Support ReplyEmail

### ISSUE THREAD

**Issue by munawirrahman** [alexed1/LightningFlowComponents#595]
Hi Team,

I believe you folks have done a great job with SendBetterEmail. But the problem with SendBetterEmail is we only can create a new email with a new thread. Sometimes our users don't want the email to be a new email, but they want the customers (or clients) to see historical data of email when sending email with this component. And also it can open a new possibility to automate replying email when some criteria have met.

I think SingleEmailMessage has a method called [setInReplyTo](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_email_outbound_single.htm#apex_Messaging_SingleEmailMessage_setInReplyTo) to reply an email with adding messageId to the parameter.

Combining this and EmailToFlow which has functionality to catch a messageId will definitely help us to automate catching email data, processing the email, do a some logic inside sf, and automate the replying process

Thanks!

**Comment by munawirrahman** [comment]
As addition, in the CPE we can add it like this
<img width="477" alt="Screen Shot 2021-02-12 at 01 02 43" src="https://user-images.githubusercontent.com/75523812/107679269-ef5f6000-6cce-11eb-8079-efbe0abdefc3.png">

**Comment by jdpond** [comment]
Can we leave off the new type?  It's a little confusing, but the developer could assume this is not a replyType if properly labeled, e.g.,
Send Email as a reply in thread of email with the following Id

**Comment by munawirrahman** [comment]
I think that'll work as well!

**Comment by jdpond** [comment]
![image](https://user-images.githubusercontent.com/271131/108099823-157c5b80-7053-11eb-8c34-4cc8de3668b4.png)

**Comment by jdpond** [comment]
Adding to release pull

**Comment by jdpond** [comment]
![image](https://user-images.githubusercontent.com/271131/108100451-eca89600-7053-11eb-8078-431605f5697a.png)

**Comment by jdpond** [comment]
@munawirrahman OK, I got it to work, but what do I use for a message Id to test with?  Options:
EmailMessage
Id - (doesn't work), get an error message of In-Reply-To header is not valid
MessageIdentifier - the identifier that appears at the bottom of threaded emails
ThreadIdentifier - usually seems the same as MessageIdentifier

**Comment by munawirrahman** [comment]
hi @jdpond sorry I was slow response, i think it should be MessageIdentifier the format of that will be something like this : `ABCDEFGHIJKL=5s03sP262OV+YG+pxA@mail.example.com` basically every email to flow will have this value

**Comment by jdpond** [comment]
NP - I've checked and it will work if you add it (I got this one from the header of a test email).
Not sure what it does, but it's in the next release.
Message-ID: <Npqa9000000000000000000000000000000000000000000000QON2YH00HxomxSh_S76puo-AAoH_9Q@sfdc.net>
In-Reply-To: <Fbg5P000000000000000000000000000000000000000000000QOMSGC00gRACvieGTKiHyEKz5Cywdw@sfdc.net>
