### ISSUE TITLE
Default Value for Parent Question

### ISSUE THREAD

**Issue by JodieM** [alexed1/LightningFlowComponents#6]
I want to have the Flow open with all the dynamic questions pre-defined based on a value in the record. 

Eg I have a question to enter a number of months. 
If the item selected before we get to this screen requires months to be entered (eg a variable blMonthsReqd is true), then I want the YES option for the Parent Question to be pre-selected. 

Is this possible. I don't think it is but asking for a feature enhancement if it's not.

**Comment by alexed1** [comment]
Delivered in version 1.1. Install from https://sites.google.com/view/flowunofficial/flow-screen-components/fsc-dynamic-question

**Comment by JodieM** [comment]
Oh, thanks! That's great.
