### ISSUE TITLE
no redirect when using OpenSObject

### ISSUE THREAD

**Issue by matt-the-bass** [alexed1/LightningFlowComponents#61]
I have a simple test flow that I've created which has 3 elements and is triggered by a customer button from an opportunity. The URL of the button passes in the current opportunity's ID. The elements are:

1. quick look up to set an SObject variable (aptly named sObjOpportunity) of type Opportunity to the opportunity matching the ID that is passed in.
2. Screen to confirm that the SObject lookup worked as expected by displaying the value ID of the sObjOpportunity
3. OpenSObject using sObjOpportunity as the source 

When I trigger the flow by clicking the button from an Opportunity record, step 2 displays as expected, but I never get redirected. I've already ensured that "Enable Lightning runtime for flows" is set in my Process Automation Settings.

Do you have any suggestions as to where I'm running into trouble?

**Comment by alexed1** [comment]
Custom Buttons are a very old technology, and Force Events (which power the redirects) don't work with them. Try switching to a Quick Action button.

**Comment by matt-the-bass** [comment]
Hi Alex,
I appreciate you taking the time to reply. Thanks for the suggestions. I’ll check them out!
