### ISSUE TITLE
Datatable (version 3.0.10) - DataTable component - Flow becomes unresponsive after clicking Configure Columns

### ISSUE THREAD

**Issue by karenzelevinsky** [alexed1/LightningFlowComponents#623]
1. I completed a fresh install of Datatable (version 3.0.10) on a brand new sandbox
2. I granted my user the permission set
3. I created a screenflow
4. In the first step I did a "Get Records" on Accounts
5. In the second step I created a screen and dragged in the DataTable element. I gave an api name, selected Account as the object, my collection from Get Accounts for "Display which records", and then clicked the "Configure Columns" button.
6. My flow completely breaks at this point and I am unable to configure the screen shape.

### Expected behaviour
I should be able to configure my columns

### Actual behaviour
The flow becomes unresponsive. There is a frowny face and a progress indicator that never ends. One time when I tried several times on hover I saw the error "thefoodproject--farmdata--c.visualforce.com refused to connect." If I click escape I get this error:
Uncaught TypeError: Cannot read property 'forEach' of undefined
throws at https://thefoodproject--farmdata.lightning.force.com/auraFW/javascript/8WYDoRiNKzw4em08r-Gg4A/aura_prod.js:12:30234

I am happy to share access to this sandbox as it is a non-partial sandbox with no data.

**Comment by ericrsmith35** [comment]
Please try this first and let me know if it resolves the issue.


   - If you see this error when trying to Configure Columns, try going
to *Setup
   > Security > Session Settings* and unchecking “*Enable clickjack
   protection for customer Visualforce pages with headers disabled*“. Also,
   in your *Setup > User settings*, make sure both Debug Mode and
   Development Mode are Unchecked.

Eric Smith

**Comment by karenzelevinsky** [comment]
That did the trick, thanks Eric!!! Also, I didn't put in my list of things that I had activated the flow, which I did have to do as well.
