### ISSUE TITLE
Hover is not defined in Lookup Component

### ISSUE THREAD

**Issue by mbhfromla** [alexed1/LightningFlowComponents#64]
Hi there, love this new feature and it works great, however when I apply it to a page layout, I get this error message. I am looking to pull a list of all of our existing contacts in Salesforce.

Message
Uncaught Action failed: flowcomponents:LightningLookup$controller$hover [$ is not defined]

In the flow test runtime, I get the error message underneath the code but am able to run it successfully.

<img width="571" alt="screen shot 2018-08-07 at 5 11 34 pm" src="https://user-images.githubusercontent.com/12159170/43809081-03029e18-9a65-11e8-966e-28c24df7921c.png">

Are there any steps I can take.

**Comment by ericrsmith35** [comment]
Have you tried downloading the most current version of the component?

**Comment by alexed1** [comment]
that error probably means you don't have jquery installed as a static resource. Some early versions of lookup failed to include it properly. As Eric said, if you upgrade to the latest version this problem should go away.
