### ISSUE TITLE
*datatable* - _(Datable Configuration Wizard)_ - Can't configure columns. Error Non-selective query against large object type (more than 200000 rows).

### ISSUE THREAD

**Issue by romcode** [alexed1/LightningFlowComponents#640]
1. Have an object with lots of data. Example: Task object with 3.500.000 records. (this is my issue case, but I suspected the error is raised with less records)
2. Configure the datatable component to show Task data. Data source section, select object = Task. 
3. Scroll down to Table Formatting section, and click Configure Columns button.
4. Select the fields to be displayed (it does not matter if you use the Type or Pick method, both will fail)
5. You get the error "An unhandled fault has occurred in this flow
An unhandled fault has occurred while processing the flow. Please contact your system administrator for more information."

### Expected behaviour
The datatable wizard columns should appear

### Actual behaviour
The above error is showed instead

### Screenshots
n/a

### Debug Logs
<details>
<summary>Debug Log Information</summary>
 EXCEPTION_THROWN [31]|System.QueryException: Non-selective query against large object type (more than 200000 rows). Consider an indexed filter or contact salesforce.com about custom indexing.
</details>

NOTE: the above error even occurs if you set the "Maximum Number of Records to Display" property to a low number (e.g.: 10 )

As a quick workaround for my business case, I've just modified the QueryNRecords class 

            Id meId = Userinfo.getUserId();
            string query = 'Select '+ queryParam.fieldsToQuery + ' FROM ' +  queryParam.objectApiName + ' WHERE OwnerId = :meId  LIMIT ' + queryParam.numberOfRecords;

Thank you for your help

**Comment by Tmanthegamer** [comment]
The only way to solve this is to introduce a WHERE clause into the query and introduce some crazy query more shenanigans. I'd like to help but I couldn't get all the components to work in my test org. This accepted answer is basically the plan: https://salesforce.stackexchange.com/questions/22631/workaround-for-offset-2000-limit-on-soql-query

**Comment by romcode** [comment]
Hi @Tmanthegamer, reading the stackexchange article, I can't totally understand the exact plan you propose. 

If it is like I guess, it's very similar the workaround I proposed above (adding where OwnerId = :meId )

**Comment by ericrsmith35** [comment]
You should be able to avoid this error by not using the Configure Column wizard.  You can set your column attributes manually in the Advanced section.
