### ISSUE TITLE
*datatable* - _(Custom Property Editor)_ - Error opening component properties second time around if the Advance Mode is used ( [Cannot read property 'message' of undefined] )

### ISSUE THREAD

**Issue by romcode** [alexed1/LightningFlowComponents#642]
### Steps to reproduce

1. Add a Datatable component to a flow screen
2. Select "Advance Mode" => Display All Objects for selection
3. Select object => "Task"
4. Set "Display wich records?" to a colletion task variable
5. Close the screen flow component
6. Open again the screen flow component
7. The error [Cannot read property 'message' of undefined] appears and these three properties values are missing: Display all objects for selection, select object and display wich records.

### Expected behaviour
All the component properties values should be filled and no error should appear

### Actual behaviour
 The error [Cannot read property 'message' of undefined] appears and these three properties values are missing: Display all objects for selection, select object and display wich records.

### Screenshots
![image](https://user-images.githubusercontent.com/33631197/111066812-39e81e00-84c1-11eb-9e57-80eb796a9b5a.png)

**Comment by ericrsmith35** [comment]
This has been corrected and will be in the next datatable release (3.1.1)
