### ISSUE TITLE
*datatable* - _(lwc table)_ - Formula fields are not updated after saving

### ISSUE THREAD

**Issue by romcode** [alexed1/LightningFlowComponents#643]
( Sorry, I'm not totally sure if this is a bug or it is the current expected behaviour and therefore this should be opened as a feature request instead )

### Steps to reproduce

1. Add a datatable component to a screen flow and setting its source object and collection records variable
2. Add at least two columns. One of the fields should be a formula field, the other one an editable field referenced by the formula.
3. Execute the flow
4. Edit the data of the editable field
5. Save the changes
6. The formula field is not updated

### Expected behaviour
The formula field should be updated, as it is when we use standard listviews.

### Actual behaviour
The formula field is not updated

**Comment by ericrsmith35** [comment]
This is current expected behavior.  In order for the value of the formula field to change, you will need update your flow to do an Update Records followed by a Get Records to see the new formula field value.
