### ISSUE TITLE
*Validation Checker* - _(Apex Action)_ - {!Null Pointer validating collection when duplicate rule left optional}

### ISSUE THREAD

**Issue by gudavies** [alexed1/LightningFlowComponents#644]
### Steps to reproduce
1. Add Check Validation v1.2
2. Add LWC datatable from unofficial SF v3.0.10
3.Add a simple validation rule on object
4.Query some data, and edit it using datatable eg) currency field must be positive number
5.Add validation action ensuring it links to record collection linked to screen's datatable component edited rows.
Ensure to leave Check duplicate as blank / not provided, per doco this is optional attribute.
6.Enter negative number and click next
7.Run the flow
8.Null pointer exception (check duplicate attribute is null rather than false by default causing issue)

### Expected behaviour
Validation rules are checked, and toast or success follows

### Actual behaviour
Null pointer exception, potentially output edited rows does not have full data compared to a traditional record collection.
Class.CheckValidation.checkForValidationErrors: line 96, column 1
Boolean allowSave = !req.checkDuplicates;

### Screenshots
![image](https://user-images.githubusercontent.com/57922217/111086797-65771100-8572-11eb-8e73-9584875e9d59.png)
![image](https://user-images.githubusercontent.com/57922217/111087564-64e07980-8576-11eb-93b0-b50695bbb6a9.png)

### Debug Logs
<details>

Selected Navigation Button: NEXT
CHECKVALIDATION (APEX): Validate_Expenses_0
Inputs:
inputCollection = {!Expenses_Table.outputEditedRows} ([Debt__c (************),Debt__c (***********)])

Log shows collection has data, including Ids, replaced in log above for security reasons.

</details>

**Comment by gudavies** [comment]
Workaround - Set input attribute as false
![image](https://user-images.githubusercontent.com/57922217/111088631-336aac80-857c-11eb-8e1f-8775d9aee537.png)

**Comment by ericrsmith35** [comment]
Thanks for the heads up.  I'll get this corrected.

**Comment by ericrsmith35** [comment]
This has been resolved in Version 1.3
https://unofficialsf.com/validation-checker-flow-action/
