### ISSUE TITLE
Datatable - Record Name is blank

### ISSUE THREAD

**Issue by tbayly2288** [alexed1/LightningFlowComponents#649]
When adding the record name field to the datatable, it is blank unless I select the Table Behavior of "Show navigation links on Name fields" in which case it only shows the url.

### Steps to reproduce the behavior:
1. Add Datatable to flow and configure to show records
2. Add Record Name field to columns
3. Turn off "Show navigation links on Name fields"
4. Save and view in run

### Expected behaviour
I'm expecting to see the Record Name when running the flow

### Actual behaviour
The Record Name is blank. When in the configure columns section, the name displays correctly, but once running the flow it displays as blank.

### Screenshots
<img width="1439" alt="Datatable 1" src="https://user-images.githubusercontent.com/61087389/111348545-8a848600-863d-11eb-81be-12d0850fbfa0.png">
<img width="1439" alt="Datatable 2" src="https://user-images.githubusercontent.com/61087389/111348567-907a6700-863d-11eb-891b-f9689e657ef7.png">

**Comment by ericrsmith35** [comment]
Person Accounts have some different behaviors in Salesforce.  To get what you are looking for, try creating a custom formula field to store the name or change your table to instead use the First Name and Last Name fields.
