### ISSUE TITLE
*datatable* - Table behavior - Clear selection button appears for disallowed selection

### ISSUE THREAD

**Issue by zahnarzt-helden-martin** [alexed1/LightningFlowComponents#659]
### Steps to reproduce / Actual behavior
In Datatable Version 3.0.10, when "Disallow row selection" is checked, the flow component will wrongly show a *functioning* "Clear Selection" button when there is only *one* row to be displayed. 

### Expected behaviour
"Clear Selection" button should disappear for single record tables with "Disallow row selection" checked.

### Screenshots
![image](https://user-images.githubusercontent.com/78689737/112188456-4d069680-8c03-11eb-94a1-671385d0ffb3.png)

_PS: Hope this neither is a duplicate issue nor already known!_

**Comment by ericrsmith35** [comment]
This has been corrected in the current version (3.1.1) of the Datatable component.
