### ISSUE TITLE
Experience Builder Guest Users Require Addl Null DataTable To View Records

### ISSUE THREAD

**Issue by veaux** [alexed1/LightningFlowComponents#671]
Witnessed this in last 2 versions at least, 3.0.09-3.0.10. Guest users for Experience Builder (Communities) use Flow to display screen datatable of DuplicateRecordItems. All relevant permissions granted. Upon visit the Datatable will be blank. Debug logs show all queries work as expected. 

Workaround:. We have to put a duplicate DataTable in same screen. We currently use same Sobject Collection variable but display 0 records and make table 0 ht. When we do this then the original datatable will display as expected with all records.

![duplicateMgtAddress (1)](https://user-images.githubusercontent.com/39968149/112760727-11364d00-8fc6-11eb-9233-e9047c734e11.png)
![duplicateMgtAddress (2)](https://user-images.githubusercontent.com/39968149/112760787-33c86600-8fc6-11eb-8a20-f83cdc50def7.png)

**Comment by ericrsmith35** [comment]
Darrell,

Is it just this object or do you see the same behavior with different
objects?

Eric

**Comment by veaux** [comment]
I was afraid you'd ask that. So far been just this object but I can't say
that we have too many with a similar situation (i.e. using one of the
"hidden" objects by a guest user in a datatable view). I'm actually not
sure if we have any other situations like that other than DuplicateRecord
(Set/Item).
- Darrell

**Comment by veaux** [comment]
Eric, today I realized that we do use the datatable with guest Experience users on the Contact and Account objects as well and have zero issues and do not have to use the dummy table on the screen. We have been using previous versions of the datatable on these objects for a while. I believe we just started using it for DuplicateRecordItem with 3.0.09...so it could have existed as a problem before that release on that object.

**Comment by ericrsmith35** [comment]
Given that it works with some other objects and you have a workaround for
this particular issue I'm going to table trying to track this down for
now.  It most likely is a SF and not a Datatable issue.  However, please
let me know if it pops up anywhere else.
