### ISSUE TITLE
Up the API version of used components to get to new objects (like Salesforce Order Management objects)

### ISSUE THREAD

**Issue by bmacaulay** [alexed1/LightningFlowComponents#681]
**Is your feature request related to a problem? Please describe.**
datatablev2 could access the new Order Management objects, Like Order Product Summary (OrderItemSummary), but the new datatable wizard makes use of a class where the API version is 47. 

ASSIGNMENT: Save_Selection_Method
{!vSelectionMethod} Equals {!FieldSelectionMethod.value}
Result
{!vSelectionMethod} = "Pick"
LOOP: Loop_Previously_Selected_Fields
End Loop.
USF__GETFIELDINFORMATION (APEX): Get_Field_Information_usf
Inputs:
objectName = {!vSObject} (OrderItemSummary)
Error Occurred: An Apex error occurred: System.NoAccessException: Entity is not api accessible
Salesforce Error ID: 1169554011-81322 (1461704980)

**Describe the solution you'd like**
We are adding lots of new objects, and would be great to get dependent managed code updated to 51, or replaced e.g. https://github.com/alexed1/LightningFlowComponents/blob/master/flow_action_components/FlowActionsBasePack/force-app/main/default/classes/GetFieldInformation.cls which is erroring out when I use datatable wizard with a newer object (like Order Product Summary)

**Describe alternatives you've considered**
updating Datatable wizard to have it's own getFieldInformation class.

**Additional context**
Unsure of full list of impacted actions.

**Comment by ericrsmith35** [comment]
I've submitted PR#684

**Comment by ericrsmith35** [comment]
This should be in the latest release of the FlowActionsBasePack (2.17)
