### ISSUE TITLE
Guest User Access

### ISSUE THREAD

**Issue by sjones6001** [alexed1/LightningFlowComponents#692]
Does anyone know how to use this for flows accessed by guest users?

**Comment by jdpond** [comment]
Which components?  Varies @sjones6001 Normally allow access to all users when installing allows guest access.  Just because they have access though, doesn't mean they can use them - the utilization is dependent on the privileges granted by the application where they are used.

**Comment by sjones6001** [comment]
My issue turned out to be that toast doesn't work on a log in page (this was for a community log in page.  Created a separate page for my flow and toast is working great now!
