### ISSUE TITLE
Datatable - formatting - Table header

### ISSUE THREAD

**Issue by cadillacben** [alexed1/LightningFlowComponents#698]
- configure it to not display a table header
- type in a table header anyhow

Expected behaviour:

- blank table header

Actual behaviour

- The table header is displayed anyhow
- If you don't type a table header a space is left for the text you didn't type
![settings](https://user-images.githubusercontent.com/17458691/115631727-5c493480-a2d4-11eb-80fe-1c4073760fa8.png)
![table](https://user-images.githubusercontent.com/17458691/115631728-5ce1cb00-a2d4-11eb-8484-4f2bc9f451bf.png)

**Comment by ericrsmith35** [comment]
This will be addressed in the next release
