### ISSUE TITLE
Datatable - formatting - Show row numbers

### ISSUE THREAD

**Issue by cadillacben** [alexed1/LightningFlowComponents#699]
- configure it to not display row numbers
- use a collection with multiple records

Expected behaviour:

Row numbers not shown

Actual behaviour

Row numbers are shown
![table](https://user-images.githubusercontent.com/17458691/115632001-dd083080-a2d4-11eb-86be-5d6615c59b9d.png)
![settings](https://user-images.githubusercontent.com/17458691/115632002-dda0c700-a2d4-11eb-813a-5c7dde615c07.png)

**Comment by ericrsmith35** [comment]
This is standard behavior for the base Salesforce datatable component when inline editing is enabled.

_"If you check the Show Row Numbers checkbox, a column will be added on the left side of the datatable with the row number for each record in the table. The default for this setting is False, however it will always be displayed if any columns are configured to be editable."_
