### ISSUE TITLE
Error deploying flows to new system

### ISSUE THREAD

**Issue by karenzelevinsky** [alexed1/LightningFlowComponents#70]
We built some flows using your awesome components, but unfortunately when we're trying to move the work to production, we're getting errors on the deploy step:

Lightning Definition Bundle ID: bad value for restricted picklist field: c:lookupFSC

It seems that the version of lookupComponentFSC that is installed on the system where we did the development is an unmanaged package so it didn't have a specific namespace. Now we're installing lookupComponentFSC on production and when we installed we got a managed package that has its own namespace, so the component is now named flowcomponents:lookupFSC. This mismatch is making it so our change set won't deploy.

What's your recommendation for how to fix this? Is there a choice about whether install the unmanaged or managed package? Any help is greatly appreciated!!!

Note: I did try installing the latest package on my dev system, but if I switch to the new namespace component, I lose all the attributes. This means I need to find every single place I used the component and manually copy over all the inputs/outputs :(

Thanks

**Comment by allisonletts** [comment]
I'm having the same issue.

**Comment by alexed1** [comment]
We can unblock you.

Here's some background: originally all of these were published unmanaged. We experimented with managed packages, creating the managed package version of lookupComponentFSC. The goal was to make it easy to push upgrade these components, but managed packages bring their own headaches, and this looks like a new one. 

Here's an install link for an unmanaged version of lookupFSC:
https://login.salesforce.com/packaging/installPackage.apexp?p0=04tB000000068rw&isdtp=p1

 Try it and let me know if it works smoothly. If so, I'll add it to the lookup component page. Note that this latest version is the first to feature 
https://github.com/alexed1/LightningFlowComponents/pull/68
https://github.com/alexed1/LightningFlowComponents/pull/59

**Comment by karenzelevinsky** [comment]
Hopefully someone else can give this a try. I decided to bite the bullet and just update to the newest version in dev and then update the places in my flows they used the component. It was annoying but not too bad. This way I'll be able to continue to upgrade to latest in the future. Thanks.
