### ISSUE TITLE
Datatable - null collection causes an output of []

### ISSUE THREAD

**Issue by cadillacben** [alexed1/LightningFlowComponents#701]
I have this datatable only show on the page if it's get records actually gets records.  There are decisions after the screen to see if someone edited or selected rows, so I use those outputs to set a collection count and decide on that.  The component outputs what looks like [] if nothing is passed in.  The issue is that salesforce counts this as one record.  That might be a known issue, but I can't find it if so.

If it outputted the number of rows like it does for selected rows that could be used.

As a work around I added a CountRecordsAndFields action which outputs an integer.  It also outputs a null reference error, but it's working.

**Comment by ericrsmith35** [comment]
Try adding a collection count variable in your flow to "Equals Count" <your Get Records collection> and use that in you flow decision rather than any output from a datatable component that is not rendered on the flow screen.

**Comment by cadillacben** [comment]
I did try that, but salesforce considers [] as one record for some strange reason.
