### ISSUE TITLE
*Validation Checker* - _Picklist Types_ - Picklist Choice Set and Picklist Screen element results in incorrect type error

### ISSUE THREAD

**Issue by zahnarzt-helden-martin** [alexed1/LightningFlowComponents#706]
### Steps to reproduce
In this example on-screen flow, we are using a Picklist Choice Set for the Product2 field Family (Picklist). On a Screen, a Picklist element is fed with that Choice.

### Expected behaviour
The user selected value from the Picklist Choice Set should be matched to the Picklist field value.

### Actual behaviour
No matter which Product Family Picklist value is chosen, Validation Checker always produces an incorrect type error message:

```
Outputs:
errorMessages (New Record Error: ProductName [Product Family: value not of required type: Autoklav] )
isError (true)
firstInsertedId (null)
insertedIdCollection (null)
```

### Screenshots
Picklist Choice Set for the Product2 field Family:
![image](https://user-images.githubusercontent.com/78689737/116535824-7d1d1580-a8e4-11eb-8db1-7913bea21c4c.png)

Screen element Picklist:
![image](https://user-images.githubusercontent.com/78689737/116535412-04b65480-a8e4-11eb-968a-f40cf8730f0f.png)

Runtime Screen with Picklist element:
![image](https://user-images.githubusercontent.com/78689737/116534889-63c79980-a8e3-11eb-88cb-6b4ffafd60ea.png)

Debug APEX output:
![image](https://user-images.githubusercontent.com/78689737/116534411-c53b3880-a8e2-11eb-8ed7-91b175709972.png)

**Comment by ericrsmith35** [comment]
There is a bug in Salesforce that is causing this issue with Picklist values.  I am trying to find some type of workaround.

**Comment by zahnarzt-helden-martin** [comment]
Sounds great, thanks Eric.

**Comment by ericrsmith35** [comment]
This has been corrected in the upcomming Summer '21 Salesforce release.
