### ISSUE TITLE
Datatable - Select Object - AccountContactRelation object not visible

### ISSUE THREAD

**Issue by Juul1** [alexed1/LightningFlowComponents#711]
1. Add datatable to screen
2. Select object.
3. Search for AccountContactRelation
4. Object not visible

### Expected behaviour
That it is possible to select the AccountContactRelation object

### Actual behaviour
Nothing

### Screenshots
![image](https://user-images.githubusercontent.com/43982716/116867293-262d7e00-ac0d-11eb-9550-d86e007003aa.png)

### Debug Logs
If applicable, please insert debug logs here
<details>
<summary>Debug Log Information</summary>

```
Paste the output of the logs here.
```
</details>

**Comment by ericrsmith35** [comment]
Check the "Display ALL Objects for Selection" checkbox to see a complete list of Objects.

**Comment by Juul1** [comment]
Thanks for the quick reply. That I've missed that checkbox.... 😅  sorry @ericrsmith35 .

**Comment by ericrsmith35** [comment]
You weren't the only one.  I have moved it in the most recent version of
Datatable.
[image: image.png]
