### ISSUE TITLE
errors when selected columns

### ISSUE THREAD

**Issue by rongzhonghuang** [alexed1/LightningFlowComponents#713]
get error when select columns for the table

![image](https://user-images.githubusercontent.com/8980006/117007502-160cc000-ad2d-11eb-9941-5a6e2115c337.png)

**Comment by ericrsmith35** [comment]
Please let me know what version of the Datatable component you are running and what object you have selected.

**Comment by rongzhonghuang** [comment]
The Datatable component is running at 3.2.0, the object is Account

![image](https://user-images.githubusercontent.com/8980006/117083274-ad066600-ad87-11eb-9636-0d464952e57d.png)

**Comment by ericrsmith35** [comment]
Have you tried deleting and then re-adding the datatable?

**Comment by ericrsmith35** [comment]
This has been corrected in the current release.
https://unofficialsf.com/datatable-latest-release-notes-v3-2-2/
