### ISSUE TITLE
Datatable v3.2 - OutputSelectedRows - Row Output is Null but Selected Row Count is Not

### ISSUE THREAD

**Issue by CodebraCommander** [alexed1/LightningFlowComponents#714]
Experiencing a bug with Datatable 3.2 in which no records are found in the output collection when rows are selected, although the count of selected rows is correct.

### Steps to reproduce [UPDATED]

1. Create a flow with a Get Records to Accounts
2. Add a Screen Element with a Datatable that uses the accounts and the source
3. Add a "Section Element" to the same screen
3. Add an assignment step assigning the outputCollection to an Account Collection variable.
4. Add an assignment to assign the NumRowsSelected output to a number variable

### Expected behaviour
The flow completes the the Account Collection Variable is populated with the selected accounts

### Actual behaviour
The OutputCollection is [] and thus the colleciton variable is also null; however the count of rows selected is correct.  See screenshots with debugger.  Very odd.

### Screenshots

![Referral-Account-Selector](https://user-images.githubusercontent.com/21369480/117100519-ea480500-ad41-11eb-8848-f9986341db49.png)
![Referral-Account-Selector (1)](https://user-images.githubusercontent.com/21369480/117100521-ecaa5f00-ad41-11eb-8866-ea3ef73f934f.png)

### Debug Logs
If applicable, please insert debug logs here
<details>
<summary>Debug Log Information</summary>
{Id=0014000001i9rYtAAI, Name=Levy Affiliated, BillingStateCode=CA}, {Id=0014000001i9rYxAAI, Name=Oro Capital Advisors, BillingStateCode=CA}])
tableHeight = (500px)
Outputs:
**numberOfRowsSelected = 3**
outputEditedRows = []
outputEditedRowsString =
outputSelectedRow = null
**outputSelectedRows = []**
outputSelectedRowsString =
wizColumnFields = Name, BillingStateCode
wizColumnWidths = Name:470, BillingStateCode:470
wizSObject = Account

</details>

**Comment by CodebraCommander** [comment]
UPDATE:  I think I have discovered the source of the bug.

If there is a Section screen element anywhere on the same screen as the data table where you make selections, the table does not output any selected rows.  I don't know why that happens but it does reproduce the error:

![datatable bigs when section component on screen](https://user-images.githubusercontent.com/21369480/117134610-c8677600-ad73-11eb-98b2-cd55ae9b82d3.png)

**Comment by ericrsmith35** [comment]
@alexed1 This behavior is still present in Summer 21.  What has to change in how collection values are passed back to the Flow in order to get this to work?

**Comment by ericrsmith35** [comment]
This will be corrected in the upcoming 3.2.1 release.

**Comment by CodebraCommander** [comment]
Thank you!

**Comment by ericrsmith35** [comment]
The 3.2.1 release is now available.
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/#Installation
