### ISSUE TITLE
Unofficial Lookup Cpmonent Throwing an Mysterious Error

### ISSUE THREAD

**Issue by SandyHunter** [alexed1/LightningFlowComponents#733]
Wow. I am stuck and need your help, SuperFlow people.
I'm working with the Unofficial LookUp Component, and trying to make a parent/child combo of components on a single screen.
For some reason I keep getting this error: "Exception occurred: invalid ID field: Id Class.LightningLookupController.getFieldValue: line 141, column 1"
I took a deep dive and realized I was using an older version of the component. Okay, I tell myself, and go through the process of getting the latest component into the sandbox. Still getting the error.
The first component is a look up to the account, the second is a lookup to a child contract record.
Here's the kicker, I'm still getting the error message, but if I carry through the flow, the records still get created as they should.
That said, the error message will throw off my end users. Can anyone help me out on this?
Thanks,
-Sandy

### Documentation issues

If your problem stems from wrong, outdated, or unclear documentation, please:

1. Submit a link to the documentation here:
2. Explain why it is wrong or unclear:
3. Suggest any changes:

### Support requests

We do not offer support for these components, and help requests will be closed.

**Comment by ericrsmith35** [comment]
Can you please share exactly how you have the component configured as well as how it is used in your flow.

**Comment by SandyHunter** [comment]
Thanks Eric!
I'm using version 2.40.
In the parent component, I have it configured like this:

API Name: LookuUp_Amendment_Company
Component ID: ContractParentCompanyComponent
Default Value:  blank
I1: Account
I2: Name
I3: Select the Contracting Organization
I4: Id
I5: Parent
I6 - I8: all blank
Icon, O1_Output Value and Parent Id: all blank
Required? {!$GlobalConstant.False}
Where Clause: Contact_Type__pc includes ( 'Contractor' ) OR 	Company_Type__c includes ( 'Contracting Organization' ) 

That's it for the first component, here's the 2nd component (the child):
API Name: OriginalContract
Component ID: SelectContractComponent
Default Value: blank
I1: Contract
I2: ContractNumber
I3: Select the original contract for the amendment
I4: Id
I5: Child
I6 - I8: all blank
Icon: blank
O1_Output Value = Id
Parent Id: LookuUp_Amendment_Company
Required: {!$GlobalConstant.False}

That's about it.  Thanks for checking on this, Eric. I appreciate it!

**Comment by ericrsmith35** [comment]
I6 in the second component should be AccountId
