### ISSUE TITLE
Need ability to remove Default value and pass null to O1_Output Value

### ISSUE THREAD

**Issue by adb1146** [alexed1/LightningFlowComponents#74]
The new NEW PARAMETER - Default Value Usage is a great new feature, however, removing the default value is clunky. Unlike when you add a new value and you are presented with an X to clear the value thus passing a null value to the O1_Output Value. The only way to clear the Default Value is to first search, select a new value from the filtered list and then clear the variable in the field.

**Comment by adb1146** [comment]
@ericrsmith35 Having the option to X out the default immediately after load without otherwise having to interact with the field would do the trick. Today when the screen loads the X is not an available option hence there is no way to remove the default value without first selecting a new value. 
![x-is-missing](https://user-images.githubusercontent.com/36891491/45091552-d2c3a480-b0e0-11e8-822b-fd1bec16ac30.png)

**Comment by ericrsmith35** [comment]
The default value is actually being displayed using the 'placeholder' modifier for the input element.  It represents what will be available on selecting the dropdown.  There is no X because there is no real value in the field until you either type something or make a selection from the dropdown.
