### ISSUE TITLE
Selected rows not stored when using flow Section(Beta)

### ISSUE THREAD

**Issue by broekhoven** [alexed1/LightningFlowComponents#742]
Hello,

Found a Bug where the selected rows are not stored when the Data Table is placed within thew new flow Section Column. When placed outside of the Section the Row selection is stored correct in the collection again.

![image](https://user-images.githubusercontent.com/23707303/119464437-04727300-bd43-11eb-9ea9-8743e4971c6e.png)
![image](https://user-images.githubusercontent.com/23707303/119464538-1a803380-bd43-11eb-9241-8de4c1332c98.png)

**Comment by ericrsmith35** [comment]
This has been addressed in v3.2.1
