### ISSUE TITLE
Use "I1_Object Name" to reference a SObject Collection instead of table

### ISSUE THREAD

**Issue by adb1146** [alexed1/LightningFlowComponents#75]
As a future enhancement would it be possible to reference a SObject Collection instead of a table in the "I1_Object Name". This way we could generate a SObject Collection as a Temp Table of sorts.

**Comment by ericrsmith35** [comment]
I'm not sure what you are are trying to do here.  Could you provide a little more detail?

**Comment by adb1146** [comment]
@ericrsmith35 Absolutely. In flows today we can leverage Dynamic Picklists to make selections of values from filtered objects. However in many cases, one may not want to select objects directly from a table but rather from the equivalent of a APEX collection. Obviously, we cannot leverage an apex collection in Flows but we can construct sObject Collections which would be very similar. The advantage here is that we can use complex decision making to construct the collection which would then be referenced in the Lookup instead of an object. An example would be where we have a related junction object that stores contacts that have attended meetings with a specific account over time. In a flow you can iterate across the records that have attended multiple meetings with a particular client. You place these IDs in a sObject Collection of Contacts. This would become even more powerful if we ever have the ability to multi-select within a lookup.

**Comment by ericrsmith35** [comment]
@adb1146 That's a great idea for an enhancement.  It would require a fair amount of additional cusomization.

**Comment by adwhite75** [comment]
@adb1146  would it be fair to say that Apex-Defined types could be utilized here?

**Comment by adwhite75** [comment]
Resolved with generic sobject support
