### ISSUE TITLE
"I4_Output Which Field as Value?" Output as Text "Id" instead of the actual Id 

### ISSUE THREAD

**Issue by JustinJCarlson** [alexed1/LightningFlowComponents#76]
I am using the lookup component on the User object. 

I am looking to output the Id of the user made in the selection

Currently, the output value is the text string of any field I supply as the "I4_Output Which Field as Value?".

**Comment by ericrsmith35** [comment]
Are you entering Id as the name of the output field?

**Comment by JustinJCarlson** [comment]
Yes. I have also tried to use a custom formula field. 
![image](https://user-images.githubusercontent.com/3036013/46108544-f0e26900-c1a3-11e8-966c-8aa0fa164a0a.png)

**Comment by JustinJCarlson** [comment]
Screenshot from Flow Error Email

![image](https://user-images.githubusercontent.com/3036013/46108636-29824280-c1a4-11e8-9cbd-2d254e1258b1.png)

**Comment by JustinJCarlson** [comment]
So, I used "O1_Output Value" instead which seems to auto store the id of the selection. This works. But I still think the "I4_Output Which Field as Value?" is not working properly. 

Thanks!

**Comment by ericrsmith35** [comment]
I4_Output Which Field as Value is an input parameter identifying the name
of the field in the selected record whose value will be populated in the
variable specified in the output parameter O1_Output Value.

**Comment by jrr700** [comment]
Hello, I am new to this components in Flow . I installed the lookup component.  I have tried unsuccessfully to the the output variable to populate. I was experimenting with different scenarios. I received (id) once, but usually just getting null. I am capturing data that will be populated for creating a task.. the lookup field is passing the ID into a custom Lookup field. I am pulling my hair out trying to get this to work and I read and reread you notes.. I am using in Summer '19 sandbox.
It looks pretty straight forward from above, but I am not getting the desired result. Any help?

HERE IS MY FLOW DEBUG below:
RECORD CREATE: CreateTask
Create one Task record where:
ActivityDate = {!taskDueDateOnly} (June 2, 2019)
Priority = {!taskPriority} (Normal)
**Product__c = {!curProductIDOutput} (null)**
RecordTypeId = {!curTaskRecordType} (0120Y000000lBR3QAM)
SalesPrice__c = {!Sales_Price} (null)
SpendableBudget__c = {!Spendable_Budget} (null)
Status = {!taskStatus} (Not Started)
Subject = {!taskSubject} (Media Request)
WhatId = {!curOppId} (0060E00000E0zyo)

**Comment by ericrsmith35** [comment]
What are all of the parameters you are using for the Lookup component?

Eric Smith

**Comment by jrr700** [comment]
Thanks for the quick reply. I will screen grab what I have.  I have tried Using O1_Output Value on on Both INPUT and OUTPUT Sections.  Maybe I am not selecting the correct Fields. 
Let me know if you need any more info.
![image](https://user-images.githubusercontent.com/30743414/58743540-38329080-83e8-11e9-87c9-045f672bd6e2.png)
![image](https://user-images.githubusercontent.com/30743414/58743547-5f895d80-83e8-11e9-8ba0-e01ae7bb0a31.png)
![image](https://user-images.githubusercontent.com/30743414/58743550-6dd77980-83e8-11e9-8486-f5d692faa47c.png)
![image](https://user-images.githubusercontent.com/30743414/58743555-85166700-83e8-11e9-86a3-d051f47edc77.png)

**Comment by ericrsmith35** [comment]
It looks like you are trying to present a lookup list of all Products where
the Family equals "Media".  You should be able to do this one of 2 ways.

1) Clear out the input values for I6_Filter on which field? and O1_Output
Value

-- or --

2) Clear out the input value for Where Clause, set I6_Filter on which
field? to Family and set I7_Filter Value to Media (no quotes)

Eric

**Comment by jrr700** [comment]
That is correct.  I am trying to filter the lookup field by Product WHERE Family = 'Media'.  Running the flow does produce this filter and I can select. it.   Applying your suggestion, "clearing the value at I6_Filter on which field? seems to always default to AccountId . I did have this at Productid being that is the the Product2 Standard Object. So this does work.  It applies the filter to where i can select a Product.  I am just trying to grab the ID from the Lookup Field ( Product2) and then apply that Id to create a Task:

This is my Create Records element to create a Task record:
![image](https://user-images.githubusercontent.com/30743414/58754193-f8b78300-847f-11e9-8da7-36406d2a3714.png)

**Comment by ericrsmith35** [comment]
What if you try the second option I mentioned instead?

**Comment by jrr700** [comment]
Yes, that did work..thank-you.  I think the confusing part is there are two: O1_Output Value parameters.  I am not sure what the first one is for.  Thank-you again.  I think this will work well for my application.

I just want to show you the fields I used:
![image](https://user-images.githubusercontent.com/30743414/58755321-25769500-8496-11e9-8e9f-1e885d6b4c28.png)
![image](https://user-images.githubusercontent.com/30743414/58755325-3de6af80-8496-11e9-8140-c8e5e28bf14e.png)
![image](https://user-images.githubusercontent.com/30743414/58755333-5d7dd800-8496-11e9-86ed-f976aa4abaa2.png)

**Comment by ericrsmith35** [comment]
I'm glad it is working for you!  All parameters show up for both Input and
Output whether they are needed or not.

**Comment by jrr700** [comment]
Hi eric, sorry to bug you again. Although i did get the Lookup component to work correctly, I  am now adding some more field to create my task. As I mentioned, I am launching a quick action flow to create a task.  The task screen has several input fields including your look up component.  Among some other inputs, I have added a multi-select picklist the the screen the hard way by adding individual choices as I can not get the multi-select options to commit so I had to add individual "choices"(long story).  Anyway this was the resent field I added.  Now the Lookup field is displaying null again and Can't figure why adding my last field would do this.  I have other fields ie. dates fields and currency fields, but this last one throws the null error.  Would you happen to know any reason why this would happen?

**Comment by ericrsmith35** [comment]
Are you trying to use a value from one of the other input fields as a
parameter in the lookup?

**Comment by jrr700** [comment]
Not not at all. Here is my edit screen:
![image](https://user-images.githubusercontent.com/30743414/58809058-0f6cef80-85d0-11e9-91cd-9b16b6792efe.png)

Here is my Flow diagram:
![image](https://user-images.githubusercontent.com/30743414/58809296-80140c00-85d0-11e9-8c0f-0ea28a9cdfcf.png)

Here is my Create Task with Loopup Output component and New Content fields:
![image](https://user-images.githubusercontent.com/30743414/58809459-cff2d300-85d0-11e9-9884-4575e07f45cc.png)

**Comment by ericrsmith35** [comment]
Try creating a "Debug" screen node before your Create Task node and use it
to first just display each of the values you will be using in the Create
Task.

**Comment by jrr700** [comment]
My bad:  I just realized this message in Flow below:  I was running from debug and not knowing its probably not going to show up.  It works now.  Come to think of it, this might have been one of my issues all along.  Thanks for your help.   iI will keep building on this flow and hopefully this will work perfectly. 

**"Media_Task (Screen) - This screen includes screen components that require Lightning runtime**"
