### ISSUE TITLE
Display other fields in search results

### ISSUE THREAD

**Issue by adwhite75** [alexed1/LightningFlowComponents#77]
Hey Alex! Awesome component you've made!

Are there any plans to configure the search results? Right now I have to make a formula field on the target object to show more than 1 field in the results dropdown, which is no different from what I have to do with Flow's Dynamic Choice results. It's a bit of a bummer to have to make a new field...

**Comment by jlig** [comment]
Agree. But I find using a "custom formula field" gives me full control over what shows up in the lookup.
- Are we able to specify more than one column?
- It would be valuable for the end-user to see multiple, formatted columns

**Comment by ericrsmith35** [comment]
The component will only display a single field at this time.  Formula fields are the way to go if you want to display info from multiple fields.

**Comment by adwhite75** [comment]
This is a dupe of https://github.com/alexed1/LightningFlowComponents/issues/159
