### ISSUE TITLE
*{!Datatable}* - _({!PickList})_ - {!Display API name rather than Value}

### ISSUE THREAD

**Issue by twu027** [alexed1/LightningFlowComponents#770]
Hi Eric,

We are using your LWC to display an object in our org. We have a picklist to be displayed 
![Screen Shot 2021-06-14 at 11 08 33 AM](https://user-images.githubusercontent.com/7453271/121824538-f93ab380-cd00-11eb-8fe4-e4c1ae6ebca5.png)

but in the UI, the API name is displayed rather than the value. The API name does not make sense to our end users. Is that possible to display the value rather than name? See the occupation below, it is a number not the description

![Screen Shot 2021-06-14 at 11 12 48 AM](https://user-images.githubusercontent.com/7453271/121824610-8120bd80-cd01-11eb-99a4-7bee219723d5.png)

**Comment by ericrsmith35** [comment]
What version is this happening in?

**Comment by twu027** [comment]
3.x.x

**Comment by ericrsmith35** [comment]
Do you get the same results with version 3.2.3?
https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G0000047xJnQAI

**Comment by twu027** [comment]
I will try, Thanks Eric!

**Comment by jumboxue** [comment]
@twu027 it has been fixed in the latest version of datatable. We could close it now. Thanks.
