### ISSUE TITLE
* FlowActionsBasePack* - _(Update to 2.22)_ - This app can't be upgraded. 

### ISSUE THREAD

**Issue by CodeKoz** [alexed1/LightningFlowComponents#771]
### Steps to reproduce

1-install ver 0.1 (2.18)
2-try to update to ver 0.1 (2.22)

### Expected behaviour
It should upgrade

### Actual behaviour
Message : 
This app can't be upgraded. There are problems that prevent this package from being installed. Invalid Upgrade. The currently installed version does not share a common ancestor with this version.

**Comment by CodeKoz** [comment]
I just saw this on the comment section of unofficialsf. Is there a way to upgrade properly @alexed1 ?

```
Comment
Tried to upgrade the FlowActionsBasePack from 2.17 to 2.18 results in unsuccessful error: Invalid Upgrade. The currently installed version does not share a common ancestor with this version. The upgrade for FlowScreenComponentsBasePack was succesful however, anyone else seeing this?

Alex Edelstein Mod  • 14 days ago
Skip 2.18 and go to 2.19, which is now published. it should upgrade cleanly from 2.17
```

**Comment by CodeKoz** [comment]
I seem to have found this topic : https://github.com/alexed1/LightningFlowComponents/issues/585

Do I need to go through this steps? I also have some aditional components (datatable, send better email and RIch text mostly) . Do I need to uninstall the other packages as well?

Or do you have a getaround solution on the upgrade problem?

**Comment by alexed1** [comment]
I am really sorry about this currently there is no way other than all of that uninstall. The validation gap That caused version 18 to be orphaned is serious enough that the product manager of packaging plans to add functionality just to protect against it happening again.￼￼

**Comment by CodeKoz** [comment]
No prob, just wanted to make sure that I had to do it !
