### ISSUE TITLE
Datatable number of edited records output - Feature request

### ISSUE THREAD

**Issue by cadillacben** [alexed1/LightningFlowComponents#774]
**Is your feature request related to a problem? Please describe.**
If the outputEditedRows = [null] salesforce will count that as 1 when doing an equals count assignment.  The result is that I can't make a decision on if any rows were edited without using another action (count records and fields).  

**Describe the solution you'd like**
A number output showing the number of edited rows similar to numberOfRowsSelected.

**Describe alternatives you've considered**
count records and fields action - in use today
compare the input and output collections - considered but not tested

**Comment by ericrsmith35** [comment]
This has been added in v3.2.4
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/

New Output Attribute for the Number of Rows Edited (Because even when no rows are edited, the OutputEditedRows attribute is not null)
