### ISSUE TITLE
*DataTable* - Inline editing Percentage 7%- Returns 7.000000000000001

### ISSUE THREAD

**Issue by broekhoven** [alexed1/LightningFlowComponents#781]
Hello,

While testing the Datatable I found out that when I Enter 7%(0,07) in the datatable the output value becomes 
7.000000000000001 instead of 7.

All other numbers do work as expected.

### Steps to reproduce

1. Create a data table for the OpportunityLineItem Object
2. Use the discount field in inline edit mode
3. Enter 0,07 as value
4. proceed to next step

### Expected behaviour

The shown value before proceeding does show 7%

The data table should return 7%

### Actual behaviour

The datatable returns Discount:7.000000000000001,

### Screenshots

![Screenshot 2021-06-21 at 16 40 35](https://user-images.githubusercontent.com/23707303/122780807-780a9000-d2af-11eb-8d56-1bbefbfa3e38.png)
![Screenshot 2021-06-21 at 16 33 00](https://user-images.githubusercontent.com/23707303/122780810-793bbd00-d2af-11eb-8876-fed8e2345d42.png)
![image](https://user-images.githubusercontent.com/23707303/122781322-f9fab900-d2af-11eb-9009-7e5c7d140104.png)

**Comment by ericrsmith35** [comment]
This is an issue with how JavaScript stores numbers.  I don't think there is anything that can be done about this.

**Comment by broekhoven** [comment]
My solution is a formula that multiplies and round the number:
round({!Discount}*100,2).

**Comment by ericrsmith35** [comment]
Good idea!
