### ISSUE TITLE
*FlowScreenComponentsBasePack* - _(Installation)_ - On sandbox failed

### ISSUE THREAD

**Issue by jumboxue** [alexed1/LightningFlowComponents#782]
I'm trying to upgrade datatable from v3.2.1 to v.3.2.3 by following instructions on this page 
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/

The first step is following https://unofficialsf.com/flow-action-and-screen-component-basepacks/ to upgrade base packs.
1. The upgrade of FlowActionsBasePack to 2.24 in the sandbox is a SUCCESS.
2. The upgrade of FlowScreenComponentsBasePack to 2.3.7 is a FAIL. (BTW: there is no link to sandbox package so I use the production/dev package link which is incorrect?)
3. The upgrade of Datatable to v3.2.3 is a FAIL due to failure of step #2.

Details of failure in step #2.
Your request to install package "FlowScreenComponentsBasePack ver 0.1" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.

If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.

Organization: (00D0n0000001EjA)
User: Jumbo Xue (0050n000003dW1o)
Package: FlowScreenComponentsBasePack (04t5G0000047xJi)

Problem:

1.  Apex compile failure
Apex class FilterCollectionTest: line 12, column 21: Variable does not exist: sourceAccountCollection

2.  Apex compile failure
Apex class FilterCollectionTest: line 13, column 64: Variable does not exist: sourceAccountCollection

3.  Apex compile failure
Apex class FilterCollectionTest: line 19, column 21: Variable does not exist: sourceAccountCollection

4.  Apex compile failure
Apex class FilterCollectionTest: line 20, column 59: Variable does not exist: sourceAccountCollection

5.  Apex compile failure
Apex class FilterCollectionTest: line 25, column 21: Variable does not exist: sourceAccountCollection

6.  Apex compile failure
Apex class FilterCollectionTest: line 30, column 21: Variable does not exist: sourceAccountCollection

7.  Apex compile failure
Apex class FilterCollectionTest: line 32, column 21: Variable does not exist: targetValuesCSVString

8.  Apex compile failure
Apex class FilterCollectionTest: line 33, column 21: Variable does not exist: filterField

9.  Apex compile failure
Apex class FilterCollectionTest: line 40, column 48: Variable does not exist: filteredAccountCollection

10.  Apex compile failure
Apex class FilterCollectionTest: line 51, column 21: Variable does not exist: sourceCaseCollection

11.  Apex compile failure
Apex class FilterCollectionTest: line 52, column 61: Variable does not exist: sourceCaseCollection

12.  Apex compile failure
Apex class FilterCollectionTest: line 58, column 21: Variable does not exist: sourceCaseCollection

13.  Apex compile failure
Apex class FilterCollectionTest: line 59, column 56: Variable does not exist: sourceCaseCollection

14.  Apex compile failure
Apex class FilterCollectionTest: line 64, column 21: Variable does not exist: sourceCaseCollection

15.  Apex compile failure
Apex class FilterCollectionTest: line 69, column 21: Variable does not exist: sourceCaseCollection

16.  Apex compile failure
Apex class FilterCollectionTest: line 71, column 21: Variable does not exist: targetValuesCSVString

17.  Apex compile failure
Apex class FilterCollectionTest: line 72, column 21: Variable does not exist: filterField

18.  Apex compile failure
Apex class FilterCollectionTest: line 79, column 48: Variable does not exist: filteredCaseCollection

19.  Apex compile failure
Apex class NC_ApplicantTransformation_Test: line 52, column 16: Comparison arguments must be compatible types: Integer, String

20.  Apex compile failure
Apex class NC_ApplicantTransformation_Test: line 91, column 16: Comparison arguments must be compatible types: Integer, String

21.  Apex compile failure
Apex class NC_ApplicantTransformation_Test: line 264, column 43: Method does not exist or incorrect signature: void getApplicants(List<LLC_BI__Legal_Entities__c>, Map<Id,Account>, Map<Id,List<LLC_BI__Income__c>>, Map<Id,List<LLC_BI__Financial_Report__c>>, Map<Id,List<LLC_BI__Debt__c>>, Map<Id,List<LLC_BI__Deposit__c>>, User) from the type NC_ApplicantTransformation

22.  Apex compile failure
Apex class NC_DAPayloadProcessor_Test: line 72, column 65: Method does not exist or incorrect signature: void createDARequest(LLC_BI__Product_Package__c, NC_DecisionAgentRequest.Facilities, LLC_BI__Loan__c, List<NC_DecisionAgentRequest.Applicants>, List<NC_DecisionAgentRequest.Securities>, User, LLC_BI__Service_Mgmt__c) from the type NC_DAPayloadProcessor

23.  Apex compile failure
Apex class NC_DAPayloadProcessor_Test: line 194, column 65: Method does not exist or incorrect signature: void createDARequest(LLC_BI__Product_Package__c, NC_DecisionAgentRequest.Facilities, LLC_BI__Loan__c, List<NC_DecisionAgentRequest.Applicants>, List<NC_DecisionAgentRequest.Securities>, User, LLC_BI__Service_Mgmt__c) from the type NC_DAPayloadProcessor

24.  Apex compile failure
Apex class NC_LADPayloadProcessor_Test: line 200, column 76: Method does not exist or incorrect signature: void createLoanSecurities(LLC_BI__Product_Package__c, List<LLC_BI__Loan_Collateral2__c>, Map<Id,List<LLC_BI__Collateral_Valuation__c>>) from the type NC_LADPayloadProcessor

25.  Apex compile failure
Apex class NC_LADPayloadProcessor_Test: line 334, column 64: Method does not exist or incorrect signature: void createtFacilities(LLC_BI__Product_Package__c, LLC_BI__Loan__c, Integer, List<LLC_BI__Pricing_Rate_Component__c>, List<LLC_BI__Pricing_Payment_Component__c>) from the type NC_LADPayloadProcessor

26.  Apex compile failure
Apex class NC_LADPayloadProcessor_Test: line 418, column 64: Method does not exist or incorrect signature: void createtFacilities(LLC_BI__Product_Package__c, LLC_BI__Loan__c, Integer, List<LLC_BI__Pricing_Rate_Component__c>, List<LLC_BI__Pricing_Payment_Component__c>) from the type NC_LADPayloadProcessor

27.  Apex compile failure
Apex class NC_LADPayloadProcessor_Test: line 691, column 53: Method does not exist or incorrect signature: void mapLADRequest(LLC_BI__Product_Package__c, List<LLC_BI__Loan__c>, Map<Id,List<LLC_BI__Pricing_Rate_Component__c>>, Map<Id,List<LLC_BI__Pricing_Payment_Component__c>>, Map<Id,List<LLC_BI__Fee__c>>, Map<Id,List<LLC_BI__Loan_Collateral2__c>>, Map<Id,Account>, Map<Id,List<LLC_BI__Collateral_Valuation__c>>, Map<Id,List<LLC_BI__Service_Mgmt__c>>, Map<Id,List<LLC_BI__Loan_Collateral2__c>>, Map<Id,List<LLC_BI__Legal_Entities__c>>, Map<Id,List<NC_Loan_Guarantee__c>>) from the type NC_LADPayloadProcessor

28.  Apex compile failure
Apex class NC_SecurityDeValTransformation_Test: line 34, column 84: Method does not exist or incorrect signature: void transformSecurityDeValuation(LLC_BI__Loan_Collateral2__c) from the type NC_SecurityTransformation

29.  Apex compile failure
Apex class NC_SecurityTransformationTests: line 25, column 35: Method does not exist or incorrect signature: void setSecurityDetails(NC_DecisionAgentRequest.Securities, List<LLC_BI__Collateral_Valuation__c>) from the type NC_SecurityTransformation

30.  Apex compile failure
Apex class NC_SecurityTransformationTests: line 45, column 35: Method does not exist or incorrect signature: void setSecurityDetails(NC_DecisionAgentRequest.Securities, List<LLC_BI__Collateral_Valuation__c>) from the type NC_SecurityTransformation

31.  Apex compile failure
Apex class NC_SecurityTransformationTests: line 68, column 35: Method does not exist or incorrect signature: void setSecurityDetails(NC_DecisionAgentRequest.Securities, List<LLC_BI__Collateral_Valuation__c>) from the type NC_SecurityTransformation

32.  Apex compile failure
Apex class NC_SecurityTransformationTests: line 89, column 35: Method does not exist or incorrect signature: void setSecurityDetails(NC_DecisionAgentRequest.Securities, List<LLC_BI__Collateral_Valuation__c>) from the type NC_SecurityTransformation

**Comment by ericrsmith35** [comment]
It looks like many of those Apex errors are from other Apex tests in your target org.  When installing, under the Advanced Options section, select 'Compile only the Apex in the package'

**Comment by jumboxue** [comment]
Thank you Eric! It works. Close this now.
