### ISSUE TITLE
SendBetterEmail - BetterSendEmailUtil- Too Many SOQL Queries error from "cache" email templates

### ISSUE THREAD

**Issue by jdpond** [alexed1/LightningFlowComponents#786]
@Luke Freeland is having an issue with Send Better Email.  Using the BetterSendEmail apex action from a scheduled flow with cases to send reminder emails via email templates. This is my first instance of using scheduled flow with apex actions to try and send emails. It looks like we're hitting apex limits because all the flow interviews are running together instead of each record running the flow interview sequentially. We're hitting a Too Many SOQL Queries error and we think it's because the BetterSendEmail apex class is calling the BetterSendEmailUtil.getMapTemplateNameByEmailTemplates function to "cache" the email templates. However, we're using email template ids so there's no need to query the email templates so the email template names is empty but is still issuing the query which will return no email templates. We think since Apex Actions are called once per interview, it's calling this multiple times.
The fix I'm trying to apply is this:

`    public static Map<String, List<EmailTemplate>> getMapTemplateNameByEmailTemplates(
        Set<String> templateNames,
        Map<Id, EmailTemplate> mapIdByEmailTemplate
    ) {
        Map<String, List<EmailTemplate>> mapTemplateNameByEmailTemplates = new Map<String, List<EmailTemplate>>();
        if (templateNames == null ||
            templateNames.isEmpty()) {
            return mapTemplateNameByEmailTemplates;
        }`

**Comment by alexed1** [comment]
I've merged this and geenrated a new 2.1.4 package:  https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G0000047xLUQAY

do you want to publish it immediately? @jdpond

**Comment by jdpond** [comment]
Published
