### ISSUE TITLE
SendBetterEmail - Unable to send Lightning templates to users

### ISSUE THREAD

**Issue by Garywoo** [alexed1/LightningFlowComponents#788]
It doesn't appear to be possible to send lightning template emails to users. In my use case, the related entity type of the template is a custom object. When I specify a UserID in the **Recipient Record Id** field of the action, I get the following error:

> nullError Code:INVALID_ID_FIELD - WhatId is not available for sending emails to UserIds.

The [documentation](https://unofficialsf.com/send-better-email-flow-action/#:~:text=Required%20if%20using%20a%20template.%20The%20ID%20of%20the%20contact%2C%20lead%2C%20or%20user%20to%20which%20the%20email%20will%20be%20sent.) says that the **Recipient Record Id** field accepts the ID of the contact, lead, or user to which the email will be sent. I am unable to get it to work with Users IDs. I have tried supplying a contact ID instead, and this worked successfully.

The full config of the action is as follows:
`recordId` = ID of my custom object record
`SendTOthisStringCollectionOfEmailAddresses` = A string collection containing 2 valid emails
`setTreatTargetObjectAsRecipient` = true
`templateTargetObjectId` = User ID
`templateID` = Lightning Template ID

### Steps to reproduce

1. Create an autolaunched flow containing the SendBetterEmail action
2. Configure the inputs as above
3. Debug the flow to test

### Expected behaviour
The template is sent to the 2 provided emails, and the template references the user supplied as the recipient.

### Actual behaviour
The above quoted error occurs.

**Comment by jdpond** [comment]
Before I look into this, there must be a 1-1 correlation between the collection size of the RecipientId and the RelatedEntity (e.g., 1 recipient, 1 whatId; 2 recipients, 2 whatIds)

**Comment by jdpond** [comment]
1.  Thank you for your fantastic bug submission - it really has all the components necessary to research
2. If you'd like to chat with me, I am on salesforceohana.slack.com as Jack D. Pond
3. I think we can close this, but I'd like your feedback before doing so

I just looked at this - and remember I've run into this before.  User is **NOT** a valid setWhatId(whatId) (singleEmailMessage) or 
setWhatIds(whatIds) (massEmailMessage).  This is a limit of the SF Class sendBetterEmail was built on - not much we can do about it except lodge it as an enhancement.

```
Related Record Id (for template merge fields and/or recording Email as a task)
The ID of a record associated with the recipient.

This value must be the record ID of one of the following object types:

Account
Asset
Campaign
Case
Contract
Opportunity
Order
Product
Solution
Custom
```

**Comment by Garywoo** [comment]
Thanks for the insight Jack.

Since sending to users is not possible, should this issue instead stand as an issue with the [documentation for the SendBetterEmail action](https://unofficialsf.com/send-better-email-flow-action/)? Correcting it to close this issue would be fine by me.

**Comment by jdpond** [comment]
Will change the documentation to warn about this limitation
