### ISSUE TITLE
*Datatable* - Picklist - Showing API Name in edit mode instead of value

### ISSUE THREAD

**Issue by jumboxue** [alexed1/LightningFlowComponents#789]
![image](https://user-images.githubusercontent.com/14865228/123241191-0a6f9580-d535-11eb-88e8-36252f864f69.png)
Occupation is a picklist with Values (Abattoir Worker etc.) and API Names (36071, 36072 etc.).
For a row, it could display the correct label in read mode.
But in edit mode, the dropdown list will list API Names instead of values. 
(36071 is the API Name for value "Abattoir Worker").
Hope we could fix it very soon.

Datatable version: 3.2.3.

**Comment by ericrsmith35** [comment]
This has been fixed in v3.2.4
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/

The dropdown picklist values when editing will show the picklist labels instead of the picklist API names (The selected edit prior to selecting Save will show as the API name)
