### ISSUE TITLE
Unable to assign null value in lookupFSC

### ISSUE THREAD

**Issue by RBurcher** [alexed1/LightningFlowComponents#79]
I have a screen which contains three different lookupFSC components within it.  Two of these are required so a value must be entered and the remaining one is optional and it is possible for it to be null.  When testing this flow it has trouble when the lookupFSC contains a null value.

The O1_Output Value is set to populate CaseCreate.Transfer_Team__c however the debug log shows that when this field is not populated during the screen it is set as follows:
![image](https://user-images.githubusercontent.com/44418913/47398138-42741880-d78f-11e8-898c-02154ebc2192.png)

Then when the record is created further down the flow the null value in the above lookupFSC creates an error:
![image](https://user-images.githubusercontent.com/44418913/47398161-56b81580-d78f-11e8-83d8-99786cd8745a.png)

I've tried setting the default value to the global constant empty string, but that doesn't seem to work either.  Is there any way I can pass a null value into this variable if no value is chosen in the lookupFSC?

Thanks
Rach

**Comment by ericrsmith35** [comment]
Try setting the O1_Output Value to a flow variable.  Then use the variable in your Record Create node.

**Comment by RBurcher** [comment]
@ericrsmith35 , the O1_Output Value is setting a flow variable.  This is setting a field within an sObject variable which works for the other 2 lookupFSC's that I have on the same screen.  Are you saying that I need to create a dedicated variable just to collect this value in order to create a record containing a null value?

**Comment by ericrsmith35** [comment]
Either that or you could use a Decision node to check for a null value before your record create.  Is the field defined as available in the sObject?

**Comment by RBurcher** [comment]
@ericrsmith35, I managed to get it working using a dedicated variable and not the sObject variable

**Comment by ericrsmith35** [comment]
@RBurcher I'm glad you have it working now.
