### ISSUE TITLE
*Datatable* - Formula Field - Apex Action Error not editable

### ISSUE THREAD

**Issue by SgtSkyfall** [alexed1/LightningFlowComponents#790]
1. Select Formula Field for datatable from field picker
2. Press Next 
3. 3.Voila our error appears

**Comment by SgtSkyfall** [comment]
![image](https://user-images.githubusercontent.com/86478302/123432997-47866700-d5cb-11eb-947b-100623e3cd56.png)

**Comment by ericrsmith35** [comment]
This error is related to orgs with Multi-currency enabled.  I will have it fixed in the next release (v3.2.4).

**Comment by SgtSkyfall** [comment]
You are the best :) love the flow pack, better than Salesforces own

**Comment by ericrsmith35** [comment]
This has been fixed in v3.2.4
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/
