### ISSUE TITLE
Data Table - please confirm license

### ISSUE THREAD

**Issue by rjfay** [alexed1/LightningFlowComponents#794]
**Is your feature request related to a problem? Please describe.**
The Data Table directory does not include an explicit usage license (e.g. BSD-3-Clause or MIT), so I'm unsure whether we can use it for a project.

I see that the top level of the repository uses the BSD-3-Clause license, but I don't know if that applies to all components within the repository.

**Describe the solution you'd like**
Please add a note to the Data Table README confirming which license applies to this component.

Alternatively, if the BSD-3-Clause License applies to all projects within the LightningFlowComponents repository, please state this within the top-level README.

**Describe alternatives you've considered**
N/A - unable to use code without a license.

**Additional context**
Really appreciate all work done done by the different contributors to this repository.  Thank you!

**Comment by alexed1** [comment]
I just added this line "This license applies to all code in this LightningFlowComponents repository."
https://github.com/alexed1/LightningFlowComponents/blob/master/LICENSE

Does that give you the coverage you need?

**Comment by rjfay** [comment]
Thanks @alexed1, hero!
