### ISSUE TITLE
SendBetterEmail - NullPointerException after upgrade to version 2.1.3

### ISSUE THREAD

**Issue by ashley-clement** [alexed1/LightningFlowComponents#797]
### Expected behaviour
Email sends

### Actual behaviour
I had a flow working in version 2.1. After upgrading to 2.1.3, I get a apex error "System.NullPointerException: Attempt to de-reference a null object" 

### Debug Logs
If applicable, please insert debug logs here
<details>
<summary>Debug Log Information</summary>

Error element SendEmail (FlowActionCall).
An Apex error occurred: System.NullPointerException: Attempt to de-reference a null object 
________________________________________
Flow Details
Flow API Name: Scheduled_Epic_Training_Scheduled
Type: Autolaunched Flow
Version: 7
Status: Inactive
Org: Ochsner Health (00D1b00000092jX)
Flow Interview Details
Interview Label: Scheduled Epic Training Scheduled 6/28/2021 4:53 PM
Current User: Automated Process (0051U000002v3X4)
Start time: 6/28/2021 4:53 PM
Duration: 0 seconds
How the Interview Started
Automated Process (0051U000002v3X4) started the flow interview.
API Version for Running the Flow: 52
GET RECORDS: GetAppSec
Find all Application_Security__c records where:
1. Training_Status__c Equals Scheduled
2. Training_Status__c Equals E-learning assigned
3. Epic_Security_Status__c Does not equal Complete
4. Training_Scheduled_Email_Sent__c Equals false
5. Training_Status__c Equals E-learning needed
6. Class_Date_Time__c Greater than {!f_now} (6/28/2021 4:53 PM)
7. Hire_Date__c Greater than {!f_today} (June 28, 2021)
with advanced logic ((1 OR 2 OR 5) AND 3 AND 4 AND (6 OR 7))
Store the values of these fields in GetAppSec: Employee__c, Class_Date_Time__c, Id, Hire_Date__c, Training_Scheduled_Email_Sent__c
Result
Successfully found records.
GET RECORDS: Get_Org_Wide_Email
Find one OrgWideEmailAddress record where:
DisplayName Equals IS Training Team
Result
Successfully found record.
{!var_replyToEmail} = istraining@ochsner.org
{!var_orgWideEmailId} = 0D21b00000003LWCAY
GET RECORDS: Get_Non_Provider_Email_Template
Find one EmailTemplate record where:
Name Equals Epic Training Scheduled VF
Result
Successfully found record.
{!var_nonProvEmailTempId} = 00X1b000000F2pZEAS
LOOP: Loop_App_Sec
Loop Through: [a3k1b000000C6tqAAC]
Iteration: 0
Current iteration item: a3k1b000000C6tqAAC
DECISION: Send_Email
Outcome executed: Yes
Outcome conditions: 
1. {!Loop_App_Sec.Employee__r.Email} (ashley.clement@ochsner.org) Is null false
2. {!f_dateToCompare} (July 5, 2021) Less than {!f_8daysDate} (July 6, 2021)
Logic: All conditions must be true (AND)
DECISION: Record_Type
Outcome executed: Ochsner_Employee
Outcome conditions: 
{!Loop_App_Sec.Employee__r.RecordType.Name} (Ochsner Employee) Equals Ochsner Employee
SENDBETTEREMAIL (APEX): SendEmail
Inputs:
recordId = {!f_appSecId} (a3k1b000000C6tqAAC)
replyEmailAddress = {!const_replyToEmail} (ISTraining@ochsner.org)
saveAsActivity = true
senderDisplayName = {!const_SenderName} (Epic Training)
SendTOthisOneEmailAddress = {!f_recipientEmail} (ashley.clement@ochsner.org)
templateTargetObjectId = {!f_recipientId} (0031b00000lLsYCAA0)
templateID = {!var_nonProvEmailTempId} (00X1b000000F2pZEAS)
________________________________________
Error Occurred: An Apex error occurred: System.NullPointerException: Attempt to de-reference a null object 
________________________________________
Transaction Rolled Back
Because an error occurred, any records that the flow was ready to create, update, or delete weren’t committed to the database.
________________________________________
Salesforce Error ID: 1683571538-201511 (-856572903)

</details>

**Comment by jdpond** [comment]
@ashley-clement Do you have a copy of the apex error email?

**Comment by jdpond** [comment]
@ashley-clement I found this - completely my bad - was a release/typo error.  Will fix it and see if @alexed1 can do an emergency release for us.

**Comment by ashley-clement** [comment]
That's great. I had copied the content from the flow error email into the original post (debug logs section). I also wanted to mention, that the link for 2.1.4 and 2.1.3 are the same, so 2.1.3 was the latest release that I could install in my org.

**Comment by jdpond** [comment]
@ashley-clement

If you want to do a quick check and see if this was it, Line 87 of Class SendBetterEmail (in developer console) should be:
                if (curRequest.templateTargetObjectId != null) {

**Comment by ashley-clement** [comment]
Yes, that was the culprit!

**Comment by jdpond** [comment]
@ashley-clement, @alexed1 processed the pull request, merged and created a package.  He also updated the Post:  Could you check and make sure this was your problem (it certainly was a problem for many).
The package is at https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G0000047xLtQAI, which is the same as the post link for 2.1.15.
[Send Rich Email (Send HTML Email Action)](https://unofficialsf.com/send-rich-email-with-the-new-sendhtmlemail-action/)
