### ISSUE TITLE
*Datatable* - Inline Editing - Inline edits are not persisting changes in memory when clicking save or tabbing

### ISSUE THREAD

**Issue by zathchris** [alexed1/LightningFlowComponents#801]
1. Go to a datatable with version 3.2.4 and an editable number field.
2. Enter a number click save or tab. 
3. The number resets to what the datatable originally started with.

### Expected behavior
The data table should commit the field edit to memory until leaving the current flow screen. (I have attempted this with datatable v2 and it works as intended)

### Actual behavior
90% of the time, the edit is not saved and the original value in the datatable is reloaded. Occasionally, it does save when using the save button but you have to click it perfectly in the middle.

I have recorded a comparison of Datatable v3.2.4 as the top table and Datatable v2 as the bottom table.
[2021-06-30 16.31.01 Datatable Bug.zip](https://github.com/alexed1/LightningFlowComponents/files/6743891/2021-06-30.16.31.01.Datatable.Bug.zip)

**Comment by ericrsmith35** [comment]
I tried to reproduce this in a couple of different orgs but was unable to experience the behavior you are having.

Does this still occur if you activate the flow and run it from a Lightning Page instead of in debug mode?

Have you tried creating a new flow with different fields to see if it happens again?

**Comment by zathchris** [comment]
@ericrsmith35 Activating the flow and running in the UI did not work, however, creating a new flow from the existing version and rebuilding the datatable seems to have solved the problem. I did upgrade from 3.2.1 - 3.2.4 yesterday so something may have been corrupted in the existing tables.
