### ISSUE TITLE
Dependent Picklist Assignment

### ISSUE THREAD

**Issue by anoynay** [alexed1/LightningFlowComponents#81]
Hi,
I cant find where to post this. This is not an issue by the way but a possible enhancement which could be benefited by some of our users.

Can we make this new plugin to be more dynamic when we talk about dependent picklist?
Can make it possible to assign multiple dependent picklist for a specific Parent choice 1?
We have this scenario where if we select Parent Choice 1 for example, two individual picklist should display.

Thanks.

**Comment by alexed1** [comment]
Good idea.

**Comment by adwhite75** [comment]
Closing this because we can likely achieve this with Component Visibility - feel free to reopen if I missed the mark
