### ISSUE TITLE
Datatable  - lwc not responsive

### ISSUE THREAD

**Issue by PhilippReinholdMaag** [alexed1/LightningFlowComponents#814]
Hi,

since the latest release, the table overflows and is no longer in-line with neither the boarder of the lwc nor with the "boarder" of actual screenflow:

Screenflow on Lightning Page:

![Bildschirmfoto 2021-07-15 um 10 16 43](https://user-images.githubusercontent.com/69080199/125754489-92ec051c-d667-40d4-b3d3-3e4eb4e57dc7.png)

Screenflow launched from Actions & Recommendations in Console App: 

![Bildschirmfoto 2021-07-15 um 10 22 02](https://user-images.githubusercontent.com/69080199/125754665-84fe01ab-af0e-414e-bf91-bd5ad963d367.png)

Cheers

**Comment by ericrsmith35** [comment]
What version are you running?  Have you set a value for the Table Height attribute?

**Comment by PhilippReinholdMaag** [comment]
Hi,

I run: Datatable Version #: 3.2.4
Table Height attribute is empty.


My other **enabled** Settings:

- Show Row Numbers
- Show navigation links on Name fields
- Open links in the same Tab

**Comment by ericrsmith35** [comment]
You must set a value for the Table Height attribute in the Advanced section in order to disable the table overflow.

I will be creating a separate setting for this in a future release.

**Comment by PhilippReinholdMaag** [comment]
The additional setting works great. Thanks a lot!
