### ISSUE TITLE
Standard Salesforce Object not supported by Datatable? 

### ISSUE THREAD

**Issue by eberenguerv** [alexed1/LightningFlowComponents#819]
Hi, 

When trying to use the Datatable component on a Salesforce instance with HealthCloud enabled, I've tried to show the contents of the object "MedicationRequest" (https://developer.salesforce.com/docs/atlas.en-us.health_cloud_object_reference.meta/health_cloud_object_reference/hc_r4_api_objects_MedicationRequest.htm) using the datatable and salesforce throws the following error:
An Apex error occurred: System.QueryException: sObject type 'MedicationRequest' is not supported.

The email is also followed by:

USF_GETFIELDINFORMATION (APEX): Get:Field_Information_usf
Inputs: 
ObjectName= {!vSObject} {MedicationRequest}
Outputs:
{!apexColFieldDescriptors_usf}=fields([FieldDescriptor:(Error rendering usf.FieldDescriptor), FieldDescriptor: (Error rendering: usf.FieldDescriptor), FieldDescritptor: (Error rendering: usf.FieldDescriptor)]

I've tried to query the object with the same user via developer console and the tooling api, without issues. Any clues which could be the problem?

Thanks,

**Comment by Marcoparigi** [comment]
Using a Custom Object and only display outputSelectedRows on the next screen, it works
Using Standard SF Object it won't.
It raises me the following error : 

_Unfortunately, there was a problem. Please try again. If the problem continues, get in touch with your administrator with the error ID shown here and any other related details. Error ID: 2136248563-21238 (2127287436)_

**Comment by ericrsmith35** [comment]
@alexed1 Is there something unique I should be checking for here?  I don't have access to a HealthCloud org to test.

**Comment by BreakingGood** [comment]
MedicationRequest is API version 51+. From what I can tell, these components are not yet on that API version.

**Comment by ericrsmith35** [comment]
MedicationRequest does not appear in the list of Standard Salesfoce Objects for API 52.0.  https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_list.htm

**Comment by samwolfe40** [comment]
I can confirm bumping API version to 52 fixed this issue on the Quicklookup component. (Same error, different health cloud object: HealthcareFacility)

https://github.com/alexed1/LightningFlowComponents/tree/master/flow_screen_components/quickLookup

**Comment by alexed1** [comment]
Which specific place did you change to 52?

**Comment by samwolfe40** [comment]
> 
> 
> Which specific place did you change to 52?

https://github.com/alexed1/LightningFlowComponents/blob/master/flow_screen_components/quickLookup/force-app/main/default/classes/QuickLightningLookupController.cls-meta.xml

This file (which in my environment was API version 38.0 because [this commit](https://github.com/alexed1/LightningFlowComponents/commit/cab6a5beec85cb79f6111785d38c166d99906945#diff-aa90a08592f3059f68d06c37a5c123a3ed8e55fa6a09bbdbf2b028433d53ad48) is either not released yet or I just didn't have the latest update.

**Comment by ericrsmith35** [comment]
One work-around for Datatable might be to manually enter your fields and column configurations in the advanced section.

**Comment by ericrsmith35** [comment]
API 52.0 has been implemented in the latest release of Datatable (v3.3.2)
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/
