### ISSUE TITLE
*FLOW ACTION BASE PACK* - _({!ElementName})_ -INSTALLATION ISSUE 

### ISSUE THREAD

**Issue by xsudiptaster** [alexed1/LightningFlowComponents#824]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.
* 
I am unable to update the FLow Action Base pack, the current version I have been using is 2.18. Get the following error 

### Steps to reproduce

Managed Package Link 
Click on the link to install

"The currently installed version does not share a common ancestor with this version."
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Debug Logs
If applicable, please insert debug logs here
<details>
<summary>Debug Log Information</summary>

```
Paste the output of the logs here.
```
</details>

**Comment by alexed1** [comment]
Unfortunately the packaging of 2.18 was screwed up and there's no way to upgrade from it.  You'll have to uninstall it manually. I know this can be really painful. Versions after 2.18 will not have this upgrade problem. The packaging problem that led to this has been brought to the attention of the packaging team at Salesforce. I apologize for the inconvenience.
