### ISSUE TITLE
lookupFSC - set a default on child component

### ISSUE THREAD

**Issue by KreGab** [alexed1/LightningFlowComponents#84]
Hi,

unfortunatly the SOQL statement doesn't work properly. Whenever the default is, set the Where-clause in the log displays "[SELECT Id,Name FROM Contact WHERE Name='<default>' AND AccountId='<AccountId'];.
The default will not be overwritten. This is my configuration:

![lookupaccount](https://user-images.githubusercontent.com/44999577/48407247-a5c1ec80-e736-11e8-9d83-5351d1a74235.PNG)
![lookupcontact](https://user-images.githubusercontent.com/44999577/48407249-a78bb000-e736-11e8-8c9a-a3eed63eb26f.PNG)
![where-clause](https://user-images.githubusercontent.com/44999577/48407251-a8244680-e736-11e8-8bae-4fae75e9b30b.PNG)

Is this my fault or a bug? Thanks for your help!

regards
Gabriel

**Comment by ericrsmith35** [comment]
Add the I6_Filter on which Field parameter to your Child lookup and you should be all set.
![image](https://user-images.githubusercontent.com/24724447/48411775-98920700-e710-11e8-8b38-1dc0a2ec3acc.png)

**Comment by KreGab** [comment]
Thanks for your fast answer. I set the I6_Filter on which Field paramter but it still doesn't work.
![lookupcontacti6](https://user-images.githubusercontent.com/44999577/48412393-c6913e80-e744-11e8-875c-728fb27f0368.PNG)
![where-clausebleibt](https://user-images.githubusercontent.com/44999577/48412402-cd1fb600-e744-11e8-9248-2869d9011b54.PNG)

It realy is sad because the default functionallity works fine on the account lookup.

**Comment by ericrsmith35** [comment]
Remove the Default Value on the Child lookup.  You should then get a dropdown list with only those Contacts that are related to the Account selected in the Parent lookup.
