### ISSUE TITLE
*Quick Choice* - Visual Card/Radio Button Group - Selection Bug w Multiple Components on One Screen

### ISSUE THREAD

**Issue by jncart** [alexed1/LightningFlowComponents#846]
### Steps to reproduce

1. Create a Screen element
2. Add two or more Quick Choice components to the screen
3. Configure the components for either Visual Card or Radio Button Group
4. Run the screenflow
5. Click a card/radio button from the first component so that it is active
6. Click a card/radio button from the second component

### Expected behaviour
The active/selected option in the first instance of the component should retain the active value when the second component is clicked.

### Actual behaviour
The active/selected option in the first instance of the component is cleared. No matter how many Quick Choice components there are on a page, only one option can ever be active.

### Screenshots

![quickchoicebugvid1](https://user-images.githubusercontent.com/87152637/128552992-b22dae52-7842-4b3b-84e2-b72a11d943d3.gif)

![quickchoicebugvid2](https://user-images.githubusercontent.com/87152637/128553023-2311ff4a-11fd-449e-9fcf-9483fdd79c23.gif)

**Comment by ericrsmith35** [comment]
Are you using the QuickChoice component from the most recent version of the FlowLightningComponentsBasePack?
https://unofficialsf.com/flow-action-and-screen-component-basepacks/

**Comment by jncart** [comment]
> Are you using the QuickChoice component from the most recent version of the FlowLightningComponentsBasePack?
> https://unofficialsf.com/flow-action-and-screen-component-basepacks/

Confirmed that I am running FlowScreenComponentsBasePack 2.5.1 and FlowActionsBasePack 2.2.9.

**Comment by jncart** [comment]
A couple additional observations: 

1. Even though the previously selected option no long appears to be active, the select Value is still recorded as an output.
2. The bug is also observed if you have a component set to Visual Card and another set to Radio Button Group.

**Comment by ericrsmith35** [comment]
I don't see how the configuration you show in the first graphic matches the
behavior in the second.  If you are providing the same collection values
for the Labels and the Descriptions(Values), both will show on the Visual
Card.

**Comment by ericrsmith35** [comment]
https://user-images.githubusercontent.com/24724447/128570286-a8b92443-edc2-4c3d-a558-28b442964e34.mp4

**Comment by ericrsmith35** [comment]
https://user-images.githubusercontent.com/24724447/128570507-e8ad56fc-c84d-4fe5-9992-6dcc2cd12044.mp4

**Comment by jncart** [comment]
I had overridden some CSS in the second graphic to hide the value line for reasons unrelated to this issue.

Here's an updated set of recordings:

![quickchoicebugvid3](https://user-images.githubusercontent.com/87152637/128572172-821b8626-5cae-44ae-83f0-91acbec9db0a.gif)

![quickchoicebugvid4](https://user-images.githubusercontent.com/87152637/128572138-1e7d5973-a2e9-4468-803e-afeae567ad7f.gif)

Based on your videos, the component is working fine for you, so that suggests the issue may be related to the configuration of my browser.

**Comment by ericrsmith35** [comment]
Do you still have an old version of Quick Choice installed?  The issue you are having did occur in earlier releases of the component.

**Comment by jncart** [comment]
The previous recordings are from an org that does have the old FBC package with the old Quick Choice installed. I'm confident that I was using the new version from the FSC package.

I have tried this again in a separate dev environment that does not have FBC or the old Quick Choice stand-alone package installed, and I am seeing the same result.

<img width="1702" alt="installedPackagesDevEnviro" src="https://user-images.githubusercontent.com/87152637/128574095-0e58ff62-d5f7-435a-a684-0579d94352c7.png">


![quickchoicebugvid5](https://user-images.githubusercontent.com/87152637/128574055-3d5f8d59-4c5a-49f5-a184-21ac58d758da.gif)

**Comment by ericrsmith35** [comment]
Could you atrtach a file with the flow metadata from your test flow and I'll put it in my org and give it a try?

**Comment by jncart** [comment]
[Quick_Choice_Test.flow-meta.txt](https://github.com/alexed1/LightningFlowComponents/files/6948112/Quick_Choice_Test.flow-meta.txt)

**Comment by ericrsmith35** [comment]
Sometimes it is the smallest things.  The component differentiates between multiple components on the same page by looking at the Master Label of each component.  If multiple components have the same Master Label (in your case null) they will be treated as a single radio group.  Provide each component with a unique Master label and you should be all set.

**Comment by jncart** [comment]
That was definitely the issue. Thanks!
