### ISSUE TITLE
SendBetterEmail - Allow Deployment if Enhanced Email Disabled

### ISSUE THREAD

**Issue by jimletts** [alexed1/LightningFlowComponents#855]
**Is your feature request related to a problem? Please describe.**
SendBetterEmail v2.0.4 introduced a dependency on Enhanced Email,  in test method t031_canSendEmailwithInReplyTo. This dependency prevents installation in an org with Enhanced Email disabled since the EmailMessage object is not available in that scenario. The EmailMessage object is used only in the test method, and nowhere else in the package.

**Describe the solution you'd like**
The test validates that a messageIdentifier can be put in the SendBetterEmailRequest().InReplyTo field, but does not confirm that the resulting message is actually threaded to the original method. The messageIdentifier is currently created by sending a SingleEmailMessage to create a valid messageIdentifier. Since the only [requirement for such an identifier](https://datatracker.ietf.org/doc/html/rfc2822#section-3.6.4) is that it be unique and correctly formatted, it should be sufficient for test purposes to create a string of 
`'<' + String.valueof(DateTime.now().getTime()) + '@foo.com.invalid>'`

**Describe alternatives you've considered**
I can't see any alternatives since the package does not install with that reference unless Setup > Email > Enhanced Email is enabled.

**Additional context**
Here is the error email on the failed install:
```
Your request to install package "SendBetterEmail ver 2.0.6" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected. 

If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information. 

Organization: XXX (XXX) 
User: XXX (XXX) 
Package: SendBetterEmail (04t5G000003rUZT) 
Error Number: 179535045-29977 (-810699787) 
Problem: 

1. Invalid type: EmailMessage 
SendBetterEmailTest: Invalid type: EmailMessage 

2. Variable does not exist: MessageIdentifier 
SendBetterEmailTest: Variable does not exist: MessageIdentifier 
```

**Comment by jdpond** [comment]
@jimletts - thanks for the observation and posting.   Perhaps a simple solution would be to turn on Enhanced Email before installing and then turn it off afterwards?  This arose in #595.  Could I get opinions from @munawirrahman and @alexed1?  Perhaps just turn off this test?  Would lower coverage.

**Comment by jdpond** [comment]
@jimletts after looking at this, there are many other dependent features in sendBetterEmail require Enhanced Email (Save as Activity, Save as Task, . . .).  Maybe we should just update the sendBetterEmail documentation for Enhanced Email enablement to be a requirement?

**Comment by jimletts** [comment]
My client has a fairly complex configuration and is reluctant to use anything that requires them to be "special". This includes special forked versions of community-maintained packages or "special" install sequences. And their instance is old/hairy enough that they really don't want to turn on something when they are not certain of any side effects.

As you suggested, I tried enabling Enhanced Email (EE) long enough to install it in my dev org then disabled it again. I then updated the test class to use a random messageIdentifier rather than one based on a prior EmailMessage. At this point, the entire test suite passed even with EE disabled. Not conclusive, but it did make me wonder what functionality might be dependant on EE. 

I assume you are correct, but having read through the code, I haven't been able to locate any explicit dependencies on EE. The "save as task" and "save as activity" features seem not to care about EE. Not only do their tests pass with EE disabled, but the implementation seems to just mirror the content from the request rather than pulling it out of the EmailMessage object. Even more telling, since Messaging.SendSingleEmail

I'm happy to put together a PR to remove the test's dependence on EE. Would you expect that there are additional tests/criteria that I'd need to create beyond what is already in place to ensure that EE is not actually required?

**Comment by jdpond** [comment]
How about this - we can check in Test t031_canSendEmailwithInReplyTo if the Object EmailMessage is not available, then do not exercise the code in Test 31.  This would work if it is only Test 31 that is giving you problems:
```
if (Schema.getGlobalDescribe().get('EmailMessage') != null){
. . .
. . .
}
```

**Comment by jimletts** [comment]
The problem is at install(compile) time, not at run time because the EmailMessage object doesn’t even exist in the available schema when Enahanced Email is disabled. 

I believe we'd need to replace (at 1122)
```
list<EmailMessage> emailMessageIds = [SELECT Id,MessageIdentifier FROM EmailMessage limit 1];
testReq.InReplyTo = new List<String> {emailMessageIds[0].MessageIdentifier};
```
with
```
list<String> emailMessageIds = Database.Query('SELECT MessageIdentifier FROM EmailMessage limit 1');
testReqInReplyTo = new List<String>(emailMessageIds[0]);
```

Would that be more appropriate?

**Comment by jdpond** [comment]
That would still fail, wouldn't it?  It will still try and do the query and then come up with (attempt to assign to null)

**Comment by jdpond** [comment]
And the answer is:

```
if (Schema.getGlobalDescribe().get('EmailMessage') != null){
. . .

    list<SObject> emailMessageIds = (List<SObject>) Database.Query('SELECT MessageIdentifier FROM EmailMessage limit 1');
    testReq.InReplyTo = new List<String>{((String) emailMessageIds[0].get('MessageIdentifier'))};

. . .
}

```

Tried and tested this AM - This will be included in the next release.  You can find it at:
[jdpond/LightningFlowComponents - SendBetterEmail](https://github.com/jdpond/LightningFlowComponents/blob/master/flow_action_components/SendBetterEmail/force-app/main/default/classes/SendBetterEmail.cls)

**Comment by jimletts** [comment]
Ah - Good. Solves for both EE enabled during install but then disabled as well as installing while EE is disabled.
