### ISSUE TITLE
SendBetterEmail - CPE - Error When Selecting a Value from a Record Variable

### ISSUE THREAD

**Issue by Garywoo** [alexed1/LightningFlowComponents#856]
While setting values in the CPE fields within the action, if you try and use a value from a record variable (i.e. `VarOppoprtunity.Id`), the following error occurs:

> Something went wrong  
> Save your flow and refresh the page. If the problem persists, contact Salesforce Customer Support. Error ID: -901016616.
> 
> If you're working on a screen component, check your component configuration for invalid values.

```
This page has an error. You might just need to refresh it. [LWC component's @wire target property or method threw an error during value provisioning. Original error: [Cannot read property 'toLowerCase' of null]] Failing descriptor: {markup://c:fsc_flowCombobox}
```

This occurs both when adding new actions, and when editing existing actions. The error occurs when selecting a record variable in any of the CPE fields.

### Steps to reproduce

1.  In a new flow, add a new record variable for any object, i.e. opportunity
2.  Add the SendBetterEmail action
3.  Click in any field in the CPE, i.e. Sender Display Name, and click the > next to the record variable

### Expected behaviour

*   The record variable expands, and you can select a field from the object.

### Actual behaviour

*   The reported error occurs.

### Screenshots

Here's the error occurring:

![](https://user-images.githubusercontent.com/10392194/128894464-62ee9bb6-7de3-4836-b8e2-6e9329ba8f70.gif)

### Environment

*   SendBetterEmail - 2.1.6
*   FlowActionsBasePack - 2.31
*   FlowScreenComponentsBasePack - 2.5.3

**Comment by jdpond** [comment]
Uggh.  I saw this in testing, then it mysteriously disappeared.  @ericrsmith35 Can you help me look at this one?

**Comment by jdpond** [comment]
I tested this with String, StringCollection, and Object Collection (CDL) in the release test environment for 2.1.6.  Seemed to work.  Could this be something with Opportunity?
[Tested in Scratch Box Video](https://user-images.githubusercontent.com/271131/128907545-5919809c-86f0-451c-bbd3-e3da5da0513d.mp4)

**Comment by Garywoo** [comment]
@jdpond Yes, I upgraded both Flow Actions Base Pack and the Flow Screen Components Base Pack to the latest versions today before upgrading SendBetterEmail. This is when I started noticing the issue occurring.

The issue is occuring for any object in the record variable, not just opportunities. I also tried leads, and accounts.

I believe that objects records should continue to be selectable in these fields. I noticed the error because I was trying to set the "Related Record Id" field to the ID of an opportunity.

**Comment by ericrsmith35** [comment]
@alexed1 Could this be an issue with the latest updates to FlowCombobox?

**Comment by alexed1** [comment]
Could be. Can you create an account for me on an org where this reproduce consistently?

**Comment by jdpond** [comment]
@Garywoo could you connect with me on salesforceohana.slack.com?

**Comment by Garywoo** [comment]
Sorry @jdpond, I'm unable to join that Slack workspace. Signups are limited to Salesforce related domains only. Perhaps you can send me an invite? My GitHub profile has a link to my Twitter, and my DMs are open.

**Comment by Garywoo** [comment]
Just got off the phone with @jdpond. It seems the core issue here is with the FlowCombobox component.

It's worth noting that the issue can be worked around if you paste in the full path to the field you want in the variable, into the CPE field, e.g. `{!VarOpportunity.Name}`. Typing it manually causes the error to occur upon every keypress after the variable name, so pasting the path avoids this.

@ericrsmith35 I was able to reproduce the same error in the QuickChoice component. Selecting the > button to the right of the record variable name causes the same error to occur. 

![](https://user-images.githubusercontent.com/10392194/129267173-dc7ea587-1cfb-4326-8de1-9c1790f555ae.png)

Also, it appears that the releases for FlowActionsBasePack v2.31 and FlowScreenComponentsBasePack v2.5.3 have been rolled back, as they are no longer listed on the [UnofficialSF page](https://unofficialsf.com/flow-action-and-screen-component-basepacks/).

**Comment by Garywoo** [comment]
I have submitted a new issue (#861) to more accurately track the root cause of this problem. We discovered that this error is not exclusively with SendBetterEmail, but rather with the Flow Combobox component within the FlowScreenComponentsBasePack package, which is used in the CPE of the SendBetterEmail action.

**Comment by jdpond** [comment]
I am closing this one - will reference it in #861
