### ISSUE TITLE
DataTable - Apex Action error: unable to read SObject

### ISSUE THREAD

**Issue by jkurant** [alexed1/LightningFlowComponents#858]
I would like to use the DataTable v3.3.0 to allow the user to specify the quantity and price on some products. I have a screen flow that iterates over a list of products, which are Product2 objects, and for each one, it creates a record in a record collection of a different object. I created this object as a temporary place to store the user's choices. So, I wanted to create in memory, in a record collection variable, the list of products, each with a quantity and price. The Product2 object does not have quantity and price, so I created an object Special Charges and I wanted to loop over the products creating a Special Charge for each one and adding to a record collection. But no matter what I do, I get the following error when it gets to that screen: Apex Action error: unable to read SObject.

So, is this possible? In my loop a set the field values on a single-record variable and then I add that to my record collection variable. These are Special Charges records. But when it gets to the screen, it fails with that error. 

Am I using this correctly? I think the issue might have to do with IDs, but DataTable can handle new records that don't have IDs, so I am not sure why this error is happening.

**Comment by ericrsmith35** [comment]
If you are creating records in the flow and not committing them to the database and reading them back, you will need to provide a unique dummy Id for each of your new "records".  The id must start with the same first 3 characters as the normal record Id does for the Special Charge object.

For example if you were creating 3 Opportunity records in the flow, they would need the following values for their Id fields.  006000000000001, 006000000000002, 006000000000003.

**Comment by jkurant** [comment]
Thank you so very much, Eric! It is very kind of you to help and your code is fantastic!
