### ISSUE TITLE
Is there a way to adapt the NavigationButtonFSC to launch a subflow? 

### ISSUE THREAD

**Issue by cojilas** [alexed1/LightningFlowComponents#87]
Would like to be able to launch a second flow, and then come back to my original flow.

**Comment by ericrsmith35** [comment]
Your Flow can launch a subflow.  You don't need to use a Lightning Component for that.

**Comment by cojilas** [comment]
thanks @ericrsmith35  - but maybe I was not particularly clear....

What I want to be able to do is to use the button to set a variable (or a choice element) so that, if the user presses the button, the flow will go into a subflow (via a decision point), and if not, they will continue to the "normal" flow (via that same decision point). Is there a way to use the NavigationButtonFSC to set a choice or a variable element to do that?

**Comment by ericrsmith35** [comment]
You can do this directly in your original flow without having to use a Lightning Component

**Comment by alexed1** [comment]
@cojilas what if you just added a checkbox to your screen with the label "launch the sublow?" (or whatever). Then you check the status of that checkbox. Another thing that might work well here is the new Toggle component.

**Comment by alexed1** [comment]
@cojilas Upgraded this component to enable you to do what you want. See https://sites.google.com/view/flowunofficial/flow-screen-components/navigation-button
