### ISSUE TITLE
Quick LookUp - Clearing Parent Value

### ISSUE THREAD

**Issue by CultechPtyLtd** [alexed1/LightningFlowComponents#875]
### Steps to reproduce

1. On Parent Lookup, search and select a record.
2. On Child Lookup,  search and select a record.
3. Clear the Parent record.
4. Clear the Child record. 
5. Searching on child record still filters via the previous Parents value instead of null

### Expected behaviour
The Parent record should clear its value after clearing out the lookinig and thus clears out the Child filtering value. My use case I'm using the Parent as a Filter for the Child lookup. Sometimes you want to add a filter and remove the filter while searching throught the Child lookip.

### Actual behaviour
This bug doesn't allow the user to clear out the filter for the Child record.

### Screenshots
<img width="485" alt="Showing All Work Orders - No Parent" src="https://user-images.githubusercontent.com/73424220/130534788-5607a99a-c6f7-42e4-b742-5ad9a8bf6c1a.png">
^ Showing all child records, Parent filer not yet applied.
<img width="286" alt="Filtering WO, Parent Filter Added" src="https://user-images.githubusercontent.com/73424220/130534809-76a66122-c02e-4f81-93bf-f6e0ae0b93c7.png">
^ Filtering Child records, filtered by Parent record.
<img width="333" alt="Parrent Cleared, still filtering via previous parent value" src="https://user-images.githubusercontent.com/73424220/130534825-5de7a0fc-d208-4d8d-9b88-c7928675c4c0.png">
^ Clearing Parent record, Child still filtering by previous Parent value instead of null

**Comment by alexed1** [comment]
Fixed in version 1.1 thanks to @AndyHaas https://unofficialsf.com/lookup/
