### ISSUE TITLE
Quick Lookup - Pop-down not collapsing

### ISSUE THREAD

**Issue by CultechPtyLtd** [alexed1/LightningFlowComponents#878]
Issue: 
When clicking anywhere not on the component, the pop-down for displaying records down not collapse.

1. Click the lookup search field
2. A pop-down will appear for recent records. 
3. Click anywhere off the component

### Expected behaviour
When clicking anywhere not on the component, the pop-down should collapse.

### Actual behaviour
The pop-down does not collapse, which gets in the way of other components you may be trying to use which are directly below.

**Comment by AndyHaas** [comment]
@CultechPtyLtd 
I have made the changes to the component to close if the user clicks off the component.

**Comment by alexed1** [comment]
Fixed in version 1.1 thanks to @AndyHaas https://unofficialsf.com/lookup/
