### ISSUE TITLE
Datatable - Formula Field

### ISSUE THREAD

**Issue by allenmoy** [alexed1/LightningFlowComponents#882]
Formula text fields appear correctly in preview but are blank when running the flow to debug.

![Preview](https://user-images.githubusercontent.com/82619458/130871915-19898a28-0fb2-4c65-846c-703e53ff4ff4.PNG)
![Debug](https://user-images.githubusercontent.com/82619458/130871924-86573867-b38a-4575-98e5-8bb7d98d99ae.PNG)

**Comment by florebloes** [comment]
@ericrsmith35 I have the same issue at the moment for formula field of type number

**Comment by ericrsmith35** [comment]
The issue here was that the records were being added to a collection in the Flow then displayed in a datatable.  There were not first being written to the database and read back, therefore the formulas were not being calculated by Salesforce.

**Comment by iahmadezzat** [comment]
I have the same issue although the records are being fetched from the database, and I'm running on the last version of the datable v 4.1.4. Can you please assist on this?

**Comment by ericrsmith35** [comment]
You also need to confirm that the running user has full FLS access to all objects and fields referenced by the formula.
