### ISSUE TITLE
Make picklist editing simpler for user

### ISSUE THREAD

**Issue by njamison** [alexed1/LightningFlowComponents#883]
First of all, thank you for an awesome tool (Datatable). I use frequently and love it!

**Is your feature request related to a problem? Please describe.**
I am currently using Datatable version 3.3.0. When I use the datatable I experience this behavior in order to edit the value of a picklist:
1. Hover over field and click the pencil icon:
![image](https://user-images.githubusercontent.com/15808868/130873522-5b3f5c84-eece-4dd1-9f83-541b523db3fd.png)

2. If I try to click the down arrow (circled in red) to open up the options for the picklist it instead returns me to the view mode:
![image](https://user-images.githubusercontent.com/15808868/130873648-df6a0f97-33dd-4b3c-b150-8bb7f1ce1c40.png)
What I see after clicking the arrow:
![image](https://user-images.githubusercontent.com/15808868/130873804-16dd8260-80fc-40c3-962b-5dc322484999.png)

3.  Instead I have to click in the label (circled in green) area to view the options:
![image](https://user-images.githubusercontent.com/15808868/130873963-ccf24c90-b0e8-46da-9728-0b5c22d58eae.png)

**Describe the solution you'd like**
It would be great if clicking the down arrow displayed the list of options instead of returning the user to "view" mode.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JerrycsPoon** [comment]
hi @ericrsmith35  I've created a pull request for this fix: https://github.com/alexed1/LightningFlowComponents/pull/884

**Comment by ericrsmith35** [comment]
This will be released in Winter '22 with version 3.3.3
