### ISSUE TITLE
Load Web Page Local Action - How do i get it to load in a new tab/window?

### ISSUE THREAD

**Issue by cojilas** [alexed1/LightningFlowComponents#89]
Currently the LoadWebPage local action loads the URL into the same window as the flow. I would like it to load in a new window, so I could keep the flow active. Is this possible?

My URL is currently: https://mydomain.lightning.force.com/lightning/o/Event/home

**Comment by adwhite75** [comment]
Resolved with https://unofficialsf.com/new-ways-to-open-web-pages-from-flow/
