### ISSUE TITLE
Quick Choice FSC Enhancement: Small cards/visual picker

### ISSUE THREAD

**Issue by cadillacben** [alexed1/LightningFlowComponents#908]
If I use the visual cards option, even if I use extra small the cards are quite large.  I have a screen where I allow the user to pick the record type and there can be 8ish record types, so the extra size fills the screen quickly.  I like the cards because of the instant navigation.

I think what I'm after is the .slds-visual-picker component type.

**Comment by ericrsmith35** [comment]
There is no size option for the cards.  Have you tried 2 columns?

Another option would be to try this component.  appexchange | Flow Magic -
Picklists - Salesforce Labs - AppExchange
<https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3A00000FeFBAUA3>

**Comment by cadillacben** [comment]
Ah, I see that now.  The link mode doubles the card size and only the icon size can change, dang.

I do have it in two column mode, so I'm just being picky.  Thanks for the app tip, I'll take a look.

Thank you for all your hard work with these packages!
