### ISSUE TITLE
Respect Validation Rules

### ISSUE THREAD

**Issue by mwahd** [alexed1/LightningFlowComponents#910]
**Is your feature request related to a problem? Please describe.**
When a user uses the custom datatable and clicks on next I was wondering if there would be a feature to respect the validation rules on the object. I noticed in customDatatable.js there's a function called `handleCellChange` where it has a comment saying "// TODO - Add support for User Defined Validation Rules" Do you know when this feature will be worked on/released?

**Describe the solution you'd like**
When a user clicks next in the flow I would like the custom datatable to check the validation rules on the object prior to allowing the user to continue to the next screen.

**Describe alternatives you've considered**
Possibly creating a validation feature directly on the custom datatable to create validation rules directly on the column rather than using the validation rules on the object.

**Additional context**

**Comment by ericrsmith35** [comment]
You can check the Validation Rules from the Object with this separate component I created.  https://unofficialsf.com/validation-checker-flow-action/

**Comment by mwahd** [comment]
Thanks I was hoping if we could somehow utilize the error handling of the datatable, but since the output of the validation plugin is the list of errors we would have to go with the approach you suggested. Do you see any time in the future of integrating validation checking in the custom datatable or is that feature out of scope?

**Comment by ericrsmith35** [comment]
It could be in the future.  I'd certainly like to avoid making someone
recreate the same validation rules in multiple places.

**Comment by mwahd** [comment]
Awesome, thanks so much for your help!
