### ISSUE TITLE
Filter on checkboxes

### ISSUE THREAD

**Issue by Rwischne1** [alexed1/LightningFlowComponents#92]
Really more of a question than maybe an issue.

I tried to filter the lookup to users based on field IsActive and Filter Value TRUE. This did not work, I tried Yes and true also.

Any tips on how to filter the values based on a checkbox?

**Comment by ericrsmith35** [comment]
For now, create a formula field on IsActive that returns a text value and use that with the component.

**Comment by alexed1** [comment]
Thumbs up.
