### ISSUE TITLE
Datatable component (UnofficialSF): ability to translate error messages?

### ISSUE THREAD

**Issue by LIPV23** [alexed1/LightningFlowComponents#920]
@ericrsmith35 
Hi, 
I'm new to GitHub, so not sure where to post, but:
For the Datatable component (unofficialsf), I was wondering how error messages can be translated. I'm currently trying to find a way to translate the "This is a required entry. At least 1 row must be selected"-message.
Thanks.

**Comment by ericrsmith35** [comment]
I will convert this to a custom label in the next release.

**Comment by ericrsmith35** [comment]
This has been addressed in the latest release: v3.4.5
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/#Installation
