### ISSUE TITLE
SendBetterEmail - SendEmail - Can't select Mass email

### ISSUE THREAD

**Issue by Windyo** [alexed1/LightningFlowComponents#925]
Selecting "Mass Email" results in a failure to save with a warning that prevents activation.

### Steps to reproduce

1. Install SendBetterEmail on a new org.
2. Adda  new Action SendBetterEmail to a Flow
3. Save

### Expected behaviour
You can save and send emails massively

### Actual behaviour
(Action) - The type for the input parameter "emailMessageType" doesn't match the type for the assigned value.

### Screenshots
![image](https://user-images.githubusercontent.com/17938171/135321841-8e00d41f-2d24-4ce9-8624-e6f71adee7e0.png)
![image](https://user-images.githubusercontent.com/17938171/135321855-558a823a-da6f-463b-b7fa-759014f2b38a.png)

**Comment by Windyo** [comment]
@jdpond As requested by ric_hoo, tagging you here.

**Comment by Windyo** [comment]
Possibly related: Deplyoing a Flow using SendBEtterEmail via MDAPI results in
`field integrity exception: unknown (A required input parameter is missing: "whoId")`
`field integrity exception: unknown (A required input parameter is missing: "emailTemplateId")`

which are related to the email componnent. probably linked to data being lost on save

**Comment by CodeKoz** [comment]
Also happens with the Bulk Request feature(which is a great idea by the way)

@Windyo Did you find a workaround?

**Comment by Windyo** [comment]
Nope, I have a golive blocked by this and if it continues I'm paying a dev to reimplemnt it internally /shrug

Oct 6, 2021 09:10:09 CodeKoz ***@***.***>:

**Comment by CodeKoz** [comment]
Sure ! Can you send some timeslots ? I'm available from now to 5:30PM (EET) if you are too.

**Comment by Windyo** [comment]
Same, available at various times, feel free to suggest a few slots. Timezone here is GMT+1

**Comment by jdpond** [comment]
Send your contact to the email on my github account

**Comment by CodeKoz** [comment]
Hey Jack,

It seems to be ok on the environment. Created a simple flow and no error
messages.

Well done !

Le jeu. 14 oct. 2021 à 20:27, Jack D. Pond ***@***.***> a
écrit :
