### ISSUE TITLE
*Datatable 3.3.2* - Column attributes not available in communities

### ISSUE THREAD

**Issue by cadillacben** [alexed1/LightningFlowComponents#956]
### Steps to reproduce

1. add datatable to a screen flow
2. add to a community page
3. login as user and view table

### Expected behaviour
The columns should have attributes like wrap text clip text and set filter

### Actual behaviour
Zero attributes show, but you can sort by clicking the column name.  All appears fine if running in debug mode as a user, but when you're actually in the community the options are not there.

### Screenshots
Debug mode
![image](https://user-images.githubusercontent.com/17458691/139736029-7e81bcb2-42d8-478e-95b3-977a7f92803f.png)

In community mode
![image](https://user-images.githubusercontent.com/17458691/139736106-e198ed13-3243-4fdb-af31-44a4c6f041c5.png)

Table config
![image](https://user-images.githubusercontent.com/17458691/139736204-a657e9d8-5ddd-4204-bebd-ac06c23813be.png)

**Comment by cadillacben** [comment]
I also tried this with a guest user and a 'normal' community, but the result was the same.

**Comment by cadillacben** [comment]
I think this is related to something with this specific community, so it should be deprioritized.  Once I determine the root cause I will report back for awareness.

**Comment by cadillacben** [comment]
Update on the cause of this.  I've found it is something related to the Theme Layout Component the site is using.  I don't currently know the exact cause, but I suspect css although nothing jumped out at me.

@ericrsmith35

**Comment by ericrsmith35** [comment]
Thanks for keeping us updated.

**Comment by cadillacben** [comment]
We tracked this down to a community theme that was created and applied by a consultant.  Why you would ever hide this by default is beyond me, but this was the cluprit.

`.THIS .slds-table .slds-th__action-button {
  display: none;`
