### ISSUE TITLE
Quick Lookup - Child filter not respecting Parent Default Value 

### ISSUE THREAD

**Issue by CultechPtyLtd** [alexed1/LightningFlowComponents#962]
On your instructions you give 2 options for using default values. For Option Two, it's a matter of also populating the O1_Output Value. This works fine when you are not using any Child Lookups off the Parent. However, If you are using a child lookup then that lookup does not respect the populated defaulted value of the parent it is using for filtering. You have to clear the parent and reselect it in order for the Child to begin its filtering on that value.

Because of this, I am forced to use the Option One for the default value which is not ideal as its more steps for the user to complete.

Would be great to have the Child respected the Pre-populated/Default Output of the Parent.

**Comment by CultechPtyLtd** [comment]
This sort of ties into this bug I posted a while back:

https://github.com/alexed1/LightningFlowComponents/issues/875

**Comment by Megalithe** [comment]
I am encountering this issue in the lookupFSC and updating to the QuickLookup component did not resolve. As mentioned the filters/where clauses do not apply to child lookups by default. I have to clear and reselect the preceding value to force the lookup to apply.

**Comment by alexed1** [comment]
Fixed in version 1.1 thanks to @AndyHaas https://unofficialsf.com/lookup/
