### ISSUE TITLE
*Datatable* - Apex Action error: Unable to read SObject

### ISSUE THREAD

**Issue by hackbac** [alexed1/LightningFlowComponents#963]
Creating a Datatable using a collection of SObjects which is not yet committed to the database results in a browser error "Apex Action error: Unable to read SObject" 

Flow API Version 53.0

### Steps to reproduce

1. Create a Screen Flow
2. Add a single Record Resource ("SObject")
3. Add a record collection Resource ("Collection")
4. Add an assignment element, setting the Name attribute of SObject to "Test"
5. Add an assignment element, adding SObject to Collection
6. Add a Screen element
7. Add the datatable component
8. Set Data Source > "Select Object" to the SObject type
9. Set Data Source > "Display which records?" to the Collection resource
10. Set Advanced > "Key Field" to the Name field 
11. Run the Flow and observe the error

### Expected behaviour

The collection resource should be able to display SObject records before committing to the database

### Actual behaviour
Running the flow produces a browser alert "Apex Action error: Unable to read SObject"

**Comment by hackbac** [comment]
Package Name	datatable
Version Number	3.2

**Comment by ericrsmith35** [comment]
You will need to use an Apex Defined Object if your records don't have an Id field with a valid Id.

**Comment by hackbac** [comment]
Thanks for the quick reply.

An Apex defined object seems like a lot of overhead to support this
functionality.
1. Every sobject field change would also require a code change to maintain
a 1:1 mapping.
2. Every field would require both a mapping assignment to an Apex defined
object as an input to the data table.
3. Every Apex defined object property would need to be remapped back into
the sobject field in order to leverage flow insert.

> .
>

**Comment by ericrsmith35** [comment]
Typically, when creating a collection of "new" records for the datatable,
give each record a unique dummy Id prior to passing the collection to the
datatable.  For example for Opportunity records, use Id values of
006000000000001, 006000000000002, 006000000000002, ....  If you want to
later commit the collection to the object as new records, strip the Ids
before you pass the collection to a Create Records node.

Can you give a more detailed description of your use case?

**Comment by hackbac** [comment]
My use case is to use a screen flow to create a parent record (e.g. Case object) and multiple child records (e.g. a junction object.) Ideally, this flow would be `Screen for Case info => Loop to build collection => Screen for datatable to edit the collection => Insert Case => Insert child records`. The alternative process is `Screen for Case info => Create Case => Loop to build collection => Insert child records => Query child records => Screen for datatable for child records => Update child records`, which is less streamlined and can create Cases without children if the user exists the flow prematurely.

**Comment by ericrsmith35** [comment]
Your first option is certainly doable.  Just include a counter in your
"loop to build collection" and use that to assign the unique dummy id to
each record.  Be sure to have the first 3 characters of the Id match what
the child object uses for the actual Ids.

**Comment by JeroenSfdc** [comment]
@ericrsmith35 @hackbac I had the issue 'Unable to read SObject' in a specific scenario. I created an invocable method which populated a custom object. I needed to populate a formula field which a value different from what got calculated and reverted to deserializing/serializing. Somehow that list was not accepted by the data table component although 100% valid. 


```
       Planning__c p = new Planning__c();
       p.Id = <some fake id>
       String json = JSON.serialize(p);
       Map<String, Object> dataMap = (Map<String,Object>)JSON.deserializeUntyped(json);
       dataMap.remove('attributes'); // w/o this line data table comp was throwing an error
       dataMap.put('EndTime__c', Time.newInstance(14, 0, 0, 0)); // my formula field
       json = JSON.serialize(dataMap);
       Planning__c so = (Planning__c)JSON.deserializeStrict(json, Planning__c.class);
```

Is was 'fixed' once I added this line:
`dataMap.remove('attributes');`

**Comment by IvanSudakov** [comment]
> Typically, when creating a collection of "new" records for the datatable, give each record a unique dummy Id prior to passing the collection to the datatable. For example for Opportunity records, use Id values of 006000000000001, 006000000000002, 006000000000002, .... If you want to later commit the collection to the object as new records, strip the Ids before you pass the collection to a Create Records node. Can you give a more detailed description of your use case?
> […](#)

Thank you Eric, I had the same issue as @hackbac and creating/removing ids worked for me.

**Comment by nitheeshkurapati** [comment]
Hey @ericrsmith35 - We started getting this error randomly today in our production. The flow using the datatable wasn't changed recently. Any suggestions how to fix this error?

**Comment by punnareddy-git** [comment]
Hey @ericrsmith35 - we also getting the same issue too that @nitheeshkurapati and @wadams2010 getting. from last 3 days we are seeing this issue on the data table which is used in the screen flow. Please provide the fix for this as our customers are impacting? we tried many ways to fix but no luck.

**Comment by ericrsmith35** [comment]
@alexed1 @adwhite75 Any behind the scenes Salesforce changes going on that would cause this type of issue when nothing has changed in the flows or the component?

**Comment by wadams2010** [comment]
Not on my end. The flow has been in place for a few months without issues
and hasn't been changed.

**Comment by alexed1** [comment]
'Unable to read' is often a permissions issue.....is it possible that the user running the flow doesn't possess the traditional permissions?

**Comment by wadams2010** [comment]
I'm trying it as a system admin so no. Thought it was a old version so did
a full update and no luck.

**Comment by brettamurphy** [comment]
Reviving an old thread, I came upon this issue today. My use case is that I want to create a bunch of records based on previous screen decisions. I want to display these records as a confirmation before creating. Having to loop thru and setting IDs seems like a very inefficient work-around. Because after the confirmation screen, now I have to do another loop to remove them. At least I can use the built-in datatable for this piece. Not pretty, but will do the job I need here.
