### ISSUE TITLE
SendBetter - Support for New Threading Behavior 

### ISSUE THREAD

**Issue by jcallahan526** [alexed1/LightningFlowComponents#964]
**Is your feature request related to a problem? Please describe.**
I would like to User Send Better for notifications to Case Followers.  I would like the Case Followers to be able to reply to the email and update the Case.  

**Describe the solution you'd like**
The new Threading Behavior for Email-To-Case matches based on the Message-ID in the original email.  
https://help.salesforce.com/s/articleView?language=en_US&type=1&id=000355168
Can Send Better generate and apply a Message ID to emails?

**Describe alternatives you've considered**
If I enable "Save Email as Activity on Recipient Record(s)" replies will update the Case.
However this also creates a post in the Case for each email sent.

**Comment by alexed1** [comment]
@jdpond interesting....

**Comment by jdpond** [comment]
Yeah, I was looking at this @jcallahan526 there is a feature accessible if you're using templates called  **_MessageId List of existing email if this is InReplyTo_** which was added in #595.  Could you do me a favor and provide a step-by-step how-to you would like to see this work?

Thanks!

![image](https://user-images.githubusercontent.com/271131/141202428-b44a28ee-93b3-4dcb-bc94-54dc3b747991.png)

**Comment by jcallahan526** [comment]
Thanks for the Quick Responses!   
From what I understand the MessageId List allows you to populate with existing/known MessageIds.   
However when a new email is created via Better Send we need the option to generate a new MessageId.
With that said I am not sure what the formula/format is for generating the MessageId (it is not the same as the previous Thread_Id.  I guess if I knew this I could populate it in the MessageId List

**Comment by jcallahan526** [comment]
@jdpond 
Sorry for the delinquent response.  I  have cloned the necessary components and modified the BetterSendEmail.cls Apex Class to include the setReferences() method where you can pass a Message Id.
When you create an email via an SF Email Alert the system generates Message Id which is stamped in the Reference of the outgoing email.
When there is a reply to this Alert generated email the Email-To-Case service will match the incoming email to the Case based on this Message Id. Unfortunately I cannot find anywhere online regarding the format of these Message Id's required for this default matching.
However there is a workaround...
If the Message Id on incoming email matches an Email Message record (02s Object) which is related to the Case then Email-To-Case will match it to a Case - the format does not matter the Message Id on the incoming just needs to match that of an Email Message.
Below is a flow...

Attached is a screenshot of my Flow which will generate an email to the Case Contact when an Internal Users adds a Public Post (all Users) to a Case. The Flow will check if previous Email Messages exist against the Case and...
- If yes it will populate the Reference on the SendBetter email with the Message Id from the most recent Email Message
- If not it will create an Email Message record using a self generated Message Id and populate the Reference on the SendBetter email.

Happy to share this. 

![image](https://user-images.githubusercontent.com/19171783/161119197-a543df06-a331-43f6-9643-be7490fc2daa.png)

**Comment by alexed1** [comment]
Fixed in https://github.com/alexed1/LightningFlowComponents/pull/1188
