### ISSUE TITLE
File Upload Improved - Control Session Storage

### ISSUE THREAD

**Issue by mtaajama** [alexed1/LightningFlowComponents#967]
**Is your feature request related to a problem? Please describe.**
When using in flow, the uploaded files are always stored in Session Storage and retrieved from there when the component is loaded. Now when starting the flow from the beginning (even with page refresh) for an example new uploads to another record, the previous uploads are there. This is not wanted, because now user by default will remove those files (since they want to add only new files) and actually they are removed the original record.

**Describe the solution you'd like**
A controlled way to manage with boolean control are the files retrieved at all from session storage.

**Describe alternatives you've considered**
Other way to clear the session storage by the flow. Perhaps by giving an option to define the partitioning key for the session storage, we possibly could empty the storage by other component (not tested is that possible).

**Additional context**
N/A

**Comment by rygramer** [comment]
@mtaajama have you configured `{!$Flow.InterviewGuid}`? That field controls is the key to session storage, so it must be unique. There's a section in the documentation describing a few ways this can be configured: https://unofficialsf.com/from-josh-dayment-improved-file-upload-in-flow-screens/

**Comment by mtaajama** [comment]
Nope, I didn't, my bad. That solves the issue.
