### ISSUE TITLE
ConvertCSVTo Records v1.4 - Fails to Import Negative numbers, Fails to Import Checkboxes as 1/0

### ISSUE THREAD

**Issue by bottomlinebrokers** [alexed1/LightningFlowComponents#971]
Two issues with ConvertCSVToRecords v1.4 (most recent revision).

1 - I am attempting to import a negative value into a currency field "-2053".  The number imports as the positive number "2053". (Ignore the quotes).  I have not tried negative numbers into standard numbers fields.

2 - Attempting to import a column into a checkbox field with 1s and 0s representing TRUE and FALSE.  1/0 is how Salesforce exports checkbox from Reports.  However, when using 1/0, nothing is imported into the checkbox fields!  If I change the CSV data to "TRUE" or "FALSE", the field imports properly.  But when values are "1" or "0", no data is imported.

**Comment by surajp** [comment]
@alexed1 Created a PR with fixes for these issues.

**Comment by bottomlinebrokers** [comment]
Gents,

Where can I go to install the new release?

Thanks,

Mark

________________________________
