### ISSUE TITLE
Datatable Component in Flow Screen Shows AccountContactRelations but Lookup to Accounts and Contacts are Plain Text Ids, not Link-to Record Names 

### ISSUE THREAD

**Issue by nickytorstensson** [alexed1/LightningFlowComponents#976]
### Steps to reproduce

Currently installed version is 3.3.2

1. As admin (for the sake of example, who has Modify All to all records) do the following:
2. Create a screen flow
2. Add a Get data element and select object AccountContactRelation. Make sure to get All records, 
3. Add a screen element, add a Datatable component.
4. Configure the Datatable component to show the AccountContactRelation records, by selecting from all objects. Select the fields AccountId, ContactId as a minimum
5. Connect the start element to the Get element, and the Get element to the Screen element
5. Of course ensure there are data to make the component render the data
6. Save the flow and debug it

### Expected behaviour
Since the AccountContactRelation links contacts to multiple accounts (and vice versa), I presume the Account Contact Relation records are visible to all in general, and as such the lookup fields' record ids display as links and record names, because the account and contact records are editable (per our setup). Especially to an admin user, who has Modify All access.

### Actual behaviour
The lookup fields display as plain text record ids.

This is likely due to this section of the Datatable documentation.

> _In order to have the Datatable display a Lookup field as a link to the record rather than just the recordId value in the field, the running User must have Edit access to the object whose records are being displayed in the Datatable.  
For example, if you have a Datatable for Contact records and include the AccountId(Lookup) field, the running User needs to have Edit access for the Contact object in order for the AccountId field to show as a clickable link with the Account’s Name.  
Without Edit access to the Contact record, the Datatable will display, as unclickable, the Account’s recordId value._

However, this does not coincide well with the admin user having Modify All access to all objects

### Screenshots
The screenshot is from a debug of the flow. The screenshot shows 2 Datatable components, Account Contact Relations and Contact-Contact Relations. Only the Account Contact Relation object has the issue.
![image](https://user-images.githubusercontent.com/55800560/143207523-a7ebfc52-cdfd-4fa3-8225-19f0e6752218.png)

**Comment by ericrsmith35** [comment]
Not all standard Salesforce objects behave as one would expect. Try creating a custom object with Lookup fields for Account and Contact and any other fields you want for your datatable.  In your flow, loop through your Account Contact Relationship records and build a collection of records for your new custom object and use that object and collection in your datatable.

**Comment by nickytorstensson** [comment]
Hi Eric,

First and foremost, great component and great job.

On solving the issue at hand, we currently have a limitation to not be able to create more objects (though I agree, this would be a workaround), so this is not a viable workaround.

To generalize the issue: I hope you can help me understand the setup of the Datatable component. In general, for the Datatable component to be able to render the objects' lookup fields as names and links, I presume the component queries the lookup fields' names. Wouldn't this also (in principle) be possible for the Account Contact Relationship records?

**Comment by ericrsmith35** [comment]
The processing of the Lookup fields happen here in lines 262-299.  https://github.com/alexed1/LightningFlowComponents/blob/master/flow_screen_components/datatable/force-app/main/default/classes/ers_DatatableController.cls

**Comment by nickytorstensson** [comment]
Hi Eric,

Thanks for the link! I looked into the code with some debug statements and found that the variable `curRR.lookupFieldList` is not set for AccountContactRelation records. It is just empty. And thus, the code in lines 269-276 does not run

I presume it should be set, but I might need to find where it is _not_ being set. It will take some looking into, but perhaps you have a quick pointer to where (or maybe even now know why it is not being set)?

As a suggestion, these current lines exist:
Line 135: `curRR = getColumnData(curRR, fieldNames, objName);`
Line 136: `curRR = getLookupData(curRR, records, curRR.lookupFieldList, objName);`
Before we execute line 136, would it make sense to run the selected fields (`fieldNames`) through a field.getDescribe method to determine if they are lookup/master-detail? If so, then we can add them to the `curRR.lookupFieldList` and execute line 136? Of course, I don't know if this is redundant, but just a suggestion.

Looking forward to your input.

**Comment by nickytorstensson** [comment]
Hi Erik,

Please ignore my previous post, I found that it all boils down to, that the fields on AccountContactRelation object are not updatable (thus line 199 doesn't set the variable, that line 249 uses, which in turn results in 269-276 not being run).
https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_accountcontactrelation.htm

My question is now, why do the fields, that are references (lookup/master-detail), need to be updatable as per line 199? I know there is a bigger picture (more code complexity) to consider, but would it not suffice that it is readable?

**Comment by ericrsmith35** [comment]
It has to do with how the controller is updating the record collection
being passed to the datatable to include a cross-object value.

**Comment by nickytorstensson** [comment]
I closed the issue. While it would be a nice-to-have that the IDs of lookup fields, which are not editable, are populated with links to the parent record, it is working as designed.
