### ISSUE TITLE
Datatable - not allowing data types other than String

### ISSUE THREAD

**Issue by SusanD04** [alexed1/LightningFlowComponents#99]
I am using the Datatable Flow Screen Component with the Contact object.  It has correctly displayed String and Date fields, but I have not been able to get it to display any number fields.  I wasn't exactly sure what types it would accept, so I've tried "Double", "Number", "Currency" and none of those have worked.  Do you have a list of data types accepted by the Datatable?  And do you have any thoughts on why number fields are not displaying?  Similarly, can Datatable display fields that are the result of a formula, rollup, or DLRS rollup?

**Comment by alexed1** [comment]
Datatable uses this component: https://developer.salesforce.com/docs/component-library/bundle/lightning:datatable/documentation

I'm not surprised to hear that its internal capabilities to convert types to string is limited, but Flow gives you a lot of ways to deal with that. For example, if you have a picklist, you can convert it in flow to a string using the formula TEXT(myPicklist). At that point you should be able to give the formula to the datatable (or you may need to first assign the value of the formula to a separate string variable).

The things that TEXT function can convert are described in https://help.salesforce.com/articleView?id=customize_functions.htm&type=5 : 

TEXT | Converts a percent, number, date, date/time, or currency type field into text anywhere formulas are used. Also, converts picklist values to text in approval rules, approval step rules, workflow rules, escalation rules, assignment rules, auto-response rules, validation rules, formula fields, field updates, and custom buttons and links.

**Comment by steveecl** [comment]
Hi, how I would achieve assigning a variable to the datatable to resolve this issue and get numbers displaying, since it is parsing field names?
