### ISSUE TITLE
datatable - Master/detail field without re-parenting enabled showing Id 

### ISSUE THREAD

**Issue by JeroenSfdc** [alexed1/LightningFlowComponents#995]
### Steps to reproduce

1. Set-up a Flow with a Screen including data table component
2. Query a List of records including a M/D relationship field which is configured as not re-parentable
3. The data table will show the Id instead of the Lookup name. 

### Expected behaviour
Per documentation it should not show a link, still it should show the Name field (without a link) - that is the expectation. 

### Actual behaviour
Relationship field (Id) is showing instead of Name field. 

### Screenshots
HouseholdHelp is a m/d field. 
When I flip to re-parentable, it will show correct. 

![image](https://user-images.githubusercontent.com/27854769/147162007-a431582d-dc06-43b0-8b2b-ac7c35e44201.png)

![image](https://user-images.githubusercontent.com/27854769/147162107-966889a2-05a1-4817-babb-7eaf3e2820b2.png)

### Debug Logs
- None

**Comment by JeroenSfdc** [comment]
I found it in the code; explicitly mentioned.

```
                when 'REFERENCE' {
                    if (dfr.isUpdateable()) {       // Only works with Master-Detail fields that are reparentable
                        lookupFields.add(fieldName);
                    }
                }
```

**Comment by ericrsmith35** [comment]
The Name will only be displayed for a reparentable M-D field, otherwise just the actual value of the field(ID) will be shown.
